### ISSUE TITLE
Release 22.2.0 failed to create admin account on remote management database (MySQL) during init setup

### ISSUE THREAD

**Issue by fredpan** [dbeaver/cloudbeaver#1179]
**Describe the bug**
When I use MySQL as remote management database, it failed to grant admin permission during initial setup.

**To Reproduce**
1. in cloudbeaver.conf, use mysql as management database
2. run docker image and follow the init process
3. you will find that the username/pwd you just set to your admin account is not working.

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser Chrome
 - Version 22.2.0

**Additional context**
```
09:37:06.061 [qtp1349168118-34] DEBUG i.c.server.graphql.GraphQLEndpoint - API > configureServer 
09:37:06.066 [qtp1349168118-34] INFO  i.c.service.security.db.CBDatabase - Configure CB database security 
09:37:06.106 [qtp1349168118-34] DEBUG io.cloudbeaver.server.CBApplication - Saving runtime configuration 
09:37:06.126 [qtp1349168118-34] ERROR io.cloudbeaver.server.CBApplication - Error granting anonymous access to connections 
org.jkiss.dbeaver.model.exec.DBCException: Error granting object permissions 
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.setObjectPermissions(CBEmbeddedSecurityController.java:1565) ~[na:na] 
	at io.cloudbeaver.server.CBApplication.grantAnonymousAccessToConnections(CBApplication.java:816) ~[na:na] 
	at io.cloudbeaver.server.CBApplication.finishConfiguration(CBApplication.java:773) ~[na:na] 
	at io.cloudbeaver.service.admin.impl.WebServiceAdmin.configureServer(WebServiceAdmin.java:619) ~[na:na] 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na] 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na] 
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na] 
	at io.cloudbeaver.service.WebServiceBindingBase$ServiceInvocationHandler.invoke(WebServiceBindingBase.java:165) ~[na:na] 
	at com.sun.proxy.$Proxy12.configureServer(Unknown Source) ~[na:na] 
	at io.cloudbeaver.service.admin.WebServiceBindingAdmin.lambda$31(WebServiceBindingAdmin.java:164) ~[na:na] 
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258) ~[na:na] 
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:197) ~[na:na] 
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[na:na] 
	at graphql.execution.Execution.executeOperation(Execution.java:160) ~[na:na] 
	at graphql.execution.Execution.execute(Execution.java:101) ~[na:na] 
	at graphql.GraphQL.execute(GraphQL.java:591) ~[na:na] 
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521) ~[na:na] 
	at graphql.GraphQL.executeAsync(GraphQL.java:495) ~[na:na] 
	at graphql.GraphQL.execute(GraphQL.java:426) ~[na:na] 
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeQuery(GraphQLEndpoint.java:254) ~[na:na] 
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeSingleQuery(GraphQLEndpoint.java:200) ~[na:na] 
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.doPost(GraphQLEndpoint.java:183) ~[na:na] 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[na:na] 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[na:na] 
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[na:na] 
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508) ~[na:na] 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na] 
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[na:na] 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na] 
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[na:na] 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[na:na] 
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[na:na] 
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[na:na] 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[na:na] 
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[na:na] 
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[na:na] 
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[na:na] 
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[na:na] 
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[na:na] 
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[na:na] 
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[na:na] 
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[na:na] 
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[na:na] 
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[na:na] 
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[na:na] 
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9] 
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na] 
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`cloudbeaver_test`.`CB_OBJECT_PERMISSIONS`, CONSTRAINT `CB_OBJECT_PERMISSIONS_ibfk_1` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `CB_AUTH_SUBJECT` (`SUBJECT_ID`) ON DELETE CASCADE) 
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[na:na] 
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[na:na] 
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[na:na] 
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371) ~[na:na] 
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[na:na] 
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[na:na] 
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.setObjectPermissions(CBEmbeddedSecurityController.java:1556) ~[na:na] 
	... 53 common frames omitted 
09:37:06.127 [qtp1349168118-34] DEBUG io.cloudbeaver.server.CBApplication - Reloading application configuration 
09:37:06.127 [qtp1349168118-34] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/opt/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf] 
09:37:06.131 [qtp1349168118-34] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from '/opt/cloudbeaver/conf/product.conf' 
09:37:06.171 [qtp1349168118-34] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: ClickHouse (Legacy),ClickHouse,DB2 LUW,DB2 iSeries/AS 400,Firebird,Derby Server,Trino,H2 Embedded,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite 
09:37:06.178 [qtp1349168118-36] DEBUG i.c.server.graphql.GraphQLEndpoint - API > serverConfig 
09:37:06.204 [qtp1349168118-34] DEBUG i.c.server.graphql.GraphQLEndpoint - API > openSession 
09:37:06.218 [qtp1349168118-38] DEBUG i.c.server.graphql.GraphQLEndpoint - API > sessionPermissions 
09:37:06.218 [qtp1349168118-36] DEBUG i.c.server.graphql.GraphQLEndpoint - API > getActiveUser 
09:37:06.287 [qtp1349168118-37] DEBUG i.c.server.graphql.GraphQLEndpoint - API > getAuthProviders 
09:37:23.085 [qtp1349168118-38] DEBUG i.c.server.graphql.GraphQLEndpoint - API > sessionState 
09:38:24.074 [qtp1349168118-36] DEBUG i.c.server.graphql.GraphQLEndpoint - API > sessionState 
09:39:25.071 [qtp1349168118-38] DEBUG i.c.server.graphql.GraphQLEndpoint - API > sessionState 

```

**Comment by fredpan** [comment]
I just figured it out, I accidently delete the db init config from cloudbeaver.conf. Now it fixed
