### ISSUE TITLE
Runtime bug

### ISSUE THREAD

**Issue by killerwzb** [dbeaver/cloudbeaver#118]
**Describe the bug**
Hi:
   I run the run-server.bat at windows operation system, and show this:
2020-07-14 16:36:49.172 - Using configuration conf/cloudbeaver.conf
2020-07-14 16:36:49.234 - Load product configuration from 'F:\test\cloudbeaver\deploy\cloudbeaver\conf\product.conf'
2020-07-14 16:36:49.234 - Error reading product configuration
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 19 column 10 path $..app.logViewer
        at com.google.gson.Gson.fromJson(Gson.java:903)
        at com.google.gson.Gson.fromJson(Gson.java:853)
        at org.jkiss.dbeaver.model.data.json.JSONUtils.parseMap(JSONUtils.java:259)
        at io.cloudbeaver.server.CBApplication.parseConfiguration(CBApplication.java:300)
        at io.cloudbeaver.server.CBApplication.loadConfiguration(CBApplication.java:240)
        at io.cloudbeaver.server.CBApplication.start(CBApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 19 column 10 path $..app.logViewer

I can not find the problem from the product.conf.

**Comment by Wroud** [comment]
Seems exception caused by extra `,` on line 18 in product.conf, I'm pushed the fix, also you can just remove `,` by yourself

**Comment by killerwzb** [comment]
thanks.

**Comment by brettinternet** [comment]
The example configuration here has an extra comma on line 55 after `sm` block. https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#using-environment-variables
