### ISSUE TITLE
Oracle database connection error:

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1181]
Hello, I am trying to connect my `oracle `database via `cloudbeaver `but I am getting the following error.
![image](https://user-images.githubusercontent.com/52106718/192381404-562ecdd7-f6f0-48b8-8b05-6e5088ea2343.png)
![image](https://user-images.githubusercontent.com/52106718/192381460-333aaa08-e285-457b-9d37-46212944ff0a.png)

Logs:
[log-error-conexion-oracle.txt](https://github.com/dbeaver/cloudbeaver/files/9649689/log-error-conexion-oracle.txt)

**Comment by kseniaguzeeva** [comment]
Unfortunately, I cannot reproduce the issue. Could you please provide me more details about your database connection:
1. Do you use SSH?
2. What's your connection settings (including service type and role)?
3. Can you connect to the database via another application (e.g. DBeaver)?
4. Could you also please send error details in English.

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva   i am running cloudbeaver in run mode from eclipse
![image](https://user-images.githubusercontent.com/52106718/192540137-d30fb1f2-ee18-4ef5-acb4-4071e055ee54.png)

1. I don't use ssh

2.1. manual configuration
![image](https://user-images.githubusercontent.com/52106718/192541483-ec9c4022-db96-4b53-929e-8ba5d33c8947.png)

2.2. type of service and role
![image](https://user-images.githubusercontent.com/52106718/192541755-c42fa97f-f673-4427-96e4-4071e66bb7e5.png)
![image](https://user-images.githubusercontent.com/52106718/192544236-82fc652e-5358-4ae1-982a-636071540c04.png)

3. If I can connect to the database through the dbeaver application.
 download the dbeaver application from the official website, and successfully connect to the oracle database
![image](https://user-images.githubusercontent.com/52106718/192547816-5d244006-aed8-4c99-a099-e842f47e2ffc.png)


perform another test from eclipse java and run dbeaver, I tried to connect but this time I was unsuccessful, and it gives me the following error
![image](https://user-images.githubusercontent.com/52106718/192550117-9d1b3b03-ab62-4d5b-8618-b7abc797f801.png)

**error message translation**
ORA-00604: recursive SQL level 1 error occurred
ORA-12705: NLS data files cannot be accessed or invalid environment specified


the error is the same when running cloudbeaver from eclipse java both projects have the same error
do another test installing cloudbeaver on a server but this time using cloudbeaver repository as docker, but this time i was successful connecting to oracle database
![image](https://user-images.githubusercontent.com/52106718/192552157-c2c26808-e162-4c27-9dc6-b75b6c9572cb.png)


4. translated error details
![image](https://user-images.githubusercontent.com/52106718/192553277-c49b6cbf-540a-4372-bd30-a5128bb241f7.png)
**translation**
Connection test failed
Error connecting to database:
Connection failed:
ORA-00604: recursive SQL level 1 error occurred
ORA-12705: NLS data files cannot be accessed or invalid environment specified

error details
![image](https://user-images.githubusercontent.com/52106718/192553672-ec76fe54-4e6a-4068-a1d5-4626b5570483.png)
**translation**


**error details**

Error connecting to database:
Connection failed:
ORA-00604: recursive SQL level 1 error occurred
ORA-12705: NLS data files cannot be accessed or invalid environment specified


**details error content**
java.sql.SQLException: ORA-00604: recursive SQL level 1 error occurred
ORA-12705: NLS data files cannot be accessed or invalid environment specified

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:441)
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:436)
at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1061)
at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:550)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:499)
at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1279)
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:663)
at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:194)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:213)
at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:211)
at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:171)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:116)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:90)
at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:89)
at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:953)
at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:520)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)



@kseniaguzeeva, I sent you all the data you asked for and some tests I did, I hope you can replicate the error and help me I am trying to connect to an oracle 11g database


I only have this problem with the oracle database, since with the postgresql database I have a correct connection

**Comment by kseniaguzeeva** [comment]
Thank you for the details. According the information you provided, it's a DBeaver issue. Could you please create the ticket with the details on other [board](https://github.com/dbeaver/dbeaver/issues) in order to Dbeaver command could fix it?
