### ISSUE TITLE
Server configuration use postgresql database initializing database error

### ISSUE THREAD

**Issue by chacha95** [dbeaver/cloudbeaver#1227]
**Describe the bug**
server configuration
```yaml
server: {
  serverPort: 8978,

  workspaceLocation: "workspace",
  contentRoot: "web",
  driversLocation: "drivers",

  rootURI: "/cloudbeaver/",
  serviceURI: "/api/",

  productConfiguration: "conf/product.conf",

  expireSessionAfterPeriod: 1800000,

  develMode: false,

  enableSecurityManager: false,

  database: {
    driver="postgres-jdbc",
    url: "jdbc:postgresql://postgresql.database.svc.cluster.local/dingo",
    user: "dingo",
    password: "dingo",

    createDatabase: true,

    initialDataConfiguration: "conf/initial-data.conf",

    pool: {
      minIdleConnections: 4,
      maxIdleConnections: 10,
      maxConnections: 100,
      validationQuery: "SELECT 1"
    }
  }
},
app: {
  anonymousAccessEnabled: true,
  anonymousUserRole: "user",
  supportsCustomConnections: false,

  forwardProxy: false,

  publicCredentialsSaveEnabled: true,
  adminCredentialsSaveEnabled: true,

  resourceManagerEnabled: true,

  resourceQuotas: {
    dataExportFileSizeLimit: 10000000,
    resourceManagerFileSizeLimit: 500000,
    sqlMaxRunningQueries: 100,
    sqlResultSetRowsLimit: 100000,
    sqlResultSetMemoryLimit: 2000000,
    sqlTextPreviewMaxLength: 4096,
    sqlBinaryPreviewMaxLength: 261120
  },
  enabledAuthProviders: [
      "local"
  ],

  disabledDrivers: [
    "sqlite:sqlite_jdbc",
    "h2:h2_embedded",
    "clickhouse:yandex_clickhouse"
  ]
}
```
**Error Info**
```sh
08:50:12.966 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [CREATE TABLE IF NOT EXISTS CB_SCHEMA_INFO (
    VERSION INTEGER NOT NULL,
    UPDATE_TIME TIMESTAMP NOT NULL
)]
08:50:12.966 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [CREATE TABLE IF NOT EXISTS CB_INSTANCE(
    INSTANCE_ID CHAR(36) NOT NULL,              -- Unique instance ID

    MAC_ADDRESS CHAR(12) NOT NULL,
    HOST_NAME VARCHAR(128) NOT NULL,

    PRODUCT_NAME VARCHAR(100) NOT NULL,         -- Server product name
    PRODUCT_VERSION VARCHAR(32) NOT NULL,       -- Server product version

    UPDATE_TIME TIMESTAMP NOT NULL,

    PRIMARY KEY(INSTANCE_ID)
)]
08:50:12.967 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [CREATE TABLE IF NOT EXISTS CB_INSTANCE_DETAILS(
    INSTANCE_ID CHAR(36) NOT NULL,              -- Unique instance ID
    FIELD_NAME VARCHAR(32) NOT NULL,
    FIELD_VALUE VARCHAR(255),

    PRIMARY KEY(INSTANCE_ID, FIELD_NAME),
    FOREIGN KEY(INSTANCE_ID) REFERENCES CB_INSTANCE(INSTANCE_ID)
)]
08:50:12.967 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [CREATE SEQUENCE CB_INSTANCE_EVENT_EVENT_ID]
08:50:13.058 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - Error updating CB schema version from 1 to 2
org.postgresql.util.PSQLException: ERROR: relation "cb_instance_event_event_id" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[na:na]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291) ~[na:na]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286) ~[na:na]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[na:na]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:175) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:119) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:101) ~[na:na]
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189) ~[na:na]
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:57) ~[na:na]
	at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:464) ~[na:na]
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:460) ~[na:na]
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:320) ~[na:na]
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:165) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
08:50:13.060 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:193) ~[na:na]
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:57) ~[na:na]
	at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:464) ~[na:na]
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:460) ~[na:na]
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:320) ~[na:na]
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:165) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
Caused by: org.jkiss.dbeaver.DBException: Error updating CB schema version
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:108) ~[na:na]
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189) ~[na:na]
	... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "cb_instance_event_event_id" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[na:na]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315) ~[na:na]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291) ~[na:na]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286) ~[na:na]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[na:na]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:175) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:119) ~[na:na]
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:101) ~[na:na]
	... 19 common frames omitted
08:50:13.064 [Framework stop - Equinox Container: 32f9e883-5692-4eaf-bf38-3855b27ed2df] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
08:50:13.186 [Framework stop - Equinox Container: 32f9e883-5692-4eaf-bf38-3855b27ed2df] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 122ms
```

**Comment by chacha95** [comment]
I think this is very similary to [this issue](https://github.com/dbeaver/cloudbeaver/issues/968)
and my cloudbeaver version is 22.2.0

**Comment by miltonchirinos44** [comment]
That's weird, I used the same configuration to connect the default database with postgresql and I didn't have any errors.
You may need to indicate the port
maybe it would be something like this
**url: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/dingo"**

**Comment by chacha95** [comment]
I just try 
url: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/dingo"
but result is same....

**Comment by miltonchirinos44** [comment]
You have to modify in the following location:
cloudbeaver
    |---config
         |---sample-databases
              |---DefaultConfiguration
                   |---cloudbeaver.conf

```
...
database: {
     driver="postgres-jdbc",
     url: "jdbc:postgresql://ip:5432/baseDatos",
     user: "postgres",
     password: "postgres",
     
     createDatabase: true,
     ...,
     ...,
     ...,
}
```

**Comment by kseniaguzeeva** [comment]
I cannot reproduce it either. Could you please try to use such config and command example. The mentioned database must exist in PostgreSQL
```
{
  "server": {
    "serverName": "CloudBeaver CE Server",
    "serverURL": "http://localhost:8090",
    "expireSessionAfterPeriod": 1800000,
    "database": {
        "driver": "postgres-jdbc",
        "url": "jdbc:postgresql://local_host_number:5432/cb",
        "user": "user_name",
        "password": "user_password"
    }
  }
}
```

`docker run --name cloudbeaver --rm -ti -p 8978:8978 --add-host=host.docker.internal:local_host_number -v C:\var\cloudbeaver\workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:22.2.3`

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva what is the operation of this command:

`docker run --name cloudbeaver --rm -ti -p 8978:8978 --add-host=host.docker.internal:local_host_number -v C:\var\cloudbeaver\workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:22.2.3`

For example, to change the h2 database to postgresql, use the following steps:

- use the settings
```
{
  "server": {
    "serverName": "CloudBeaver CE Server",
    "serverURL": "http://localhost:8090",
    "expireSessionAfterPeriod": 1800000,
    "database": {
        "driver": "postgres-jdbc",
        "url": "jdbc:postgresql://local_host_number:5432/cb",
        "user": "user_name",
        "password": "user_password"
    }
  }
}
```

- run the following commands to build the cloudbeaver project with the new changes so that the files in the `cloudbeaver/deploy` folder where the compiled files are are also updated:

```
cd cloudbeaver
cd deploy
./build.sh
```


in this way the cloudbeaver project has been updated with the new database connection changes from h2 to postgresql

**Comment by kseniaguzeeva** [comment]
You can use PostgreSQL database as internal using the steps above https://github.com/dbeaver/cloudbeaver/issues/1227#issuecomment-1293264598

**Comment by miltonchirinos44** [comment]
> Puede usar la base de datos PostgreSQL como interna siguiendo los pasos anteriores [# 1227 (comentario)](https://github.com/dbeaver/cloudbeaver/issues/1227#issuecomment-1293264598)


Database connection successfully verified

**Comment by kseniaguzeeva** [comment]
Feel free to ask to reopen the ticket if the issue is still actual for you.
