### ISSUE TITLE
Cannot update a component (`Tab`) while rendering 

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1228]
When I click the SQL button to generate a `script` I get the following error in my browser console, it gets to a point where several warnings appear every time I press the SQL button.

Apparently there are errors in the components `(`TabsState`)`, `(`CaptureView`)` and `(`NavigationNodeElement`)`, I am using the latest version of cloudbeaver, the error is displayed in the following image

![image](https://user-images.githubusercontent.com/52106718/196974726-99faa188-6ca3-4cd5-b92e-9dc28f227fc4.png)

Error

```
react_devtools_backend.js:4026 Warning: Cannot update a component (`Tab`) while rendering a different component (`TabsState`). To locate the bad setState() call inside `TabsState`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at TabsBox (webpack-internal:///../core-ui/src/Tabs/TabsBox/TabsBox.tsx:83:124)
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at SlideElement (webpack-internal:///../core-blocks/src/Slide/SlideElement.tsx:18:57)
    at div
    at SlideBox (webpack-internal:///../core-blocks/src/Slide/SlideBox.tsx:23:49)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at main
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at AppScreen (webpack-internal:///../core-app/src/AppScreen/AppScreen.tsx:31:96)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at DndProvider (webpack-internal:///../../node_modules/react-dnd/dist/core/DndProvider.js:43:11)
    at DNDProvider (webpack-internal:///../core-ui/src/DragAndDrop/DNDProvider.tsx:19:55)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at Suspense
    at AppContext (webpack-internal:///../core-di/src/AppContext.tsx:27:53)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react-dom.development.js?a814:86
error @ react-dom.development.js?a814:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js?a814:27492
scheduleUpdateOnFiber @ react-dom.development.js?a814:25498
dispatchSetState @ react-dom.development.js?a814:17527
forceUpdate @ useObserver.js?7c84:44
eval @ useObserver.js?7c84:60
runReaction_ @ mobx.esm.js?db9f:2501
runReactionsHelper @ mobx.esm.js?db9f:2680
reactionScheduler @ mobx.esm.js?db9f:2652
eval @ mobx.esm.js?db9f:2693
batchedUpdates$1 @ react-dom.development.js?a814:26140
reactionScheduler @ mobx.esm.js?db9f:2692
runReactions @ mobx.esm.js?db9f:2661
endBatch @ mobx.esm.js?db9f:2281
track @ mobx.esm.js?db9f:2561
useObserver @ useObserver.js?7c84:113
observerComponent @ observer.js?9e13:42
renderWithHooks @ react-dom.development.js?a814:16305
updateFunctionComponent @ react-dom.development.js?a814:19588
updateSimpleMemoComponent @ react-dom.development.js?a814:19425
beginWork @ react-dom.development.js?a814:21678
beginWork$1 @ react-dom.development.js?a814:27426
performUnitOfWork @ react-dom.development.js?a814:26557
workLoopSync @ react-dom.development.js?a814:26466
renderRootSync @ react-dom.development.js?a814:26434
performConcurrentWorkOnRoot @ react-dom.development.js?a814:25738
workLoop @ scheduler.development.js?e22e:266
flushWork @ scheduler.development.js?e22e:239
performWorkUntilDeadline @ scheduler.development.js?e22e:533
react_devtools_backend.js:4026 Warning: Cannot update a component (`CaptureView`) while rendering a different component (`SqlEditor`). To locate the bad setState() call inside `SqlEditor`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at ComplexLoader (webpack-internal:///../core-blocks/src/ComplexLoader.tsx:42:87)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Comp (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:50:26)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at TabsBox (webpack-internal:///../core-ui/src/Tabs/TabsBox/TabsBox.tsx:83:124)
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at SlideElement (webpack-internal:///../core-blocks/src/Slide/SlideElement.tsx:18:57)
    at div
    at SlideBox (webpack-internal:///../core-blocks/src/Slide/SlideBox.tsx:23:49)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at main
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at AppScreen (webpack-internal:///../core-app/src/AppScreen/AppScreen.tsx:31:96)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at DndProvider (webpack-internal:///../../node_modules/react-dnd/dist/core/DndProvider.js:43:11)
    at DNDProvider (webpack-internal:///../core-ui/src/DragAndDrop/DNDProvider.tsx:19:55)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at Suspense
    at AppContext (webpack-internal:///../core-di/src/AppContext.tsx:27:53)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react-dom.development.js?a814:86
error @ react-dom.development.js?a814:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js?a814:27492
scheduleUpdateOnFiber @ react-dom.development.js?a814:25498
dispatchSetState @ react-dom.development.js?a814:17527
forceUpdate @ useObserver.js?7c84:44
eval @ useObserver.js?7c84:60
runReaction_ @ mobx.esm.js?db9f:2501
runReactionsHelper @ mobx.esm.js?db9f:2680
reactionScheduler @ mobx.esm.js?db9f:2652
eval @ mobx.esm.js?db9f:2693
batchedUpdates$1 @ react-dom.development.js?a814:26140
reactionScheduler @ mobx.esm.js?db9f:2692
runReactions @ mobx.esm.js?db9f:2661
endBatch @ mobx.esm.js?db9f:2281
track @ mobx.esm.js?db9f:2561
useObserver @ useObserver.js?7c84:113
observerComponent @ observer.js?9e13:42
renderWithHooks @ react-dom.development.js?a814:16305
updateFunctionComponent @ react-dom.development.js?a814:19588
updateSimpleMemoComponent @ react-dom.development.js?a814:19425
updateMemoComponent @ react-dom.development.js?a814:19284
beginWork @ react-dom.development.js?a814:21673
beginWork$1 @ react-dom.development.js?a814:27426
performUnitOfWork @ react-dom.development.js?a814:26557
workLoopSync @ react-dom.development.js?a814:26466
renderRootSync @ react-dom.development.js?a814:26434
performConcurrentWorkOnRoot @ react-dom.development.js?a814:25738
workLoop @ scheduler.development.js?e22e:266
flushWork @ scheduler.development.js?e22e:239
performWorkUntilDeadline @ scheduler.development.js?e22e:533
react_devtools_backend.js:4026 You should provide either `aria-label` or `aria-labelledby` props. 
 See https://reakit.io/docs/tab 
    at Comp (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:50:26)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at ComplexLoader (webpack-internal:///../core-blocks/src/ComplexLoader.tsx:42:87)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Comp (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:50:26)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at TabsBox (webpack-internal:///../core-ui/src/Tabs/TabsBox/TabsBox.tsx:83:124)
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at SlideElement (webpack-internal:///../core-blocks/src/Slide/SlideElement.tsx:18:57)
    at div
    at SlideBox (webpack-internal:///../core-blocks/src/Slide/SlideBox.tsx:23:49)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at main
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at AppScreen (webpack-internal:///../core-app/src/AppScreen/AppScreen.tsx:31:96)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at DndProvider (webpack-internal:///../../node_modules/react-dnd/dist/core/DndProvider.js:43:11)
    at DNDProvider (webpack-internal:///../core-ui/src/DragAndDrop/DNDProvider.tsx:19:55)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at Suspense
    at AppContext (webpack-internal:///../core-di/src/AppContext.tsx:27:53)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
overrideMethod @ react_devtools_backend.js:4026
warning @ warning.js?2a1f:27
eval @ useWarning.js?a72e:22
commitHookEffectListMount @ react-dom.development.js?a814:23150
commitPassiveMountOnFiber @ react-dom.development.js?a814:24926
commitPassiveMountEffects_complete @ react-dom.development.js?a814:24891
commitPassiveMountEffects_begin @ react-dom.development.js?a814:24878
commitPassiveMountEffects @ react-dom.development.js?a814:24866
flushPassiveEffectsImpl @ react-dom.development.js?a814:27039
flushPassiveEffects @ react-dom.development.js?a814:26984
performSyncWorkOnRoot @ react-dom.development.js?a814:26076
flushSyncCallbacks @ react-dom.development.js?a814:12042
commitRootImpl @ react-dom.development.js?a814:26959
commitRoot @ react-dom.development.js?a814:26682
finishConcurrentRender @ react-dom.development.js?a814:25981
performConcurrentWorkOnRoot @ react-dom.development.js?a814:25809
workLoop @ scheduler.development.js?e22e:266
flushWork @ scheduler.development.js?e22e:239
performWorkUntilDeadline @ scheduler.development.js?e22e:533
react_devtools_backend.js:4026 Warning: Cannot update a component (`NavigationNodeElement`) while rendering a different component (`ElementsTree`). To locate the bad setState() call inside `ElementsTree`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
    at div
    at Pane (webpack-internal:///../../node_modules/go-split/lib/Pane.js:11:62)
    at Pane
    at div
    at Split (webpack-internal:///../../node_modules/go-split/lib/Split.js:13:9)
    at Split
    at main
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at AppScreen (webpack-internal:///../core-app/src/AppScreen/AppScreen.tsx:31:96)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at div
    at DndProvider (webpack-internal:///../../node_modules/react-dnd/dist/core/DndProvider.js:43:11)
    at DNDProvider (webpack-internal:///../core-ui/src/DragAndDrop/DNDProvider.tsx:19:55)
    at observerComponent (webpack-internal:///../../node_modules/mobx-react-lite/es/observer.js:50:73)
    at Suspense
    at AppContext (webpack-internal:///../core-di/src/AppContext.tsx:27:53)
    at ErrorBoundary (webpack-internal:///../core-blocks/src/ErrorBoundary.tsx:69:115)
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react-dom.development.js?a814:86
error @ react-dom.development.js?a814:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js?a814:27492
scheduleUpdateOnFiber @ react-dom.development.js?a814:25498
dispatchSetState @ react-dom.development.js?a814:17527
forceUpdate @ useObserver.js?7c84:44
eval @ useObserver.js?7c84:60
runReaction_ @ mobx.esm.js?db9f:2501
runReactionsHelper @ mobx.esm.js?db9f:2680
reactionScheduler @ mobx.esm.js?db9f:2652
eval @ mobx.esm.js?db9f:2693
batchedUpdates$1 @ react-dom.development.js?a814:26140
reactionScheduler @ mobx.esm.js?db9f:2692
runReactions @ mobx.esm.js?db9f:2661
endBatch @ mobx.esm.js?db9f:2281
track @ mobx.esm.js?db9f:2561
useObserver @ useObserver.js?7c84:113
observerComponent @ observer.js?9e13:42
renderWithHooks @ react-dom.development.js?a814:16305
updateFunctionComponent @ react-dom.development.js?a814:19588
updateSimpleMemoComponent @ react-dom.development.js?a814:19425
beginWork @ react-dom.development.js?a814:21678
beginWork$1 @ react-dom.development.js?a814:27426
performUnitOfWork @ react-dom.development.js?a814:26557
workLoopSync @ react-dom.development.js?a814:26466
renderRootSync @ react-dom.development.js?a814:26434
performConcurrentWorkOnRoot @ react-dom.development.js?a814:25738
workLoop @ scheduler.development.js?e22e:266
flushWork @ scheduler.development.js?e22e:239
performWorkUntilDeadline @ scheduler.development.js?e22e:533
:3100/#/:1 Uncaught (in promise) undefined
```

error file

[error.txt](https://github.com/dbeaver/cloudbeaver/files/9831015/error.txt)

**Comment by devnaumov** [comment]
@miltonchirinos44 Thanks for the report. We know about the issue and will fix it in the future. You can ignore it if it's not blocking you from the development process.
