### ISSUE TITLE
 Error executing the command to run cloudbeaver in development mode

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1288]
I recently upgraded the cloudbeaver project from java 11 to 17 since the dbeaver developer group upgraded the jdk 11 to jdk 17, I did all the steps to be able to deploy the project in eclipse java, I had no problems with that step, I managed to run cloudbeaver from eclipise java and i can view cloudbeaver from address http://localhost:8978. The problem I'm having is when I run the command to enable development mode I get the following error:

COMMAND:
`lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=http://localhost:8978 `

MISTAKE:
![image](https://user-images.githubusercontent.com/52106718/202196938-2b5cb927-9ade-489a-a1a5-193bb71c54dc.png)

```
$ lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=http://localhost:8978
info cli using local version of lerna
lerna notice cli v5.5.4
lerna info versioning independent
lerna notice filter including "@cloudbeaver/product-default"
lerna info filter [ '@cloudbeaver/product-default' ]
lerna info Executing command in 1 package: "yarn run dev -- --env server=http://localhost:8978"
lerna success run Ran npm script 'dev' in 1 package in 0.4s:
lerna success - @cloudbeaver/product-default
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
(node:4380) UnhandledPromiseRejectionWarning: Error: Command failed with UNKNOWN: yarn run dev -- --env server=http://localhost:8978
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at execa (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\execa\index.js:83:26)
    at spawnProcess (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:127:17)
    at Object.spawnStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:67:19)
    at npmRunScriptStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\npm-run-script\npm-run-script.js:26:23)
    at RunCommand.runScriptInPackageStreaming (C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:302:12)
    at C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:141:23
    at C:\Users\milton2\Desktop\procloudbeaver\cloudbeaver\webapp\node_modules\@lerna\run-topologically\run-topologically.js:34:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
How can I solve this problem since I can't run cloudbeaver in development mode?

**Comment by kseniaguzeeva** [comment]
Could you please write the name of the ticket in English?

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva   is already corrected

Mention again that it is failing is failing the development mode steps to replicate the problem please review
![image](https://user-images.githubusercontent.com/52106718/202478203-da7bb2f7-2b28-4401-b5de-3ff7d42e3b83.png)

the error is still the same:
![image](https://user-images.githubusercontent.com/52106718/202479120-d343157d-41f6-49a9-9b65-71411addd189.png)

**ERROR:**
```
$ lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=localhost:8978
info cli using local version of lerna
lerna notice cli v5.5.4
lerna info versioning independent
lerna notice filter including "@cloudbeaver/product-default"
lerna info filter [ '@cloudbeaver/product-default' ]
lerna info Executing command in 1 package: "yarn run dev -- --env server=localhost:8978"
lerna success run Ran npm script 'dev' in 1 package in 0.4s:
lerna success - @cloudbeaver/product-default
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
(node:19536) UnhandledPromiseRejectionWarning: Error: Command failed with UNKNOWN: yarn run dev -- --env server=localhost:8978
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at execa (C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\execa\index.js:83:26)
    at spawnProcess (C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:127:17)
    at Object.spawnStreaming (C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\child-process\index.js:67:19)
    at npmRunScriptStreaming (C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\npm-run-script\npm-run-script.js:26:23)
    at RunCommand.runScriptInPackageStreaming (C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:302:12)
    at C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\run\index.js:141:23
    at C:\Users\milton7\Desktop\proyectoCloudBeaver\cloudbeaver\webapp\node_modules\@lerna\run-topologically\run-topologically.js:34:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```
Please review the problem

**Comment by miltonchirinos44** [comment]
@devnaumov did you manage to replicate the error? to enable cloudbeaver development mode when you run the following command:

**TOOLS:**
- latest version of cloudbeaver
- openjdk-17
- maven-3.8.6
- node 14.16.x
- lerna
- yarn

**COMMAND:**
lerna run dev --stream --scope=@cloudbeaver/product-default -- -- --env server=http://localhost:8978

**Comment by miltonchirinos44** [comment]
For now I have no solution to this problem or how else can I access cloudbeaver's development mode

**Comment by miltonchirinos44** [comment]
Someone installed cloudbeaver, installing the latest version that is with java 17 and maven 3.8.6 and when he runs the command for development mode he gets errors and does not finish running cloudbeaver in development mode. Could someone verify this error, is easy to replicate

**Comment by miltonchirinos44** [comment]
I solved it thanks for the help
