### ISSUE TITLE
 ERROR connecting to ORACLE database

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1326]
Hello friends, I am trying to connect to an oracle 11g database through cloudbeaver, but when I configure the connection data and perform the connection tests, I get the following

error:
![image](https://user-images.githubusercontent.com/52106718/204316912-755108c9-625e-4a08-85cb-f227d850bf6b.png)

**TRANSLATED MESSAGE:**
```
Connection test failed
Error connecting to database:
Connection failed:
ORA-00604: Recursive SQL level 1 error occurred
ORA-12705: Cannot access NLS data files or invalid environment specified
```
![image](https://user-images.githubusercontent.com/52106718/204319032-b66a7cd2-a015-47c2-a3af-5910978ce5b7.png)

**ERROR DETAILS**

```
Error connecting to database:
Connection failed:
ORA-00604: Recursive SQL level 1 error occurred
ORA-12705: Cannot access NLS data files or invalid environment specified

java.sql.SQLException: ORA-00604: se ha producido un error a nivel 1 de SQL recursivo
ORA-12705: No se puede acceder a los archivos de datos NLS o se ha especificado un entorno no válido

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:441)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:436)
	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1061)
	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:550)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:499)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1279)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:663)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:172)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:90)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1025)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:604)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

```

Has anyone else got this error?

**Comment by kseniaguzeeva** [comment]
I cannot reproduce the issue, Have you tried to configure the connection in another application (e.g. DBeaver)? If the database is connected there, could you please give me more details about the connection configuration.

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva    I tell you that I run from eclipse compiling dbeaver and trying to connect to the oracle database and I'm getting the same error

![image](https://user-images.githubusercontent.com/52106718/205133380-a77b1386-2213-4b80-a292-c44cf761632b.png)

CONNECTION ERROR

ORA-00604: Recursive SQL level 1 error occurred
ORA-12705: Cannot access NLS data files or invalid environment specified

**Comment by kseniaguzeeva** [comment]
What auth method do you use for Oracle?

**Comment by miltonchirinos44** [comment]
TNS authentication method, I configure my .ora file to only enter username and password. Or what do you mean @kseniaguzeeva?

**Comment by miltonchirinos44** [comment]
@kseniaguzeeva   so far I have not received any solution on this error please verify the problem?

**Comment by kseniaguzeeva** [comment]
If you have the same problem in DBeaver, you should open ticket in the DBeaver board https://github.com/dbeaver/dbeaver/issues. I close the ticket as a third party issue.
