### ISSUE TITLE
can not start cloudbeaver in eclipse ;  java -version  :  17  maven : 3.8.6   And start  dbeaver successful, but con not start cloudbeaver 

### ISSUE THREAD

**Issue by Amor7527** [dbeaver/cloudbeaver#1335]
I found this issue: https://github.com/dbeaver/cloudbeaver/issues/1226  In order to solve my problem, but it didn't work. Is there any better suggestion? I have tried all the solutions, as shown in the figure Shown:

1. jdk version 17
2. maven 3.8.6
3. windows 10
4. eclipse
5 sl4j.jar not selected

![image](https://user-images.githubusercontent.com/91579939/205206698-0dd8c035-1dce-4022-a0d6-6ac507f554ca.png)

![image](https://user-images.githubusercontent.com/91579939/205206732-92a9ec85-8fa4-4da6-bef0-403d2f99d239.png)

![image](https://user-images.githubusercontent.com/91579939/205206851-9427ebba-bd20-4148-84b2-b28af0573f25.png)

![image](https://user-images.githubusercontent.com/91579939/205205748-bb72dc74-5655-4f9b-9b06-16a50fa87889.png)

![image](https://user-images.githubusercontent.com/91579939/205208025-2c8bf72a-7244-4e0b-adf9-19f394dad47a.png)

![image](https://user-images.githubusercontent.com/91579939/205205784-4481d598-0cb8-4c8b-8883-6bf7c2c5bc6e.png)

![image](https://user-images.githubusercontent.com/91579939/205205923-4d0e9ece-1b35-49fe-8da7-6bfe8d5eaa90.png)

![image](https://user-images.githubusercontent.com/91579939/205206496-339b53cc-c129-486b-91db-864168617a37.png)

![image](https://user-images.githubusercontent.com/91579939/205206262-e0f9a84e-3826-42e8-ba0e-bbce91495535.png)

![image](https://user-images.githubusercontent.com/91579939/205207860-63beeadc-09c5-4bed-ad8c-5adad5b5f1ac.png)

!SESSION 2022-12-02 11:00:26.578 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data E:\Project\dbeaver\test_2/../runtime-DBeaverWebServer.product -dev file:E:/Project/dbeaver/test_2/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.eclipse.osgi 4 0 2022-12-02 11:00:31.063
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in io.cloudbeaver.product.ce was unable to load class io.cloudbeaver.server.CBApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: io.cloudbeaver.server.CBApplication cannot be found by io.cloudbeaver.product.ce_22.3.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 16 more
An error has occurred. See the log file
E:\Project\dbeaver\test_2\.metadata\.plugins\org.eclipse.pde.core\CloudbeaverServer.product\1669950026924.log.

**Comment by Amor7527** [comment]
Well, no one answered my question? Is it because you don’t have a solution? I read most of the issues, a lot of startup-related problems, but the final result is nothing. The relevant documents are all from dbeaver. There is basically no relevant development documentation for cloudbeaver, a little disappointing...

**Comment by miltonchirinos44** [comment]
Hello friend, how far in the guide did you get?
Did you manage to start dbeaver?
Did you manage to start cloudbeaver?
can you send screenshots?

**Comment by Amor7527** [comment]
![image](https://user-images.githubusercontent.com/91579939/206067758-7260fd7f-21f8-4e20-b75e-f60fbbe54b35.png)

![image](https://user-images.githubusercontent.com/91579939/206067836-58e12c3c-74ff-4ebe-afb2-ec20a3a5bb1d.png)


ok, let me answer your questions, the official operation guide is too brief, it almost took me a lot of time to find cloudbeaver related documents, but there are almost few solutions to the problem, but i still found a bootable version

1. dbeav has been started normally, the screenshot has been reflected in the above issue,
2. Cloudbeaver cannot be started, because of various errors, the screenshot is still in the upper part of the issue,
3. Now I have started dbeaver and cloudbeaver 21.3.3 locally,

Today I will try to start the latest version of dbeaver and cloudbeaver

**Comment by Amor7527** [comment]
2022-12-07 09:40:13.336 - Using configuration [conf/cloudbeaver.conf]
2022-12-07 09:40:13.467 - Load product configuration from 'E:\Project\dbeaver\test_6_21.3.3\cloudbeaver\deploy\cloudbeaver\conf\product.conf'
2022-12-07 09:40:13.490 - CloudBeaver CE Server 21.3.3.qualifier is starting
2022-12-07 09:40:13.491 - 	OS: Windows 10 10.0 (amd64)
2022-12-07 09:40:13.493 - 	Java version: 17.0.4.1 by Eclipse Adoptium (64bit)
2022-12-07 09:40:13.497 - 	Install path: 'F:\eclipse\eclipse'
2022-12-07 09:40:13.498 - 	Global workspace: 'file:/E:/Project/dbeaver/runtime-DBeaverWebServer.product/'
2022-12-07 09:40:13.498 - 	Memory available 271Mb/512Mb
2022-12-07 09:40:13.529 - Initializing product: CloudBeaver CE Server 21.3.3
2022-12-07 09:40:13.530 - Host plugin: io.cloudbeaver.product.ce 21.3.3.qualifier
2022-12-07 09:40:13.530 - Initialize web platform...
!SESSION 2022-12-07 09:40:07.906 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data E:\Project\dbeaver\test_6_21.3.3/../runtime-DBeaverWebServer.product -dev file:E:/Project/dbeaver/test_6_21.3.3/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.jkiss.dbeaver.model 1 0 2022-12-07 09:40:13.542
!MESSAGE Initialize web platform...
2022-12-07 09:40:13.848 - BounceCastle bundle found. Use JCE provider BC
2022-12-07 09:40:14.100 - Initialize base platform...
2022-12-07 09:40:14.340 - Total database drivers: 90 (90)
2022-12-07 09:40:14.352 - Available drivers: ClickHouse,DB2 LUW,DB2 iSeries/AS 400,Firebird,H2 Embedded,Derby Server,Trino,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite

!ENTRY org.jkiss.dbeaver.model 1 0 2022-12-07 09:40:14.353
!MESSAGE Available drivers: ClickHouse,DB2 LUW,DB2 iSeries/AS 400,Firebird,H2 Embedded,Derby Server,Trino,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
2022-12-07 09:40:14.364 - Web platform initialized (834ms)

!ENTRY org.jkiss.dbeaver.model 1 0 2022-12-07 09:40:14.366
!MESSAGE Web platform initialized (834ms)
2022-12-07 09:40:14.368 - 	Content root: E:\Project\dbeaver\test_6_21.3.3\cloudbeaver\deploy\cloudbeaver\web
2022-12-07 09:40:14.368 - 	Drivers storage: E:\Project\dbeaver\test_6_21.3.3\cloudbeaver\deploy\cloudbeaver\drivers
2022-12-07 09:40:14.368 - 	Base port: 8978
2022-12-07 09:40:14.370 - 	Base URI: /api/
2022-12-07 09:40:14.372 - 	Production mode
2022-12-07 09:40:14.372 - 	Server is in configuration mode!
2022-12-07 09:40:25.689 - 	Local host addresses:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-07 09:40:25.736 - 		127.0.0.1 (activate.navicat.com)
2022-12-07 09:40:25.737 - 		192.168.220.19 (PC-202004041438)
2022-12-07 09:40:25.945 - Initiate management database
2022-12-07 09:40:26.068 - 	Initiate connection pool with management database (H2 Embedded; jdbc:h2:E:\Project\dbeaver\runtime-DBeaverWebServer.product/.data/cb.h2.dat)
2022-12-07 09:40:27.201 - 	Connected to H2 1.4.199 (2019-03-13)
2022-12-07 09:40:27.614 - 	Management database connection established
2022-12-07 09:40:27.627 - No auto configuration was found. Server must be configured manually

!ENTRY org.jkiss.dbeaver.model 1 0 2022-12-07 09:40:27.628
!MESSAGE No auto configuration was found. Server must be configured manually
2022-12-07 09:40:27.628 - Starting Jetty server (8978) 
2022-12-07 09:40:28.393 - Schema extensions loaded: WebServiceBindingCore,WebServiceBindingNavigator,WebServiceBindingSQL,WebServiceBindingAdmin,WebServiceBindingAuth,WebServiceBindingDataTransfer,WebServiceBindingMetadata
2022-12-07 09:40:29.377 - Active servlets:
2022-12-07 09:40:29.378 - 	static: [/*]
2022-12-07 09:40:29.378 - 	status: [/status]
2022-12-07 09:40:29.378 - 	images: [/api/images/*]
2022-12-07 09:40:29.378 - 	graphql: [/api/gql/*]
2022-12-07 09:40:29.378 - 	sqlResultValueViewer: [/api/sql-result-value/*]
2022-12-07 09:40:29.378 - 	adminLogs: [/api/logs/*]
2022-12-07 09:40:29.378 - 	dataTransfer: [/api/data/*]

**Comment by Amor7527** [comment]
When I use the latest version of dbeaver and cloudbeaver, I still can't start, even though I can use the bat script to start,

At this time the latest version of dbeaver can be started

![image](https://user-images.githubusercontent.com/91579939/206074050-c35fbbc7-e868-4de0-9a41-03b7d483f54a.png)

![image](https://user-images.githubusercontent.com/91579939/206074547-337a700a-7b70-4789-a43f-d67625ceb513.png)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
!SESSION 2022-12-07 10:39:32.263 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data E:\Project\dbeaver\test_4_1/../runtime-DBeaverWebServer.product -dev file:E:/Project/dbeaver/test_4_1/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.eclipse.core.jobs 2 2 2022-12-07 10:39:55.109
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob



![image](https://user-images.githubusercontent.com/91579939/206074219-eda73191-2d5d-4426-af0b-1aec3db72790.png)

**Comment by Amor7527** [comment]
![image](https://user-images.githubusercontent.com/91579939/206077699-999c8385-0558-4a94-91bc-a7cc93db092c.png)

![image](https://user-images.githubusercontent.com/91579939/206077767-582feb24-ed0c-4d67-b93a-5867a8851db7.png)

This is how I enter the page after the startup is complete, is this correct? Does the page need to be started separately?

**Comment by yagudin10** [comment]
Hi, @Amor7527!
Did I understand correctly that you can't open CB page after running server with run-server.bat file?

**Comment by Amor7527** [comment]
Yes, but the main problem is that cloudbeaver cannot be started in deug in eclipse,


![image](https://user-images.githubusercontent.com/91579939/206207261-15fd49ed-4700-41ac-9f7f-091c5e159e26.png)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
!SESSION 2022-12-07 22:35:39.341 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data E:\Project\dbeaver\test_8_22.3/../runtime-DBeaverWebServer.product -dev file:E:/Project/dbeaver/test_8_22.3/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.eclipse.core.jobs 2 2 2022-12-07 22:35:45.678
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob


>

**Comment by miltonchirinos44** [comment]
@Amor7527    From what I see, the error that appears in the terminal is telling you that there is already another instance of cloudbeaver running and if you don't stop that instance that is running, you won't be able to run cloudbeaver from eclipse, you have to remove or stop the instance that is running. was executed first, surely the instance was created when you executed the ./bulild.sh

```
cd cloudbeaver/deploy
./build.sh 
```

You need to check that out first

**Comment by Amor7527** [comment]
> @Amor7527 From what I see, the error that appears in the terminal is telling you that there is already another instance of cloudbeaver running and if you don't stop that instance that is running, you won't be able to run cloudbeaver from eclipse, you have to remove or stop the instance that is running. was executed first, surely the instance was created when you executed the ./bulild.sh
> 
> ```
> cd cloudbeaver/deploy
> ./build.sh 
> ```
> 
> You need to check that out first

![image](https://user-images.githubusercontent.com/91579939/206347938-d99812f2-5409-46fe-bdf3-998920075c47.png)

![image](https://user-images.githubusercontent.com/91579939/206348047-beaed51d-ab03-49ec-a5ac-a20b6bb81746.png)

![image](https://user-images.githubusercontent.com/91579939/206348164-ed6e227a-b180-4b6c-b3ad-ad67eb003491.png)

![image](https://user-images.githubusercontent.com/91579939/206349154-277ac90e-6b22-427b-ba35-6c74c6524607.png)

Yes, I did this, all model builds are successful, except for the webapp folder, but I think it should not affect the java code, as shown in the figure, the backend build is successful, but I will be stuck here when building the webapp. Currently I hope it can be started correctly in eclipse.
What I don't understand is that there is no error log generated when starting up, only a stop message.
I have used jdk 17, maven 3.8.6 and npm related, working directory I have selected the path of the build: cloudbeaver\deploy\cloudbeaver,
plug-ins I did not choose sl4j, but I chose the necessary plug-ins,

**Comment by Amor7527** [comment]
![image](https://user-images.githubusercontent.com/91579939/206350107-08a2e671-88b5-478e-b3eb-90e92f7ce494.png)

**Comment by miltonchirinos44** [comment]
@Amor7527  , in the following path you have to delete the **runtime-DBeaverWebServer.product** folder 
**Path:**  C:\Users\usuario\

**Comment by Amor7527** [comment]
> 

![image](https://user-images.githubusercontent.com/91579939/206607197-780a400c-f62c-4faf-bb87-ddc9efc57a34.png)
![image](https://user-images.githubusercontent.com/91579939/206608403-92ebd965-d500-4fa7-8f59-b293b73fbb9d.png)

![image](https://user-images.githubusercontent.com/91579939/206607496-253cd2f1-a16e-4cf7-8696-044917f1571b.png)


Thank you for your solution. I changed the working directory as shown in the figure, and cloudbeaver can be started, but I see such a page in the browser after starting, I know it is caused by the failure of the webapp build, I will try to rebuild it webapp directory

But do you know why I don't have logs printed? I hope to see logs of different levels in the console. I didn't choose sl4j.jar. When I start up, I can only see the following logs

![image](https://user-images.githubusercontent.com/91579939/206608131-899370eb-5ea0-4fbc-9d99-ed7147f69136.png)



SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by miltonchirinos44** [comment]
@Amor7527 , 
the folder that you must delete is in the following path I think you did not understand me check the image
![image](https://user-images.githubusercontent.com/52106718/207057879-b29217a5-c9bc-4878-874a-dd4c488f8448.png)

`runtime-DBeaverWebServer`, this folder is created every time you run the application

**Comment by miltonchirinos44** [comment]
@Amor7527 ,  did the suggestion I made help you?

**Comment by Amor7527** [comment]
OK I deleted or changed this directory and it did start the project, thanks

**Comment by miltonchirinos44** [comment]
@Amor7527 , any other problem you have here is the community to help you
