### ISSUE TITLE
User authentication failed: Error reading user permissions

### ISSUE THREAD

**Issue by chnacib** [dbeaver/cloudbeaver#1389]
Its happening after update from **cloudbeaver-aws:22.0.0** to **cloudbeaver-aws:22.3.0**

Logs:

```
java.lang.NullPointerException: Cannot invoke "org.h2.value.Value.compareTo(org.h2.value.Value, org.h2.engine.Mode, org.h2.value.CompareMode)" because "<parameter1>" is null

              at org.h2.mvstore.db.ValueDataType.compareValues(ValueDataType.java:177)

              at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:150)

              at org.h2.mvstore.MVMap.compare(MVMap.java:526)

              at org.h2.mvstore.Page.binarySearch(Page.java:481)

              at org.h2.mvstore.Cursor.traverseDown(Cursor.java:169)

              at org.h2.mvstore.Cursor.<init>(Cursor.java:31)

              at org.h2.mvstore.tx.TransactionMap$TMIterator.<init>(TransactionMap.java:701)

              at org.h2.mvstore.tx.TransactionMap$KeyIterator.<init>(TransactionMap.java:652)sudo docker run --name cloudbeaver-aws -d --restart unless-stopped -p 8978:8978 -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver-aws:22.0.0

              at org.h2.mvstore.tx.TransactionMap.keyIterator(TransactionMap.java:575)

              at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:273)

              at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:266)

              at org.h2.index.BaseIndex.find(BaseIndex.java:132)

              at org.h2.index.IndexCursor.find(IndexCursor.java:163)

              at org.h2.table.TableFilter.next(TableFilter.java:475)

              at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882)

              at org.h2.result.LazyResult.hasNext(LazyResult.java:101)

              at org.h2.result.LazyResult.next(LazyResult.java:60)

              at org.h2.command.dml.Select.queryFlat(Select.java:742)

              at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)

              at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)

              at org.h2.command.dml.Query.query(Query.java:435)

              at org.h2.command.dml.Query.query(Query.java:397)

              at org.h2.command.CommandContainer.query(CommandContainer.java:145)

              at org.h2.command.Command.executeQuery(Command.java:202)

              at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)

              at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)

              at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)

              at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getUserPermissions(CBEmbeddedSecurityController.java:953)

              at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getUserPermissions(CBEmbeddedSecurityController.java:975)

              at io.cloudbeaver.service.security.CBEmbeddedSecurityController.finishAuthentication(CBEmbeddedSecurityController.java:1615)

              at io.cloudbeaver.service.security.CBEmbeddedSecurityController.authenticate(CBEmbeddedSecurityController.java:1103)

              at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:80)

              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

              at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

              at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```
Deploy command:

```
sudo docker run --name cloudbeaver-aws -d --restart unless-stopped -p 8978:8978 -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver-aws:22.3.0
```

**Comment by chnacib** [comment]
Now, after downgrade from **cloudbeaver-aws:22.3.0** to **cloudbeaver-aws:22.0.0**, error response changes to: **"Error reading user details: Error while searching credentials"**

Error logs:
```
2022-12-29 14:50:54.486 - GraphQL call failed at '/user'
io.cloudbeaver.DBWebException: Error reading user details:
Error while searching credentials
        at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.activeUser(WebServiceAuthImpl.java:291)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.cloudbeaver.service.WebServiceBindingBase$ServiceInvocationHandler.invoke(WebServiceBindingBase.java:154)
        at com.sun.proxy.$Proxy8.activeUser(Unknown Source)
        at io.cloudbeaver.service.auth.WebServiceBindingAuth.lambda$3(WebServiceBindingAuth.java:52)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:197)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72)
        at graphql.execution.Execution.executeOperation(Execution.java:160)
        at graphql.execution.Execution.execute(Execution.java:101)
        at graphql.GraphQL.execute(GraphQL.java:591)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521)
        at graphql.GraphQL.executeAsync(GraphQL.java:495)
        at graphql.GraphQL.execute(GraphQL.java:426)
        at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeQuery(GraphQLEndpoint.java:257)
        at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeSingleQuery(GraphQLEndpoint.java:201)
        at io.cloudbeaver.server.graphql.GraphQLEndpoint.doPost(GraphQLEndpoint.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1372)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1294)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:562)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Error while searching credentials
        at io.cloudbeaver.server.CBSecurityController.getUserById(CBSecurityController.java:196)
        at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.activeUser(WebServiceAuthImpl.java:283)
        ... 50 more
Caused by: org.h2.jdbc.JdbcSQLTimeoutException: Timeout trying to lock table {0}; SQL statement:
SELECT META_ID,META_VALUE FROM CB_USER_META WHERE USER_ID=? [50200-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.command.Command.filterConcurrentUpdate(Command.java:333)
        at org.h2.command.Command.executeQuery(Command.java:209)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
        at io.cloudbeaver.server.CBSecurityController.getUserById(CBSecurityController.java:185)
        ... 51 more
Caused by: org.h2.message.DbException: Row "5" not found in primary index "PUBLIC.CB_USER_META_DATA" [90143-199]
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.mvstore.db.MVPrimaryIndex.getRow(MVPrimaryIndex.java:274)
        at org.h2.mvstore.db.MVTable.getRow(MVTable.java:338)
        at org.h2.mvstore.db.MVSecondaryIndex$MVStoreCursor.get(MVSecondaryIndex.java:455)
        at org.h2.index.IndexCursor.get(IndexCursor.java:274)
        at org.h2.table.TableFilter.getValue(TableFilter.java:1092)
        at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:215)
        at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1890)
        at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
        at org.h2.result.LazyResult.next(LazyResult.java:60)
        at org.h2.command.dml.Select.queryFlat(Select.java:742)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)
        at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)
        at org.h2.command.dml.Query.query(Query.java:435)
        at org.h2.command.dml.Query.query(Query.java:397)
        at org.h2.command.CommandContainer.query(CommandContainer.java:145)
        at org.h2.command.Command.executeQuery(Command.java:202)
        ... 55 more
Caused by: org.h2.jdbc.JdbcSQLTransientException: Row "5" not found in primary index "PUBLIC.CB_USER_META_DATA" [90143-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:621)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        ... 72 more
```

**Comment by kseniaguzeeva** [comment]
Thank you for the report, I'll give you a detailed response as soon as I reproduce the issue.

**Comment by kseniaguzeeva** [comment]
I partly reproduced the issue: I can't login after upgrading from 22.0.0 to 22.3.0, but I have another the error content:
```
User authentication failed:
Error reading user permissions
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CB_USER_TEAM" not found; SQL statement:
SELECT DISTINCT AP.PERMISSION_ID FROM CB_AUTH_PERMISSIONS AP,CB_USER_TEAM UR
WHERE UR.TEAM_ID=AP.SUBJECT_ID AND UR.USER_ID=? [42102-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7146)
	at org.h2.command.Parser.readTableFilter(Parser.java:1895)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2641)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2788)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2636)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2469)
	at org.h2.command.Parser.parseSelect(Parser.java:2440)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:303)
	at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:303)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getUserPermissions(CBEmbeddedSecurityController.java:949)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getUserPermissions(CBEmbeddedSecurityController.java:975)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.finishAuthentication(CBEmbeddedSecurityController.java:1615)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.authenticate(CBEmbeddedSecurityController.java:1103)
	at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**Comment by alexander-skoblikov** [comment]
@chnacib Hi, can you execute this query in cloudbeaver database `SHOW TABLES` and send results? 
h2 file located in `/var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db`
default db credentials (if you did not specify your own):
user: `cb-data` (if you did not specify your own)
password: stored in `/var/cloudbeaver/workspace/.data/.database-credentials.dat`

**Comment by chnacib** [comment]
@alexander-skoblikov I downloaded the h2 file and tried to login in my local machine using dbeaver with h2 embedded connection. But i get "Wrong username or password" authenticating with db default credentials. 
I never configured a user or password because its authenticated by AWS IAM since first login.
Did i do something wrong?

**Comment by alexander-skoblikov** [comment]
@chnacib did you use credentials from the post above?
```
default db credentials (if you did not specify your own):
user: cb-data
password: stored in /var/cloudbeaver/workspace/.data/.database-credentials.dat
```

**Comment by chnacib** [comment]
@alexander-skoblikov yes. i did

**Comment by alexander-skoblikov** [comment]
@chnacib Please check that you have not inserted any extra characters when copying the password value from /var/cloudbeaver/workspace/.data/.database-credentials.dat

**Comment by chnacib** [comment]
@alexander-skoblikov i did, but still cant login

**Comment by alexander-skoblikov** [comment]
[h2-query-executor-1.0.0.jar.zip](https://github.com/dbeaver/cloudbeaver/files/10395023/h2-query-executor-1.0.0.jar.zip)
@chnacib can you unzip this file, copy h2-query-executor-1.0.0.jar to a aws machine and execute  this command
`java -jar h2-query-executor-1.0.0.jar --db-path=/var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db --db-user=cb-data
--db-password-path=/var/cloudbeaver/workspace/.data/.database-credentials.dat --db-custom-query="show tables"` ?

the source code of the script is [here](https://github.com/dbeaver/cloudbeaver/pull/1411) and will be merged soon

**Comment by chnacib** [comment]
@alexander-skoblikov it worked
```
root@ip-172-31-42-62:/home/ubuntu# java -jar h2-query-executor-1.0.0.jar --db-path=/var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db --db-user=cb-data --db-password-path=/var/cloudbeaver/workspace/.data/.database-credentials.dat --db-custom-query="show tables"
Execute query: show tables
CB_AUTH_ATTEMPT PUBLIC 
CB_AUTH_ATTEMPT_INFO PUBLIC 
CB_AUTH_CONFIGURATION PUBLIC 
CB_AUTH_PERMISSIONS PUBLIC 
CB_AUTH_PROVIDER PUBLIC 
CB_AUTH_SUBJECT PUBLIC 
CB_AUTH_TOKEN PUBLIC 
CB_INSTANCE PUBLIC 
CB_INSTANCE_DETAILS PUBLIC 
CB_INSTANCE_EVENT PUBLIC 
CB_OBJECT_PERMISSIONS PUBLIC 
CB_ROLE PUBLIC 
CB_SCHEMA_INFO PUBLIC 
CB_SESSION PUBLIC 
CB_SESSION_LOG PUBLIC 
CB_SESSION_STATE PUBLIC 
CB_TEAM PUBLIC 
CB_USER PUBLIC 
CB_USER_CREDENTIALS PUBLIC 
CB_USER_META PUBLIC 
CB_USER_PARAMETERS PUBLIC 
CB_USER_ROLE PUBLIC 
CB_USER_SECRETS PUBLIC 
CB_USER_STATE PUBLIC 
CB_USER_TEAM PUBLIC 
CB_WORKSPACE PUBLIC 

```

**Comment by alexander-skoblikov** [comment]
@chnacib please try this steps:

1.  stop cloudbeaver docker container
2. create cb database backup ( `sudo cp /var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db /var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db_backup` ) 
3. execute `sudo java -jar h2-query-executor-1.0.0.jar --db-path=/var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db --db-user=cb-data --db-password-path=/var/cloudbeaver/workspace/.data/.database-credentials.dat --db-custom-query="drop table CB_USER_TEAM"`
4.  execute `sudo java -jar h2-query-executor-1.0.0.jar --db-path=/var/cloudbeaver/workspace/.data/cb.h2.dat.mv.db --db-user=cb-data --db-password-path=/var/cloudbeaver/workspace/.data/.database-credentials.dat --db-execute-11-migration-fix`
5. start cloudbeaver 22.3.0 and check that it works

**Comment by chnacib** [comment]
@alexander-skoblikov like a charm
Thank you so much <3
