### ISSUE TITLE
Cloudbeaver wont build

### ISSUE THREAD

**Issue by kempshawn** [dbeaver/cloudbeaver#1393]
I am trying to install CB community on RHEL 8. I have the following versions of prerequisites:
Java version: 17.0.5
Apache Maven 3.8.5 (Red Hat 3.8.5-3)
Nodejs v16.17.1
yarn -version 1.22.19

java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

which java /usr/bin/java

When I go to build the project I get the following error:

Build CloudBeaver server
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
        at com.google.inject.internal.Errors.<clinit>(Errors.java:709)
        at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:62)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
        at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:651)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 18 more

**Comment by Amor7527** [comment]
Java required version: jdk17

**Comment by kseniaguzeeva** [comment]
@kempshawn Could you try the Java version according to the advice above?

**Comment by TatyanaSsau** [comment]
I've noticed there is no updates for a long time. 
@kempshawn Please, feel free to reopen the ticket if it's still actual.
