### ISSUE TITLE
Server postgreSQL initializing database error

### ISSUE THREAD

**Issue by cb-arkea** [dbeaver/cloudbeaver#1567]
**Describe the bug**
Server postgreSQL initializing database error

**cloudbeaver.conf**
```
  database: {
	        driver: "postgres-jdbc",
            url: "jdbc:postgresql://host:5432/dbeavercloud?targetServerType=primary",
            user: "dbeavercloud",
            password: "aaaa",
            initialDataConfiguration: "conf/initial-data.conf",
            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 50,
                validationQuery: "SELECT 1"
            }
        }
```

**initial-data.conf**
```
{
    adminName: "toto",
    adminPassword: "toto",
    roles: [
        {
            roleId: "admin",
            name: "Admin",
            description: "Administrative access. Has total and full authority.",
            permission: ["public", "admin"]
        },
        {
            roleId: "user",
            name: "User",
            description: "Standard user",
            permission: ["public"]
        }
    ]
}
```

**Logs**
```
12:43:14.091 [main] DEBUG i.c.service.security.db.CBDatabase -  Initiate connection pool with management database (PostgreSQL; jdbc:postgresql://host:5432/dbeavercloud?targetServerType=primary)
12:43:14.665 [main] DEBUG i.c.service.security.db.CBDatabase -  Connected to PostgreSQL 14.6
12:43:14.775 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Create new schema CB
12:43:15.369 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - CB migration has been rolled back
12:43:15.371 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:193)
        at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:484)
        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:480)
        at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:323)
        at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:186)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Error saving user teams in database
        at io.cloudbeaver.service.security.CBEmbeddedSecurityController.setUserTeams(CBEmbeddedSecurityController.java:188)
        at io.cloudbeaver.service.security.CBEmbeddedSecurityController.createUser(CBEmbeddedSecurityController.java:148)
        at io.cloudbeaver.service.security.db.CBDatabase.createAdminUser(CBDatabase.java:258)
        at io.cloudbeaver.service.security.db.CBDatabase$CBSchemaVersionManager.fillInitialSchemaData(CBDatabase.java:384)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.createNewSchema(SQLSchemaManager.java:159)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:91)
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189)
        ... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "cb_user_team" violates foreign key constraint "cb_user_team_team_id_fkey"
  Detail: Key (team_id)=(user) is not present in table "cb_team".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
        at io.cloudbeaver.service.security.CBEmbeddedSecurityController.setUserTeams(CBEmbeddedSecurityController.java:181)
        ... 24 common frames omitted
12:43:15.377 [Framework stop - Equinox Container: 8534262e-049f-4cf8-870a-787cc4e40f09] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
12:43:15.480 [Framework stop - Equinox Container: 8534262e-049f-4cf8-870a-787cc4e40f09] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 103ms
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob

```

**Comment by cb-arkea** [comment]
From scratch, first launch :  

```
4:54:24.867 [main] DEBUG i.c.service.security.db.CBDatabase -  Connected to PostgreSQL 14.6
14:54:24.951 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Update schema CB version from 1 to 2
14:54:25.172 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [DROP TABLE IF EXISTS CB_SERVER]
14:54:25.176 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [CREATE TABLE CB_SCHEMA_INFO (VERSION INTEGER NOT NULL,
UPDATE_TIME timestamp NOT NULL)]
14:54:25.184 [main] ERROR o.j.d.m.sql.schema.SQLSchemaManager - Error during sql migration
org.postgresql.util.PSQLException: ERROR: relation "cb_schema_info" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:196)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:141)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:112)
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189)
        at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:484)
        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:480)
        at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:323)
        at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:186)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
14:54:25.185 [main] INFO  o.j.d.m.sql.schema.SQLSchemaManager - Trying to apply the migration again
14:54:25.236 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - Error updating CB schema version from 1 to 2
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:202)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:141)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:112)
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189)
        at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:484)
        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:480)
        at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:323)
        at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:186)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "cb_schema_info" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:196)
        ... 21 common frames omitted
14:54:25.238 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - CB migration has been rolled back
14:54:25.239 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:193)
        at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:484)
        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:480)
        at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:323)
        at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:186)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.jkiss.dbeaver.DBException: Error updating CB schema version
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:123)
        at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:189)
        ... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:202)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:141)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:112)
        ... 19 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "cb_schema_info" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:196)
        ... 21 common frames omitted
14:54:25.250 [Framework stop - Equinox Container: b33dc0a0-2ee5-403c-9d18-e754b5da355a] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
14:54:25.367 [Framework stop - Equinox Container: b33dc0a0-2ee5-403c-9d18-e754b5da355a] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 117ms
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
```

**Comment by alexander-skoblikov** [comment]
@cb-arkea Hi! 
Can you clarify - the first time you had an error during the very first launch of the cloud beaver, I mean that in postgres the database was empty?
Have you tried clearing database after that and restart CloudBeaver?
What version are you using?
Do you build CloudBeaver from the source?

**Comment by cb-arkea** [comment]
HI,
yes those are the logs with an empty/cleared PostgreSQL 14.
Customized FROM dbeaver/cloudbeaver:latest with my dockerfile that makes a copy of cloudbeaver.conf, initial-data.conf, data-sources.json

**Comment by alexander-skoblikov** [comment]
@cb-arkea you use legacy initial-data file format, please change `roles` for `teams` same as [here](https://github.com/dbeaver/cloudbeaver/blob/devel/config/core/initial-data.conf)

**Comment by cb-arkea** [comment]
resolved

**Comment by fagner-moura** [comment]
I followed the same steps, but the error mentioned above persisted.

The same error occurred immediately on the initial run, when I tried to run with a clean schema.

Image version: **25.1.0**
Postgres 14.17 (RDS)

CLOUDBEAVER_DB_BACKUP_ENABLED = false (to fix problema with **pg_dump**)
CLOUDBEAVER_DB_SCHEMA = **cb**


Full trace:

```
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:186)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:140)
	at org.jkiss.dbeaver.model.sql.db.InternalDB.updateSchema(InternalDB.java:140)
	at io.cloudbeaver.service.security.db.CBDatabase.initializeSchema(CBDatabase.java:222)
	at org.jkiss.dbeaver.model.sql.db.InternalDB.initSchema(InternalDB.java:100)
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:162)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createAndInitDatabaseInstance(EmbeddedSecurityControllerFactory.java:84)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:52)
	at io.cloudbeaver.server.CBApplicationCE.createGlobalSecurityController(CBApplicationCE.java:72)
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:468)
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:310)
	at io.cloudbeaver.model.app.BaseServletApplication.start(BaseServletApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:820)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:643)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1601)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1574)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "cb_schema_info" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.jkiss.dbeaver.model.sql.db.InternalProxyConnection$StatementProxy.execute(InternalProxyConnection.java:348)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:247)
	... 23 common frames omitted
10-06-2025 11:51:28.803 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - CB_CE migration has been rolled back
10-06-2025 11:51:28.807 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:164)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createAndInitDatabaseInstance(EmbeddedSecurityControllerFactory.java:84)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:52)
	at io.cloudbeaver.server.CBApplicationCE.createGlobalSecurityController(CBApplicationCE.java:72)
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:468)
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:310)
	at io.cloudbeaver.model.app.BaseServletApplication.start(BaseServletApplication.java:210)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:820)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:643)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1601)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1574)
Caused by: org.jkiss.dbeaver.DBException: Error updating CB_CE schema version
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:153)
	at org.jkiss.dbeaver.model.sql.db.InternalDB.updateSchema(InternalDB.java:140)
	at io.cloudbeaver.service.security.db.CBDatabase.initializeSchema(CBDatabase.java:222)
	at org.jkiss.dbeaver.model.sql.db.InternalDB.initSchema(InternalDB.java:100)
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:162)
	... 17 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.jkiss.dbeaver.model.sql.db.InternalProxyConnection$StatementProxy.execute(InternalProxyConnection.java:348)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:253)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:186)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:140)
	... 21 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "cb_schema_info" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.jkiss.dbeaver.model.sql.db.InternalProxyConnection$StatementProxy.execute(InternalProxyConnection.java:348)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:247)
	... 23 common frames omitted
10-06-2025 11:51:28.817 [Framework stop - Equinox Container: 3016b53a-a6e2-46a0-8045-956f4ddc5306] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
10-06-2025 11:51:28.859 [Framework stop - Equinox Container: 3016b53a-a6e2-46a0-8045-956f4ddc5306] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 42ms

```
