### ISSUE TITLE
Error connecting to database: null, message from server: "Host '172.17.0.1' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"

### ISSUE THREAD

**Issue by Macolm6** [dbeaver/cloudbeaver#1615]
**Describe the bug**
MySQL：Error connecting to database: null, message from server: "Host '172.17.0.1' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"

**To Reproduce**
1. Go to 'SQL Edit'
2. Click on 'connect'
3. See error
Error connecting to database:
null,  message from server: "Host '172.17.0.1' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
java.sql.SQLException: null,  message from server: "Host '172.17.0.1' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at io.cloudbeaver.service.core.impl.WebServiceCore.initConnection(WebServiceCore.java:325)
	at jdk.internal.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
4、other client can connected
![image](https://user-images.githubusercontent.com/56667336/232917858-a1031755-51eb-4c45-806a-517f901c9d0f.png)
 

**Screenshots**
![image](https://user-images.githubusercontent.com/56667336/232917262-d398e251-523a-42f0-a21e-7305b60df87f.png)

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by Wroud** [comment]
this error is specific to MySQL server and not related to the CloudBeaver.
Possible solution described here: https://informatics-support.perkinelmer.com/hc/en-us/articles/4408236406420-Creating-a-MySQL-data-source-in-Information-designer-fails-with-the-Host-is-blocked-because-of-many-connection-errors-Unblock-with-mysqladmin-flush-hosts-error-

You can find more information about this error in the internet `"Host  is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"`

Probably you have configured connection wrong and tried to open it several times.

**Comment by TatyanaSsau** [comment]
I've noticed there are no updates for a long time. 
@Macolm6 please feel free to contact me to reopen the ticket if it's still actual.
