### ISSUE TITLE
bug upgradgin to v23

### ISSUE THREAD

**Issue by pmpetit** [dbeaver/cloudbeaver#1641]
**Describe the bug**
i have changed version from v22.0.2 to v23.0.3

**To Reproduce**
from version v22.0.2, use this configuration file
```json

{
        server: {
            serverPort: 8978,

            workspaceLocation: "workspace",
            contentRoot: "web",
            driversLocation: "drivers",

            rootURI: "/",
            serviceURI: "/api/",

            productConfiguration: "conf/product.conf",

            expireSessionAfterPeriod: 1200000,

            develMode: false,
            database: {
                driver="h2_embedded",
                url: "jdbc:h2:${workspace}/.data/cb.h2.dat",

                createDatabase: true,

                initialDataConfiguration: "conf/initial-data.conf",

                pool: {
                    minIdleConnections: 1,
                    maxIdleConnections: 5,
                    maxConnections: 10,
                    validationQuery: "SELECT 1"
                }
            }

        },
        app: {
            anonymousAccessEnabled: true,
            anonymousUserRole: "user",
            supportsCustomConnections: true,
            authenticationEnabled: false,

            forwardProxy: true,

            publicCredentialsSaveEnabled: false,
            adminCredentialsSaveEnabled: false,

            resourceManagerEnabled: true,

            resourceQuotas: {
                dataExportFileSizeLimit: 10000000,
                resourceManagerFileSizeLimit: 500000,
                sqlMaxRunningQueries: 100,
                sqlResultSetRowsLimit: 100000,
                sqlResultSetMemoryLimit: 2000000,
                sqlTextPreviewMaxLength: 4096,
                sqlBinaryPreviewMaxLength: 261120
            },
            enabledAuthProviders: [
                "local"
            ],

            disabledDrivers: [
                "sqlite:sqlite_jdbc",
                "h2:h2_embedded",
                "clickhouse:yandex_clickhouse"
            ]

        }
    }
}
``` 

then change to version v23.0.3, using your default configuration file with this change
```json
          database: {
              driver="h2_embedded_v2",
              url: "jdbc:h2:${workspace}/.data/cb.h2v2.dat",
}
```

**Screenshots**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4059185/236160073-0c93fadb-7fb1-451a-8800-44223da291c4.png">

**Desktop (please complete the following information):**
 - OS: docker

**Additional context**
Add any other context about the problem here, e.g. error log.

**Comment by pmpetit** [comment]
for your information,
i created a helm chart to install cb.
no pb with v22.0.2
switching to v23.0.3 without changing anything in cloudbeaver.conf file gives

<img width="1758" alt="image" src="https://user-images.githubusercontent.com/4059185/236172286-da95daa1-5c9b-46af-a384-54669ab56de3.png">

**Comment by pmpetit** [comment]
changing cloudbeaver.conf to 

          database: {
              driver="h2_embedded_v2",
              url: "jdbc:h2:${workspace}/.data/cb.h2v2.dat",

gives

```log
cloudbeaver Starting Cloudbeaver Server                                                                                                                                                                                    │
│ cloudbeaver WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign                                                                                                                                  │
│ cloudbeaver 09:57:02.617 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /opt/cloudbeaver/conf/cloudbeaver.conf                                                                                 │
│ cloudbeaver 09:57:02.622 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [conf/cloudbeaver.conf]                                                                                                    │
│ cloudbeaver 09:57:02.623 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]                                                                                    │
│ cloudbeaver 09:57:02.734 [main] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from '/opt/cloudbeaver/conf/product.conf'                                                                           │
│ cloudbeaver 09:57:02.754 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 23.0.3.202304241015 is starting                                                                                          │
│ cloudbeaver 09:57:02.754 [main] DEBUG io.cloudbeaver.server.CBApplication -     OS: Linux 5.15.78-0-virt (amd64)                                                                                                           │
│ cloudbeaver 09:57:02.755 [main] DEBUG io.cloudbeaver.server.CBApplication -     Java version: 17.0.4.1 by Eclipse Adoptium (64bit)                                                                                         │
│ cloudbeaver 09:57:02.755 [main] DEBUG io.cloudbeaver.server.CBApplication -     Install path: '/opt/cloudbeaver/server'                                                                                                    │
│ cloudbeaver 09:57:02.755 [main] DEBUG io.cloudbeaver.server.CBApplication -     Global workspace: 'file:/opt/cloudbeaver/workspace/'                                                                                       │
│ cloudbeaver 09:57:02.755 [main] DEBUG io.cloudbeaver.server.CBApplication -     Memory available 27Mb/123Mb                                                                                                                │
│ cloudbeaver 09:57:02.791 [main] DEBUG io.cloudbeaver.server.CBPlatform - Initializing product: CloudBeaver CE Server 23.0.3                                                                                                │
│ cloudbeaver 09:57:02.791 [main] DEBUG io.cloudbeaver.server.CBPlatform - Host plugin: io.cloudbeaver.product.ce 23.0.3.202304241015                                                                                        │
│ cloudbeaver 09:57:02.792 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...                                                                                                                        │
│ cloudbeaver 09:57:03.194 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC                                                                                                 │
│ cloudbeaver 09:57:03.757 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...                                                                                                                        │
│ cloudbeaver 09:57:04.376 [main] DEBUG o.j.d.r.DataSourceProviderRegistry - Total database drivers: 101 (101)                                                                                                               │
│ cloudbeaver 09:57:04.390 [main] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: ClickHouse (Legacy),ClickHouse,Db2 for LUW,Db2 for IBM i,Firebird,Derby Server,Trino,H2 Embedded,H2 Embedded V.2,MS SQL Server │
│ cloudbeaver 09:57:04.404 [main] INFO  io.cloudbeaver.server.CBPlatform - Web platform initialized (1612ms)                                                                                                                 │
│ cloudbeaver 09:57:04.404 [main] DEBUG io.cloudbeaver.server.CBApplication -     Content root: /opt/cloudbeaver/web                                                                                                         │
│ cloudbeaver 09:57:04.404 [main] DEBUG io.cloudbeaver.server.CBApplication -     Drivers storage: /opt/cloudbeaver/drivers                                                                                                  │
│ cloudbeaver 09:57:04.404 [main] DEBUG io.cloudbeaver.server.CBApplication -     Listen port: 8978 on all interfaces                                                                                                        │
│ cloudbeaver 09:57:04.404 [main] DEBUG io.cloudbeaver.server.CBApplication -     Base URI: /api/                                                                                                                            │
│ cloudbeaver 09:57:04.405 [main] DEBUG io.cloudbeaver.server.CBApplication -     Production mode                                                                                                                            │
│ cloudbeaver 09:57:04.405 [main] DEBUG io.cloudbeaver.server.CBApplication -     Server is in configuration mode!                                                                                                           │
│ cloudbeaver 09:57:04.450 [main] DEBUG io.cloudbeaver.server.CBApplication -     Run in Docker container (host.docker.internal/192.168.5.2)?                                                                                │
│ cloudbeaver 09:57:04.451 [main] DEBUG io.cloudbeaver.server.CBApplication -     Local host addresses:                                                                                                                      │
│ cloudbeaver 09:57:04.537 [main] DEBUG io.cloudbeaver.server.CBApplication -         192.168.5.2 (192.168.5.2)                                                                                                              │
│ cloudbeaver 09:57:04.538 [main] DEBUG io.cloudbeaver.server.CBApplication -         10.42.0.122 (cb-cloudbeaver-6b6cf5d84c-hwmsx)                                                                                          │
│ cloudbeaver 09:57:04.538 [main] DEBUG io.cloudbeaver.server.CBApplication -         127.0.0.1 (localhost)                                                                                                                  │
│ cloudbeaver 09:57:04.837 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database                                                                                                                    │
│ cloudbeaver 09:57:04.904 [main] DEBUG i.c.service.security.db.CBDatabase -     Initiate connection pool with management database (H2 Embedded V.2; jdbc:h2:/opt/cloudbeaver/workspace/.data/cb.h2v2.dat)                   │
│ Stream closed EOF for decathlon-system/cb-cloudbeaver-6b6cf5d84c-hwmsx (init-data-sources)                                                                                                                                 │
│ cloudbeaver 09:57:05.855 [main] DEBUG i.c.service.security.db.CBDatabase -     Connected to H2 2.1.214 (2022-06-13)                                                                                                        │
│ cloudbeaver 09:57:05.936 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Update schema CB version from 1 to 2                                                                                                           │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)                                                                                                                                        │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)                                                                                                                                               │
└────────────
```

**Comment by pmpetit** [comment]
```log
 cloudbeaver 09:57:04.538 [main] DEBUG io.cloudbeaver.server.CBApplication -         127.0.0.1 (localhost)                                                                                                                  │
│ cloudbeaver 09:57:04.837 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database                                                                                                                    │
│ cloudbeaver 09:57:04.904 [main] DEBUG i.c.service.security.db.CBDatabase -     Initiate connection pool with management database (H2 Embedded V.2; jdbc:h2:/opt/cloudbeaver/workspace/.data/cb.h2v2.dat)                   │
│ Stream closed EOF for decathlon-system/cb-cloudbeaver-6b6cf5d84c-hwmsx (init-data-sources)                                                                                                                                 │
│ cloudbeaver 09:57:05.855 [main] DEBUG i.c.service.security.db.CBDatabase -     Connected to H2 2.1.214 (2022-06-13)                                                                                                        │
│ cloudbeaver 09:57:05.936 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Update schema CB version from 1 to 2                                                                                                           │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)                                                                                                                                        │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)                                                                                                                                               │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.run(Main.java:1467)                                                                                                                                                   │
│ cloudbeaver     at org.eclipse.equinox.launcher.Main.main(Main.java:1440)                                                                                                                                                  │
│ cloudbeaver 09:57:06.220 [main] INFO  o.j.d.m.sql.schema.SQLSchemaManager - Trying to apply the migration again                                                                                                            │
│ cloudbeaver 09:57:06.227 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - Error updating CB schema version from 1 to 2                                                                                                   │
│ cloudbeaver org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "UPDATE_TIME"; SQL statement:                                                                                                                   │
│ cloudbeaver ALTER TABLE CB_USER_CREDENTIALS ADD UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP [42121-214]                                                                                                       │
│ cloudbeaver     at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)                                                                                                                                    │
│ cloudbeaver     at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)                                                                                                                                    │
│ cloudbeaver     at org.h2.message.DbException.get(DbException.java:223)                                                                                                                                                    │
│ cloudbeaver     at org.h2.message.DbException.get(DbException.java:199)                                                                                                                                                    │
│ cloudbeaver     at org.h2.table.Table.setColumns(Table.java:487)                                                                                                                                                           │
│ cloudbeaver     at org.h2.table.TableBase.<init>(TableBase.java:73)                                                                                                                                                        │
│ cloudbeaver     at org.h2.mvstore.db.MVTable.<init>(MVTable.java:139)                                                                                                                                                      │
│ cloudbeaver     at org.h2.mvstore.db.Store.createTable(Store.java:219)                                                                                                                                                     │
│ cloudbeaver     at org.h2.schema.Schema.createTable(Schema.java:776)                                                                                                                                                       │
│ cloudbeaver     at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:454)                                                                                                            │
│ cloudbeaver     at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:339)                                                                                                                       │
│ cloudbeaver     at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:242)                                                                                                                         │
│ cloudbeaver     at org.h2.command.CommandContainer.update(CommandContainer.java:169)                                                                                                                                       │
│ cloudbeaver     at org.h2.command.Command.executeUpdate(Command.java:252)                                                                                                                                                  │
│ cloudbeaver     at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)                                                                                                                                       │
│ cloudbeaver     at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)                                                                                                                                               │
│ cloudbeaver     at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)                                                                                                                      │
│ cloudbeaver     at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)                                                                                                                      │
│ cloudbeaver     at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:202)                                                                                                            │
│ cloudbeaver     at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:141)                                                                                                     │
│ cloudbeaver     at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:112)                                                                                                             │
│ cloudbeaver     at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:199)                                                                                                                           │
│ cloudbeaver     at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)
```

**Comment by pmpetit** [comment]
fyi, 
in v22, i create a file initial-data-sources.conf from a config map. in this file there are all my connections.

doing the same in v23, failed. If i do not create this file (initial-data-sources.conf) then it is ok.

**Comment by pmpetit** [comment]
```logs
Starting Cloudbeaver Server                                                                                                                                                                                                │
│ WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign                                                                                                                                              │
│ 17:13:58.608 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /opt/cloudbeaver/conf/cloudbeaver.conf                                                                                             │
│ 17:13:58.610 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [conf/cloudbeaver.conf]                                                                                                                │
│ 17:13:58.610 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]                                                                                                │
│ 17:13:58.677 [main] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from '/opt/cloudbeaver/conf/product.conf'                                                                                       │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 23.0.3.202304241015 is starting                                                                                                      │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication -     OS: Linux 5.10.162+ (amd64)                                                                                                                            │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication -     Java version: 17.0.4.1 by Eclipse Adoptium (64bit)                                                                                                     │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication -     Install path: '/opt/cloudbeaver/server'                                                                                                                │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication -     Global workspace: 'file:/opt/cloudbeaver/workspace/'                                                                                                   │
│ 17:13:58.683 [main] DEBUG io.cloudbeaver.server.CBApplication -     Memory available 44Mb/123Mb                                                                                                                            │
│ 17:13:58.697 [main] DEBUG io.cloudbeaver.server.CBPlatform - Initializing product: CloudBeaver CE Server 23.0.3                                                                                                            │
│ 17:13:58.697 [main] DEBUG io.cloudbeaver.server.CBPlatform - Host plugin: io.cloudbeaver.product.ce 23.0.3.202304241015                                                                                                    │
│ 17:13:58.698 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...                                                                                                                                    │
│ 17:13:58.891 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC                                                                                                             │
│ 17:13:59.195 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...
```

**Comment by pmpetit** [comment]
```logs
 17:13:59.507 [main] DEBUG io.cloudbeaver.server.CBApplication -     Base URI: /api/                                                                                                                                        │
│ 17:13:59.507 [main] DEBUG io.cloudbeaver.server.CBApplication -     Production mode                                                                                                                                        │
│ 17:13:59.507 [main] DEBUG io.cloudbeaver.server.CBApplication -     Server is in configuration mode!                                                                                                                       │
│ 17:13:59.549 [main] DEBUG io.cloudbeaver.server.CBApplication -     Local host addresses:                                                                                                                                  │
│ 17:13:59.549 [main] DEBUG io.cloudbeaver.server.CBApplication -         10.0.131.2 (cloudbeaver-8669bd6578-gtvvg)                                                                                                          │
│ 17:13:59.550 [main] DEBUG io.cloudbeaver.server.CBApplication -         127.0.0.1 (localhost)                                                                                                                              │
│ 17:13:59.656 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database                                                                                                                                │
│ 17:13:59.680 [main] DEBUG i.c.service.security.db.CBDatabase -     Initiate connection pool with management database (H2 Embedded; jdbc:h2:/opt/cloudbeaver/workspace/.data/cb.h2v2.dat)                                   │
│ 17:14:00.063 [main] DEBUG i.c.service.security.db.CBDatabase -     Connected to H2 1.4.199 (2019-03-13)                                                                                                                    │
│ 17:14:00.100 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Create new schema CB                                                                                                                                       │
│ 17:14:00.403 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - CB migration has been rolled back                                                                                                                          │
│ 17:14:00.405 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database                                                                                                                                │
│ org.jkiss.dbeaver.DBException: Error updating management database schema                                                                                                                                                   │
│     at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:203)                                                                                                                                       │
│     at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:64)                                                                                  │
│     at io.cloudbeaver.server.CBApplicationCE.createGlobalSecurityController(CBApplicationC
```

**Comment by TatyanaSsau** [comment]
@pmpetit thank you for your report!
We added it to the backlog to provide solution with this case. Going to fix it after 23.1.0

**Comment by alexander-skoblikov** [comment]
@pmpetit Hi! 
Can you describe more details about problem:

- Did you mount cloudbeaver/conf folder? 
- If yes, do you also update initial-data.conf?
- Did you modify the data from the database manually? 
- If you still have a copy of the 22.0.2 database, can you open it and tell which version schema is in the table `CB_SCHEMA_INFO`?

**Comment by metalshanked** [comment]
I see the same error on a brand new install of 23.0.4 using old configs from 22 or older.

i.e.  the below from OP
![image](https://github.com/dbeaver/cloudbeaver/assets/57646596/19d1c2d9-cfe5-4765-b9cd-f0712cd02e28)

In my case even removing the initial-data.conf and initial-data-sources.conf does not help

**Comment by alexander-skoblikov** [comment]
@metalshanked Hi, can you attach full server log with the error?

**Comment by TatyanaSsau** [comment]
@pmpetit I've noticed there is no updates for a long time. 
Please contact me to reopen the ticket if it's still actual!
It is really important for me.
