### ISSUE TITLE
Cannot execute or edit saved scripts/queries

### ISSUE THREAD

**Issue by philippconzett** [dbeaver/cloudbeaver#1795]
**Describe the bug**
After having saved an SQL query, I'm not able to execute or edit the saved query. 

**To Reproduce**
1. Go to your CloudBeaver instance.
2. Click on the SQL button on the top left corner. Add your SQL query. Save the query by clicking the Save button.
3. Close your CloudBeaver instance.
4. Re-open your CloudBeaver instance.
5. Open the saved query.
6. Try to execute (Ctrl+Enter) or edit the query.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox (in Chrome and Edge, it is not possible to open a saved query)
 - Version: Developer 115.0b9 (64-bit)

**Additional context**
Error log:

java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:253)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by TatyanaSsau** [comment]
@philippconzett thank you for your report!
Unfortunately, I can not reproduce this case with 23.1.1 version.
Please, move the cursor to the next line in the SQL Editor tab and try to edit the query.

And could you provide the version of CloudBeaver? It will allow me to reproduce the issue.

**Comment by philippconzett** [comment]
@TatyanaSsau thank you for your reply!
I'm using Backend version: 23.1.1.202306260905; Frontend version: 23.1.1.202306260910.
I just gave it another try, and it worked, so I don't know why it didn't work when I reported this issue.
Sorry for the inconvenience!

**Comment by TatyanaSsau** [comment]
@philippconzett I'm very glad to hear that everything worked out! Thank you very much for using [CloudBeaver](https://github.com/dbeaver/cloudbeaver/wiki)
