### ISSUE TITLE
impossible to connect Postgresql/Postgis with cloudbeaver

### ISSUE THREAD

**Issue by ammoniaca** [dbeaver/cloudbeaver#1797]
Please, describe your question in details.
I created three docker containers locally: one with kartoza/postgis image, the second with pg4admin image and the third with cloudbeaver image:

```
version: "3.8"
#name: my-project-name


services:

  postgis:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALLOW_IP_RANGE=${POSTGRES_ALLOW_IP_RANGE}
      - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS}
      - POSTGRES_DATA_VOLUME:${POSTGRES_DATA_VOLUME}
    restart: on-failure
    volumes:
      - postgis-data:${POSTGRES_DATA_VOLUME}
    networks:
      - postgis_network

  pgadmin:
    image: dpage/pgadmin4:${PGADIM_VERION_TAG}
    container_name: ${PGADIM_CONTAINER_NAME}
    ports:
      - "5050:80"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE:${PGADMIN_CONFIG_SERVER_MODE}
    networks:
      - postgis_network
    volumes:
      - pgadmin-data:${PGADIM_DATA_VOLUME}
        #depends_on:
      #postgis:
      #condition: service_healthy

  cloudbeaver:
    image: dbeaver/cloudbeaver:23.1.0
    container_name: cloudbeaver_container
    restart: always
    ports:
      - "8085:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - postgis_network



volumes:
  postgis-data:
  pgadmin-data:
  cloudbeaver-data:

networks:
  postgis_network:
      driver: bridge
```

When I want to connect with pgadmin everything works without problems but if I want to connect with cloudbeaver I have this error message:

![image](https://github.com/dbeaver/cloudbeaver/assets/42351229/20526357-972d-4350-810a-84690942f60e)

![image](https://github.com/dbeaver/cloudbeaver/assets/42351229/76ccbf10-f48e-4b1d-bb40-7c7fac4a397b)

```

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
	at java.base/java.lang.Thread.run(Unknown Source)
```

![image](https://github.com/dbeaver/cloudbeaver/assets/42351229/b3f1e77f-0692-40d5-9888-7da4c572811e)

**Comment by alexander-skoblikov** [comment]
@ammoniaca Hi!
According to your configuration, you need to specify `postgis` as host, or you can specify a custom host by adding the `hostname` parameter

```

 postgis:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    hostname: my_host_name
    .....
```

**Comment by TatyanaSsau** [comment]
@ammoniaca I've noticed there is no updates for a long time.
Please - feel free to reopen the ticket if it's still actual.
