### ISSUE TITLE
Trino driver shows java error after successful test connection when trying to dropdown Tables

### ISSUE THREAD

**Issue by YuriyGavrilov** [dbeaver/cloudbeaver#1810]
**Describe the bug**

after successful test connection and connect when I am trying to dropdown Tables it shows this stack:
but desktop version works fine with same config.

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at io.trino.jdbc.$internal.okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.trino.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.trino.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:71)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.trino.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at io.trino.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:77)
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:131)
	at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:110)
	at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
	at io.trino.jdbc.QueryExecutor.startQuery(QueryExecutor.java:46)
	at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:728)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:239)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:227)
	at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:76)
	at io.trino.jdbc.TrinoDatabaseMetaData.select(TrinoDatabaseMetaData.java:1448)
	at io.trino.jdbc.TrinoDatabaseMetaData.getTables(TrinoDatabaseMetaData.java:936)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:586)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:67)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:74)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:159)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:143)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:416)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at io.cloudbeaver.service.navigator.impl.WebServiceNavigator.getNavigatorNodeChildren(WebServiceNavigator.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**To Reproduce**

**Screenshots**
<img width="1299" alt="Снимок экрана 2023-07-08 в 21 56 38" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/395e7131-3bfe-4657-8acf-fb0324bf1819">

**Desktop (please complete the following information):**

**Additional context**
same DB opens well on desktop DBeaver
<img width="288" alt="Снимок экрана 2023-07-08 в 21 58 59" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/42c5e1ee-2be9-419c-80dc-a923beaa2c18">

**Comment by dariamarutkina** [comment]
Hello @YuriyGavrilov ,
I can't reproduce this issue. Please tell me which version of the app you are using.

**Comment by YuriyGavrilov** [comment]
> Hello @YuriyGavrilov ,
> I can't reproduce this issue. Please tell me which version of the app you are using.

I used docker version of cloud dbeaver latest and trino FROM trinodb/trino:408 with metastore 3.2.1

**Comment by dariamarutkina** [comment]
@YuriyGavrilov Thank you for the information!
This behavior (first a successful connection, and then an error when opening the table) may be in the Trino database itself. Can you please check the connection settings, especially check the port. Please write to me what the result will be.

**Comment by YuriyGavrilov** [comment]
> @YuriyGavrilov Thank you for the information!
> This behavior (first a successful connection, and then an error when opening the table) may be in the Trino database itself. Can you please check the connection settings, especially check the port. Please write to me what the result will be.

Hi @dariamarutkina due to I use default Trino docker there is not to much settings which should be changed in the test.

<img width="1245" alt="Снимок экрана 2023-07-15 в 12 05 01" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/2a264578-b411-4466-9687-d80a5b4f66e8">
<img width="1203" alt="Снимок экрана 2023-07-15 в 12 05 11" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/e68fcfb9-d4c1-4606-9407-8ba147b70287">
<img width="1186" alt="Снимок экрана 2023-07-15 в 12 05 17" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/6f189eea-e8b0-43b0-abfe-c9a32eb24c07">
<img width="256" alt="Снимок экрана 2023-07-15 в 12 05 38" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/aba04853-a866-4976-897a-988c77d14d3b">
<img width="534" alt="Снимок экрана 2023-07-15 в 12 05 48" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/68a6fd87-4986-45ef-9a0e-ed5c19506368">


Same settings in the desktop dbeaver:
<img width="968" alt="Снимок экрана 2023-07-15 в 12 11 18" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/b810fdd1-46bc-4b62-b4f2-649752d04c93">
<img width="961" alt="Снимок экрана 2023-07-15 в 12 11 40" src="https://github.com/dbeaver/cloudbeaver/assets/44679014/287dba18-4cdc-42e6-9a5a-b97891004b65">

**Comment by LonwoLonwo** [comment]
It looks like the issue is in the driver version. In CloudBeaver, it is older.

**Comment by YuriyGavrilov** [comment]
> It looks like the issue is in the driver version. In CloudBeaver, it is older.

@LonwoLonwo it seems you are right, in the cloud version there is 351 version (the first one), but in reality there is already a version 422 of the driver.

![image](https://github.com/dbeaver/cloudbeaver/assets/44679014/23e3d296-a036-4cf2-9c0f-365fa6604747)
![image](https://github.com/dbeaver/cloudbeaver/assets/44679014/a6bb05df-e2f0-4b23-8439-bfc9c1721eea)

**Comment by dariamarutkina** [comment]
@YuriyGavrilov thank you for bug reporting!
We are going to fix it in the near future.

**Comment by yagudin10** [comment]
Hi, @YuriyGavrilov,
There will be a new driver in the next release, but it seems like you have the problem with connection configuration.
Could you explain us, why host parameter from connection configuration is different between CloudBeaver and DBeaver?

**Comment by YuriyGavrilov** [comment]
@yagudin10 there is only one change. In dbeaver I use localhost due to it run inside the docker container but in case of cloudbeaver I use the name inside docker network trino name or trino1

**Comment by YuriyGavrilov** [comment]
@yagudin10 other settings are the same.

**Comment by EvgeniaBzzz** [comment]
Hi, @YuriyGavrilov,
Trino driver has been upgraded to version 3.41. Please, check CloudBeaver v.23.1.4.

**Comment by YuriyGavrilov** [comment]
@EvgeniaBzzz trying to test. Thanks a lot!

**Comment by YuriyGavrilov** [comment]
@EvgeniaBzzz tests are done. Everything perfect. Thanks a lot! 
![image](https://github.com/dbeaver/cloudbeaver/assets/44679014/6c08bc6b-1452-4dc2-bdb4-351c231b66d3)

**Comment by YuriyGavrilov** [comment]
@EvgeniaBzzz  but wrote that "Trino driver has been upgraded to version 3.41. Please, check CloudBeaver v.23.1.4." 
but the current version of driver is 422 - https://mvnrepository.com/artifact/io.trino/trino-jdbc. There is no 3.41 version as you mention. Just to understand...

**Comment by EvgeniaBzzz** [comment]
@YuriyGavrilov sure, thanks for the correction )
