### ISSUE TITLE
SQL error during setup new cloud beaver configuration database on oracle. 

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#1849]
We run Cloud Beaver on Kubernetes and try to use an external configuration database on oracle. After Pod start he is creating all DB Tables in "CB" database schema, but runs after that in an error " ORA-00933: SQL command not properly ended"

**cloudbeaver.conf**

         database: {
            driver="oracle",
            url: "jdbc:oracle:thin:@dbora002:1521:wsdc1",
            user: "CB",
            password: "xxx",

            createDatabase: true,

            initialDataConfiguration: "conf/initial-data.conf",

            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

**Pod Log**

`Starting Cloudbeaver Server
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
26-07-2023 11:20:25.404 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /opt/cloudbeaver/conf/cloudbeaver.conf
26-07-2023 11:20:25.405 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]
26-07-2023 11:20:25.406 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/opt/cloudbeaver/conf/cloudbeaver.conf]
26-07-2023 11:20:25.583 [main] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from '/opt/cloudbeaver/conf/product.conf'
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 23.1.3.202307241029 is starting
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - 	OS: Linux 4.18.0-372.64.1.el8_6.x86_64 (amd64)
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Java version: 17.0.4.1 by Eclipse Adoptium (64bit)
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Install path: '/opt/cloudbeaver/server'
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Global workspace: 'file:/opt/cloudbeaver/workspace/'
26-07-2023 11:20:25.590 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Memory available 12Mb/121Mb
26-07-2023 11:20:25.676 [main] DEBUG io.cloudbeaver.server.CBPlatform - Initializing product: CloudBeaver CE Server 23.1.3
26-07-2023 11:20:25.677 [main] DEBUG io.cloudbeaver.server.CBPlatform - Host plugin: io.cloudbeaver.product.ce 23.1.3.202307241029
26-07-2023 11:20:25.677 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...
26-07-2023 11:20:26.475 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC
26-07-2023 11:20:27.198 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...
26-07-2023 11:20:28.081 [main] DEBUG o.j.d.r.DataSourceProviderRegistry - Total database drivers: 105 (105)
26-07-2023 11:20:28.089 [main] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: ClickHouse (Legacy),ClickHouse,Db2 for LUW,Db2 for IBM i,Firebird,Derby Server,Trino,H2 Embedded,H2 Embedded V.2,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
26-07-2023 11:20:28.090 [main] INFO  io.cloudbeaver.server.CBPlatform - Web platform initialized (2413ms)
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Content root: /opt/cloudbeaver/web
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Drivers storage: /opt/cloudbeaver/drivers
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Listen port: 8978 on all interfaces
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Base URI: /api/
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Production mode
26-07-2023 11:20:28.090 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Server is in configuration mode!
26-07-2023 11:20:28.183 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Local host addresses:
26-07-2023 11:20:28.183 [main] DEBUG io.cloudbeaver.server.CBApplication - 		10.0.136.152 (dbeaver-6c477b88c9-2dj74)
26-07-2023 11:20:28.184 [main] DEBUG io.cloudbeaver.server.CBApplication - 		0:0:0:0:0:0:0:1%lo (localhost)
26-07-2023 11:20:28.400 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database
26-07-2023 11:20:29.093 [main] DEBUG i.c.service.security.db.CBDatabase - 	Initiate connection pool with management database (Oracle; jdbc:oracle:thin:@dbora002.p01.its.aareon.com:1521:wsdc1)
26-07-2023 11:20:30.604 [main] DEBUG i.c.service.security.db.CBDatabase - 	Connected to Oracle Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production
26-07-2023 11:20:31.188 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Update schema CB version from 1 to 2
26-07-2023 11:20:31.689 [main] DEBUG o.j.d.m.sql.schema.SQLSchemaManager - Process [DROP TABLE IF EXISTS CB_SERVER]
26-07-2023 11:20:31.780 [main] ERROR o.j.d.m.sql.schema.SQLSchemaManager - Error during sql migration
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:896)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1737)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:199)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.upgradeSchemaVersion(SQLSchemaManager.java:145)
	at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:116)
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:215)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:65)
	at io.cloudbeaver.server.CBApplicationCE.createGlobalSecurityController(CBApplicationCE.java:63)
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:481)
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:324)
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:225)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 36 common frames omitted
26-07-2023 11:20:31.780 [main] INFO  o.j.d.m.sql.schema.SQLSchemaManager - Trying to apply the migration again
26-07-2023 11:20:31.783 [main] WARN  o.j.d.m.sql.schema.SQLSchemaManager - Error updating CB schema version from 1 to 2`

**Comment by MatthiasSchnoeke** [comment]
DROP TABLE IF **EXISTS** CB_SERVER  is not a valide Oracle statement. How can we change this?

**Comment by TatyanaSsau** [comment]
@MatthiasSchnoeke thank you for your report! It is bug.
We added it to the backlog to provide solution with this case.

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke!
Some fixes were made in 23.2.4. Please, try again.
Delete Oracle tables which were created in your previous try before running server.

**Comment by EvgeniaBzzz** [comment]
If you encounter any futher problems, please do not hesitate to reach out to us.
We're grateful for your support and engagement with our project!
