### ISSUE TITLE
recurring authentication issue

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#1881]
Very often, the first logons in the morning run into an error. The authentication is then only successful after 5 attempts.
We run CB in connection to a Maria configuration DB.

`08-08-2023 05:43:32.156 [Test datasource connection] DEBUG i.c.s.session.WebSessionManager - New web session 'ozo6xqotrfz71g9g9ionb33jf1126'
08-08-2023 05:43:32.627 [Test datasource connection] DEBUG i.c.server.graphql.GraphQLEndpoint - API > getAuthProviders
08-08-2023 05:43:32.633 [qtp765329253-30] DEBUG i.c.server.graphql.GraphQLEndpoint - API > sessionPermissions
08-08-2023 05:43:35.494 [Test datasource connection] DEBUG i.c.server.graphql.GraphQLEndpoint - API > authLogin
08-08-2023 05:43:35.505 [Test datasource connection] DEBUG i.c.server.graphql.GraphQLEndpoint - GraphQL call failed at '/authInfo'
io.cloudbeaver.DBWebException: User authentication failed:
(conn=58) Connection reset by peer
	at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.cloudbeaver.service.WebServiceBindingBase$ServiceInvocationHandler.invoke(WebServiceBindingBase.java:169)
	at jdk.proxy6/jdk.proxy6.$Proxy10.authLogin(Unknown Source)
	at io.cloudbeaver.service.auth.WebServiceBindingAuth.lambda$0(WebServiceBindingAuth.java:39)
	at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:309)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:286)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:212)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
	at graphql.execution.Execution.executeOperation(Execution.java:161)
	at graphql.execution.Execution.execute(Execution.java:104)
	at graphql.GraphQL.execute(GraphQL.java:557)
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:476)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:471)
	at graphql.GraphQL.executeAsync(GraphQL.java:439)
	at graphql.GraphQL.execute(GraphQL.java:365)
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeQuery(GraphQLEndpoint.java:249)
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeSingleQuery(GraphQLEndpoint.java:195)
	at io.cloudbeaver.server.graphql.GraphQLEndpoint.doPost(GraphQLEndpoint.java:178)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jkiss.dbeaver.DBException: (conn=58) Connection reset by peer
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.createNewAuthAttempt(CBEmbeddedSecurityController.java:1267)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.authenticate(CBEmbeddedSecurityController.java:1167)
	at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:80)
	... 58 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: (conn=58) Connection reset by peer
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:240)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:248)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:338)
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:527)
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:741)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCTransaction.<init>(JDBCTransaction.java:38)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.createNewAuthAttempt(CBEmbeddedSecurityController.java:1229)
	... 60 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: Connection reset by peer
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:1925)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:236)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)
	... 66 common frames omitted
Caused by: java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream.flushBuffer(StandardPacketOutputStream.java:111)
	at org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream.flush(AbstractPacketOutputStream.java:185)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
	... 67 common frames omitted`

**Comment by TatyanaSsau** [comment]
@MatthiasSchnoeke please, try to set `autoReconnect=true` for mariaDB, the connector will simply try to reconnect to its host after a failure.

**Comment by MatthiasSchnoeke** [comment]
Where is this option defined in cloudbeaver.conf?


{
    server: {
        serverPort: 8978,

        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        rootURI: "/",
        serviceURI: "/api/",

        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 21600000,

        develMode: false,

        enableSecurityManager: false,

        database: {
            driver="mariadb",
            url: "jdbc:mariadb://dbeaver-mariadb-service.cloud-beaver.svc.cluster.local:3306/cb",
            user: xxx",
            password: "xxx",

            createDatabase: true,

            initialDataConfiguration: "conf/initial-data.conf",

            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

    },
    app: {
        anonymousAccessEnabled: false,
        anonymousUserRole: "user",
        supportsCustomConnections: false,

        forwardProxy: false,

        publicCredentialsSaveEnabled: false,
        adminCredentialsSaveEnabled: false,

        resourceManagerEnabled: true,

        resourceQuotas: {
            dataExportFileSizeLimit: 10000000,
            resourceManagerFileSizeLimit: 500000,
            sqlMaxRunningQueries: 100,
            sqlResultSetRowsLimit: 100000,
            sqlResultSetMemoryLimit: 2000000,
            sqlTextPreviewMaxLength: 4096,
            sqlBinaryPreviewMaxLength: 261120
        },
        enabledAuthProviders: [
            "local"
        ],

        disabledDrivers: [
            "sqlite:sqlite_jdbc",
            "h2:h2_embedded",
            "clickhouse:yandex_clickhouse"
        ]

    }

}

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke 
Sorry for that delay
Try to add parametr to cloudbeaver.conf / .cloudbeaver.runtime.conf
`url: "jdbc:mariadb://dbeaver-mariadb-service.cloud-beaver.svc.cluster.local:3306/cb?autoreconnect=true"`

**Comment by EvgeniaBzzz** [comment]
It's been some time since last update on this issue. Please let us know if you have any further questions.

**Comment by MatthiasSchnoeke** [comment]
Hello,
sorry delay. The problem still exists despite the parameters.

**Comment by MatthiasSchnoeke** [comment]
Here the stacktrace:

java.net.SocketException: Connection reset by peer
            at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
            at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
            at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
            at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
            at org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream.flushBuffer(StandardPacketOutputStream.java:111)
            at org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream.flush(AbstractPacketOutputStream.java:185)
            at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
            at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)
            at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:527)
            at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:741)
            at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
            at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
            at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCTransaction.<init>(JDBCTransaction.java:38)
            at io.cloudbeaver.service.security.CBEmbeddedSecurityController.createNewAuthAttempt(CBEmbeddedSecurityController.java:1329)
            at io.cloudbeaver.service.security.CBEmbeddedSecurityController.authenticate(CBEmbeddedSecurityController.java:1264)
            at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:80)
            at jdk.internal.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke 
Sorry for that delay. We will need some more time to find a solutioin, as it works as expected on our test servers.
Thank you for the report!

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke!
'Keep-alive' option has been added in 23.3.3. Now you can configure alive time in the connection settings.

**Comment by EvgeniaBzzz** [comment]
Hi @MatthiasSchnoeke!
We have improved internal database reconnection. Please, check it out in 23.3.3

**Comment by MatthiasSchnoeke** [comment]
Hi,
it seems your improvement has solved this issue. Thanks so far!

**Comment by MatthiasSchnoeke** [comment]
unfortunately it took 4 logins again today to successfully log in

java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
	at org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream.flushBuffer(StandardPacketOutputStream.java:111)
	at org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream.flush(AbstractPacketOutputStream.java:185)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:527)
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:741)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCTransaction.<init>(JDBCTransaction.java:38)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.createNewAuthAttempt(CBEmbeddedSecurityController.java:1403)
	at io.cloudbeaver.service.security.CBEmbeddedSecurityController.authenticate(CBEmbeddedSecurityController.java:1334)
	at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by EvgeniaBzzz** [comment]
It seems like your MariaDB is configured to kill connections, but close it only on the DB side.

Please, try to change `.cloudbeaver.runtime.conf` in the `server.database.pool` [section](https://dbeaver.com/docs/cloudbeaver/Server-configuration/#database-connection-pool-configuration):
```
minIdleConnections=0
maxIdleConnections=0
```

or

```
minIdleConnections=0
```

**Comment by EvgeniaBzzz** [comment]
It’s been a while since an update here. Please contact us if you have any further questions.

**Comment by MatthiasSchnoeke** [comment]
sorry but the issue still exists. despite the configurations.

here my current config map:

 {
    server: {
        serverPort: 8978,

        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        rootURI: "/",
        serviceURI: "/api/",

        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 21600000,

        develMode: false,

        enableSecurityManager: false,

        database: {
            driver="mariadb",
            url: "jdbc:mariadb://dbeaver-mariadb-service.cloud-beaver.svc.cluster.local:3306/cb?autoreconnect=true",
            user: "root",
            password: "xxx",

            createDatabase: true,

            initialDataConfiguration: "conf/initial-data.conf",

            pool: {
                minIdleConnections: 0,
                maxIdleConnections: 0,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

    },
    app: {
        anonymousAccessEnabled: false,
        anonymousUserRole: "user",
        supportsCustomConnections: false,

        forwardProxy: false,

        publicCredentialsSaveEnabled: false,
        adminCredentialsSaveEnabled: false,

        resourceManagerEnabled: true,

        resourceQuotas: {
            dataExportFileSizeLimit: 10000000,
            resourceManagerFileSizeLimit: 500000,
            sqlMaxRunningQueries: 100,
            sqlResultSetRowsLimit: 100000,
            sqlResultSetMemoryLimit: 2000000,
            sqlTextPreviewMaxLength: 4096,
            sqlBinaryPreviewMaxLength: 261120
        },
        enabledAuthProviders: [
            "local"
        ],

        disabledDrivers: [
            "sqlite:sqlite_jdbc",
            "h2:h2_embedded",
            "clickhouse:yandex_clickhouse"
        ]

    }

}

**Comment by EvgeniaBzzz** [comment]
@MatthiasSchnoeke 
Have you tried to add `minIdleConnections`?

**Comment by MatthiasSchnoeke** [comment]
Yes as you can see above.

pool: {
            minIdleConnections: 0,
            maxIdleConnections: 0,
            maxConnections: 100,
            validationQuery: "SELECT 1"
        }

**Comment by LonwoLonwo** [comment]
Hello @MatthiasSchnoeke 
Thanks for the report. We will look at it in one of our feature releases.

**Comment by phantom943** [comment]
We also experience this. We didn't see this when using a built-in H2 database.
We are using postgres, though, so it's not a mariadb issue per se.
Our logs:
<details>
  <summary>Logs</summary>

```bash
io.cloudbeaver.DBWebException: User authentication failed:
User authentication failed:
Error while loading users
at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:115)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at io.cloudbeaver.service.WebServiceBindingBase$ServiceInvocationHandler.invoke(WebServiceBindingBase.java:170)
at jdk.proxy7/jdk.proxy7.$Proxy13.authLogin(Unknown Source)
at io.cloudbeaver.service.auth.WebServiceBindingAuth.lambda$0(WebServiceBindingAuth.java:39)
at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:533)
at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:497)
at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:438)
at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:397)
at graphql.execution.ExecutionStrategy.getAsyncFieldValueInfo(ExecutionStrategy.java:335)
at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:57)
at graphql.execution.Execution.executeOperation(Execution.java:180)
at graphql.execution.Execution.execute(Execution.java:116)
at graphql.GraphQL.execute(GraphQL.java:546)
at graphql.GraphQL.lambda$parseValidateAndExecute$13(GraphQL.java:476)
at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:471)
at graphql.GraphQL.lambda$executeAsync$9(GraphQL.java:429)
at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
at graphql.GraphQL.executeAsync(GraphQL.java:418)
at graphql.GraphQL.execute(GraphQL.java:359)
at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeQuery(GraphQLEndpoint.java:262)
at io.cloudbeaver.server.graphql.GraphQLEndpoint.executeSingleQuery(GraphQLEndpoint.java:203)
at io.cloudbeaver.server.graphql.GraphQLEndpoint.doPost(GraphQLEndpoint.java:186)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:653)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeHandler.handle(WebSocketUpgradeHandler.java:227)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
at org.eclipse.jetty.server.Server.handle(Server.java:181)
at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jkiss.dbeaver.DBException: User authentication failed:
Error while loading users
at io.cloudbeaver.model.session.WebSessionAuthProcessor.authenticateSession(WebSessionAuthProcessor.java:79)
at io.cloudbeaver.service.auth.impl.WebServiceAuthImpl.authLogin(WebServiceAuthImpl.java:110)
... 55 common frames omitted
Caused by: io.cloudbeaver.DBWebException: User authentication failed:
Error while loading users
at io.cloudbeaver.model.session.WebSessionAuthProcessor.finishWebSessionAuthorization(WebSessionAuthProcessor.java:184)
at io.cloudbeaver.model.session.WebSessionAuthProcessor.authenticateSession(WebSessionAuthProcessor.java:65)
... 56 common frames omitted
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Error while loading users
at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getCurrentUserParameters(CBEmbeddedSecurityController.java:689)
at io.cloudbeaver.model.session.WebUserContext.refresh(WebUserContext.java:123)
at io.cloudbeaver.model.session.WebUserContext.refresh(WebUserContext.java:96)
at io.cloudbeaver.model.session.BaseWebSession.updateSMSession(BaseWebSession.java:117)
at io.cloudbeaver.model.session.WebSession.updateSMSession(WebSession.java:875)
at io.cloudbeaver.model.session.WebSessionAuthProcessor.finishWebSessionAuthorization(WebSessionAuthProcessor.java:95)
... 57 common frames omitted
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)
at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:123)
at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:123)
at io.cloudbeaver.service.security.CBEmbeddedSecurityController.getCurrentUserParameters(CBEmbeddedSecurityController.java:679)
... 62 common frames omitted
Caused by: java.net.SocketException: Connection reset
at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162)
at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129)
at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74)
at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
... 69 common frames omitted
```
</details>

**Comment by MatthiasSchnoeke** [comment]
From time to time we still run into this login problem.

**Comment by LonwoLonwo** [comment]
Hello @phantom943 

> We also experience this.

Could you please provide info about at which moment and what exactly is happening?

**Comment by phantom943** [comment]
> Hello @phantom943
> 
> > We also experience this.
> 
> Could you please provide info about at which moment and what exactly is happening?

Hello @LonwoLonwo 
This happens for me when I click "Login" on the website.
The logs I posted above are from the backend though.
![image](https://github.com/user-attachments/assets/6793cf9f-84a4-4ae4-8867-f54f73809fa5)

This usually happens several times consecutively, and then on the 3rd or 5th try it lets me in

In terms of versions, we are running 24.3.0

**Comment by phantom943** [comment]
Hello @LonwoLonwo 
Now that we have set 
```
minIdleConnections: 0,
maxIdleConnections: 0
```
the error seems to go away. Thanks for your help!
As a suggestion, maybe those values should be set as default in future releases, as to prevent poor user experience here?
