### ISSUE TITLE
SSL Postgresql

### ISSUE THREAD

**Issue by GaetanColenoTiime** [dbeaver/cloudbeaver#1889]
Hi ! I try to use SSL for Postgresql, i use cloudbeaver 23.1.4 (so as i read on other issues, it should be implemented)
I try to add my ssl keys. i mapped on my docker compose all my files, and use the path in the container to read the files, but with the error when trying to test the connection, i don't know if it's the keys, or if it's missing something
I tried with the same conf on dbeaver and it works perfectly

Error is : 
`Error connecting to database:
Connection failed:
Loading the SSL root certificate /opt/cloudbeaver/workspace/.metadata/.plugins/io.cloudbeaver.server/security/postgres-jdbc-postgres-jdbc-189d56fab84-7a62aaed048253f27472579677853312398.cert into a TrustManager failed.
java.security.cert.CertificateException: No certificate data found
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(Unknown Source)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(Unknown Source)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(Unknown Source)
	at org.postgresql.ssl.LibPQFactory.<init>(LibPQFactory.java:158)
	at org.postgresql.core.SocketFactoryFactory.getSslSocketFactory(SocketFactoryFactory.java:61)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:34)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
	at java.base/java.lang.Thread.run(Unknown Source)`

Thanks in advance to help me with it ! Working on a toolbox with docker ^^

**Comment by yagudin10** [comment]
Hi, @GaetanColenoTiime ,
The DBeaver and CloudBeaver SSL configuration must be different because you need to set the contents of the certificates and key.
Did I understand correctly that you set the path of files in CloudBeaver?

**Comment by GaetanColenoTiime** [comment]
Hi @yagudin10 thanks for the answer

Yea, i tryied to set the path, that's good that you mention this difference (i did not see any in the doc, maybe i missed it)
So, i tried to put them, but.. what about the .der file ? or we can go back to the .pem one ? cause on dbeaver we need to change it to .der, and it is not realy readable (or maybe need another tool that i don't have..)

**Comment by EvgeniaBzzz** [comment]
Hi @GaetanColenoTiime 
Sorry for that delay 
You have to convert your certificate from .der to .pem (we do not support .der yet)

**Comment by GaetanColenoTiime** [comment]
Hi @EvgeniaBzzz 
I tried today, with 3 keys, on dbeaver, it works, but when i use them on cloudbeaver, does not work. I set everything same
Only difference, is that, on dbeaver it's path and on cloudbeaver it's content..

Here is the error log

`Error connecting to database:
Connection failed:
Internal error connecting to jdbc:postgresql://teleport.tiime.tech:443/hub
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:544)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:226)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:119)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:275)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:170)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:103)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:114)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1276)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1115)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:948)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:660)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)`

**Comment by EvgeniaBzzz** [comment]
@GaetanColenoTiime hello!
We have made a small bug-fix in 23.2.3, please try again

**Comment by GaetanColenoTiime** [comment]
Hi, it seems to work, i access to the cluster, but.. but..
Error connecting to database:
Connection failed:
database "" not found among registered databases in cluster "xxx"

database "", but i set a database in the options..

**Comment by yagudin10** [comment]
Hi, @GaetanColenoTiime !
Can you provide the log file, please?

**Comment by GaetanColenoTiime** [comment]
Okey so, i had 2 certificate generated, one work, not the other, but the error is not straightforward. here is the error with the cert that does not work (i still have to understand this, but it's to my ops team i have to check)

`Error connecting to database:
Connection failed:
database "" not found among registered databases in cluster "teleport.tiime.tech"
org.postgresql.util.PSQLException: database "" not found among registered databases in cluster "teleport.tiime.tech"
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:385)
	at org.postgresql.Driver.connect(Driver.java:298)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:246)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:259)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:278)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:551)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:579)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:277)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:172)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:105)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:114)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1280)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:677)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)`

**Comment by yagudin10** [comment]
Hi, @GaetanColenoTiime!
Can you please check if you have the same problem in DBeaver?

**Comment by GaetanColenoTiime** [comment]
Hi @yagudin10 I will check, but i had no problem using my keys in dbeaver (with path)

**Comment by EvgeniaBzzz** [comment]
Hi @GaetanColenoTiime!
Any news here?

**Comment by GaetanColenoTiime** [comment]
Sorry, it seems that i managed to make it work, i think i was just putting the wrong key (teleport was generating 2 different keys) it's all good !
Is there any plan to add the possibility to use path instead of raw content ? (so when the content change, the connection still works )

**Comment by EvgeniaBzzz** [comment]
Happy to hear that!
We are not going to add path like in DBeaver. As we do not want to allow access to the file system.
But we will add easier file uploading.

Thank you for being with CloudBeaver!

**Comment by GaetanColenoTiime** [comment]
That's a good idea @EvgeniaBzzz ! 
And i understand for the filesystem (maybe could use something like .cbeaver/config, and upload inside this folder or something like this ? since it already use some files and folder)

**Comment by EvgeniaBzzz** [comment]
Yeah, you are right - we are going to add Upload button (as it was done for SSH tab). User will initiate upload, without permanent access for the app to the file system

**Comment by GaetanColenoTiime** [comment]
And so, as a user of docker, will we be able to do it manually with mounted volume ? (so we don't need to upload everytime, if we know the path of the storage)

**Comment by EvgeniaBzzz** [comment]
I am currently finding it difficult to respond. It will become clear after detailed planning.

**Comment by GaetanColenoTiime** [comment]
No problem !
i'll look forward to it
