### ISSUE TITLE
org.jkiss.dbeaver.DBException: Driver 'postgres-jdbc' not found、The underlying library driver cannot be found

### ISSUE THREAD

**Issue by Amor7527** [dbeaver/cloudbeaver#2219]
Can't start cloudbeaver in ECLIPSE

```

!ENTRY org.jkiss.dbeaver.ui.editors.sql.terminal 4 0 2023-12-13 17:40:59.125
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.jkiss.dbeaver.ui.editors.sql.terminal [728]
  Unresolved requirement: Require-Bundle: org.jkiss.dbeaver.core
    -> Bundle-SymbolicName: org.jkiss.dbeaver.core; bundle-version="23.3.0.qualifier"; singleton:="true"
       org.jkiss.dbeaver.core [608]
         Unresolved requirement: Require-Bundle: org.osgi.service.event

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
17:40:59.417 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from /Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf
17:40:59.420 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [/Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf]
17:40:59.420 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [/Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/deploy/cloudbeaver/conf/cloudbeaver.conf]
17:40:59.476 [main] ERROR io.cloudbeaver.server.CBApplication - Product configuration file not found (/Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/conf/product.conf'
17:40:59.492 [main] ERROR o.j.d.m.impl.app.ApplicationRegistry - Multiple applications defined. Use the first one (cloudbeaver-ce), skip the rest (headless-test-app)
17:40:59.493 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 23.3.0.qualifier is starting
17:40:59.493 [main] DEBUG io.cloudbeaver.server.CBApplication - 	OS: Mac OS X 14.0 (x86_64)
17:40:59.493 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Java version: 17.0.3 by Amazon.com Inc. (64bit)
17:40:59.494 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Install path: '/Applications/Eclipse 2022.app/Contents/Eclipse'
17:40:59.494 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Global workspace: 'file:/Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/runtime-DBeaverWebServer.product/'
17:40:59.494 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Memory available 260Mb/4096Mb
17:40:59.550 [main] DEBUG io.cloudbeaver.server.CBPlatform - Initializing product: CloudBeaver CE Server 23.3.0
17:40:59.550 [main] DEBUG io.cloudbeaver.server.CBPlatform - Host plugin: io.cloudbeaver.product.ce 23.3.0.qualifier
17:40:59.551 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...
17:40:59.682 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC
17:41:00.230 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...
17:41:00.368 [main] DEBUG o.j.d.r.DataSourceProviderRegistry - Total database drivers: 7 (7)
17:41:00.379 [main] ERROR io.cloudbeaver.server.CBPlatform - 	Driver 'db2' is missing library 'drivers/db2'
17:41:00.381 [main] ERROR io.cloudbeaver.server.CBPlatform - 	Driver 'mysql8' is missing library 'drivers/mysql/mysql8'
17:41:00.382 [main] ERROR io.cloudbeaver.server.CBPlatform - 	Driver 'mariaDB' is missing library 'drivers/mariadb'
17:41:00.382 [main] ERROR io.cloudbeaver.server.CBPlatform - 	Driver 'oracle_thin' is missing library 'drivers/oracle'
17:41:00.383 [main] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: 
17:41:00.385 [main] INFO  io.cloudbeaver.server.CBPlatform - Web platform initialized (834ms)
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Content root: /Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/web
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Drivers storage: /Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/drivers
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Listen port: 8978 on all interfaces
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Base URI: /api/
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Production mode
17:41:00.385 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Server is in configuration mode!
17:41:00.532 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Local host addresses:
17:41:00.533 [main] DEBUG io.cloudbeaver.server.CBApplication - 		10.10.15.106 (bogon)
17:41:00.534 [main] DEBUG io.cloudbeaver.server.CBApplication - 		0:0:0:0:0:0:0:1%lo0 (localhost)
17:41:00.621 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database
17:41:00.655 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Driver 'postgres-jdbc' not found
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:123) ~[io.cloudbeaver.service.security_1.0.42.202312130925.jar:na]
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:65) ~[io.cloudbeaver.service.security_1.0.42.202312130925.jar:na]
	at io.cloudbeaver.server.CBApplicationCE.createGlobalSecurityController(CBApplicationCE.java:62) ~[io.cloudbeaver.server_23.3.0.202312130925.jar:na]
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:506) ~[io.cloudbeaver.server_23.3.0.202312130925.jar:na]
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:338) ~[io.cloudbeaver.server_23.3.0.202312130925.jar:na]
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:235) ~[io.cloudbeaver.model_1.0.42.202312130925.jar:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[org.eclipse.equinox.app_1.6.100.v20211021-1418.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) ~[org.eclipse.osgi_3.18.0.v20220516-2155.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[org.eclipse.osgi_3.18.0.v20220516-2155.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) ~[org.eclipse.osgi_3.18.0.v20220516-2155.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[org.eclipse.osgi_3.18.0.v20220516-2155.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651) ~[org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588) ~[org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459) ~[org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432) ~[org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar:na]
17:41:00.703 [Framework stop - Equinox Container: 9575e416-ad64-40be-871a-cc29aabbc9c2] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
17:41:00.783 [Framework stop - Equinox Container: 9575e416-ad64-40be-871a-cc29aabbc9c2] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 79ms

!ENTRY org.eclipse.core.jobs 2 2 2023-12-13 17:41:01.319
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
Disconnected from the target VM, address: '127.0.0.1:53709', transport: 'socket'

Process finished with exit code 0

```

**Comment by Amor7527** [comment]
`
{
    server: {
        serverPort: 8978,

        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        sslConfigurationPath:"${CLOUDBEAVER_SSL_CONF_PATH:workspace/.data/ssl-config.xml}",

        rootURI: "/",
        serviceURI: "/api/",

        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 1800000,

        develMode: false,

        enableSecurityManager: false,

        database: {
            driver: "postgres-jdbc",
            url: "jdbc:postgresql://192.168.1.1:9527/postgres",
            user: "amor",
            password:"111",
            initialDataConfiguration: "conf/initial-data.conf",
            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

    },
    app: {
        anonymousAccessEnabled: true,
        anonymousUserRole: "user",
        grantConnectionsAccessToAnonymousTeam: false,
        supportsCustomConnections: false,
        showReadOnlyConnectionInfo: false,

        forwardProxy: false,

        publicCredentialsSaveEnabled: true,
        adminCredentialsSaveEnabled: true,

        resourceManagerEnabled: true,

        resourceQuotas: {
            dataExportFileSizeLimit: 10000000,
            resourceManagerFileSizeLimit: 500000,
            sqlMaxRunningQueries: 100,
            sqlResultSetRowsLimit: 100000,
            sqlResultSetMemoryLimit: 2000000,
            sqlTextPreviewMaxLength: 4096,
            sqlBinaryPreviewMaxLength: 261120
        },
        enabledAuthProviders: [
            "local"
        ],

        disabledDrivers: [
            "sqlite:sqlite_jdbc",
            "h2:h2_embedded",
            "h2:h2_embedded_v2",
            "clickhouse:yandex_clickhouse"
        ]

    }

}

`

**Comment by Amor7527** [comment]
version ： dev

**Comment by Amor7527** [comment]
I can start it through a script, but there will be an error that the driver cannot be found in ECLIPSE. Only these four drivers can be found in the dataSourceProviderRegistry, respectively.
0 = {DataSourceProviderDescriptor@4593} "db2"
1 = {DataSourceProviderDescriptor@4594} "exasol"
2 = {DataSourceProviderDescriptor@4595} "mysql"
3 = {DataSourceProviderDescriptor@4596} "oracle"
<img width="1720" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/32616b44-0043-4f64-bfab-5fa06d0b0458">

<img width="1840" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/a78ff72f-a9ce-4d79-90a1-95049f9afa46">

**Comment by Amor7527** [comment]
Please read my question carefully. I can start it through a script. I have already executed the build.sh script. I can execute run-server.sh to start cloudbeaver. Don't let me execute build.sh or other nonsense.

**Comment by EvgeniaBzzz** [comment]
Hi @Amor7527 
Please, try to copy the 'drivers' folder from the Maven build into the Eclipse folder.

**Comment by Amor7527** [comment]
> 你好@Amor7527 请尝试复制“驱动程序”文件夹从 Maven 构建到 Eclipse 文件夹。
I don’t know where the two folders you are talking about are, but I tried these and it seems to have no effect.

I put this folder under /Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/deploy/cloudbeaver
/driver
s is copied to:/Users/sl/Documents/develop/Project/eclipse/cloudbeaver-start/cloudbeaver/deploy/cloudbeaver/drivers

<img width="937" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/b4f1c165-0fcd-4ba6-a413-5a3680b2b488">


<img width="1728" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/3cc02813-5290-47c1-beca-f6b4565cffa7">

**Comment by Amor7527** [comment]
> Hi @Amor7527 Please, try to copy the 'drivers' folder from the Maven build into the Eclipse folder.

Can you tell me the specific example path?

**Comment by Amor7527** [comment]
<img width="891" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/754b3314-3379-48cb-ac92-c12485ed058d">
<img width="1029" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/16e5b782-10f2-4422-8df0-aafc5365d700">
<img width="1127" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/91579939/14a77cc4-b438-48de-bb0d-846d0621e3be">

**Comment by serge-rider** [comment]
If you run cloudbeaver from Eclipse then you have to have drivers folder in the Eclipse folder. However we didn't test this environment on MacOS.

Did you try to build everything from maven and then run?

**Comment by Amor7527** [comment]
> If you run cloudbeaver from Eclipse then you have to have drivers folder in the Eclipse folder. However we didn't test this environment on MacOS.
> 
> Did you try to build everything from maven and then run?

Hey, can you take a closer look at my screenshot? It is obvious that I have executed the build.sh file and started the project through run-server.sh.

**Comment by yagudin10** [comment]
Hi, @Amor7527!
Can you check if `org.jkiss.dbeaver.ext.postgresql` is activated in Run Configuration?
<img width="828" alt="image" src="https://github.com/dbeaver/cloudbeaver/assets/59531286/7f31f4fe-5602-4645-ae53-60ca50267e3e">

**Comment by EvgeniaBzzz** [comment]
It has been some time since our last communication on this matter.
Please let us know and provide additional information.
