### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#2220]
when i builded cloudbeaver,then start has some error.
Server Error: Validation error (FieldUndefined@[serverConfig/defaultUserTeam]) : Field 'defaultUserTeam' in type 'ServerConfig' is undefined
Server Error: Validation error (FieldUndefined@[serverConfig/defaultUserTeam]) : Field 'defaultUserTeam' in type 'ServerConfig' is undefined
    at CustomGraphQLClient.overrideRequest (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:292845)
    at async NetworkStateService.sessionExpiredInterceptor (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:265896)
    at async SessionExpireService.sessionExpiredInterceptor (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:279736)
    at async ServerConfigResource.loader (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:272734)
    at async ServerConfigResource.loadingTask (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:249866)
    at async ServerConfigResource.taskWrapper (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:249954)
    at async Task.task (http://localhost:8978/index.f71571692dd1e3b7b47d.js:2:249552)
![image](https://github.com/dbeaver/cloudbeaver/assets/43168824/2f88990b-25fe-4cf6-a8a3-2b3584548963)

the version is 23.1.0

**Comment by EvgeniaBzzz** [comment]
Hi @ccczhouxin!
Please, try to start server on the browser page in incognito mode. Will the error happen again?

**Comment by ccczhouxin** [comment]
> Hi @ccczhouxin! Please, try to start server on the browser page in incognito mode. Will the error happen again?

that is ok.thank you

**Comment by EvgeniaBzzz** [comment]
So you just had a cache issue.
Thank you for being with CloudBeaver!
