### ISSUE TITLE
Clickhouse query Error: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by MapleOfLeaf** [dbeaver/cloudbeaver#248]
Hi:
Thank you for opening up this tool, but I have some problems.
Problems Detail:
Database clickhouse: Cannot query when the table contains array.
current cloudbeaver version: 1.2.0 
Error Info:
2020-12-21 16:30:41.501 - /dbeaver/gql
java.lang.StackOverflowError
        at java.lang.StringBuffer.append(StringBuffer.java:270)
        at java.io.StringWriter.write(StringWriter.java:101)
        at com.google.gson.stream.JsonWriter.newline(JsonWriter.java:601)
        at com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:618)
        at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
        at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:307)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:238)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)

![1608539767(1)](https://user-images.githubusercontent.com/15613004/102756327-a82db080-43aa-11eb-8f78-6e9b425c330e.jpg)

**Comment by MapleOfLeaf** [comment]
The specific array type is  :  Array(Decimal(10,2)) 
web result detail: 
Tasks execution returns no result

**Comment by MapleOfLeaf** [comment]
Use the following sql ：
select * from crm_order_tags_data array join order_detail limit 10;
