### ISSUE TITLE
Results 'XX' not found in context XXXX@XXXX

### ISSUE THREAD

**Issue by niklasweimann** [dbeaver/cloudbeaver#2789]
**Describe the bug**
Scrolling fast in the result window in the SQL Editor results in an exception.

**To Reproduce**
1. Open SQL Editor
2. Execute a simple SQL Query which results in a Dataset that needs multiple pages
3. Scroll super fast (Using an Logitech MX Master Mouse in endless mode)
4. Now it will happen that the scrolling triggers a new query before the previous query result arrives at the client and this error appears.  

**Screenshots**
![Screenshot 2024-07-18 at 14 43 02](https://github.com/user-attachments/assets/cb765b64-de24-49c9-ac92-ee834c310cd7)

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Firefox, Chrome
- Version:
  - Backend version: 24.1.2.202407080859
  - Frontend version: 24.1.2.202407080902

**Additional context**
```
Error executing query:
Results '14' not found in context 'postgres-jdbc-18e333d51d6-521bc749a9e5e587:1'@'postgres-jdbc-18e333d51d6-521bc749a9e5e587'

Error executing query:
Results '14' not found in context 'postgres-jdbc-18e333d51d6-521bc749a9e5e587:1'@'postgres-jdbc-18e333d51d6-521bc749a9e5e587'
io.cloudbeaver.DBWebException: Error executing query:
Results '14' not found in context 'postgres-jdbc-18e333d51d6-521bc749a9e5e587:1'@'postgres-jdbc-18e333d51d6-521bc749a9e5e587'
	at io.cloudbeaver.service.sql.WebSQLProcessor.processQuery(WebSQLProcessor.java:264)
	at io.cloudbeaver.service.sql.impl.WebServiceSQL$1.run(WebServiceSQL.java:411)
	at io.cloudbeaver.model.session.WebSession$1.run(WebSession.java:742)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: io.cloudbeaver.DBWebException: Results '14' not found in context 'postgres-jdbc-18e333d51d6-521bc749a9e5e587:1'@'postgres-jdbc-18e333d51d6-521bc749a9e5e587'
	at io.cloudbeaver.service.sql.WebSQLContextInfo.getResults(WebSQLContextInfo.java:169)
	at io.cloudbeaver.service.sql.WebSQLProcessor.processQuery(WebSQLProcessor.java:180)
	... 4 more
```

**Comment by EvgeniaBzzz** [comment]
Hi @niklasweimann 
Thank you for reporting!
It's a known issue, the fix will be available in v.24.1.3 (on Monday)

**Comment by EvgeniaBzzz** [comment]
@niklasweimann you can find a fix in v.24.1.3.
Thank you for being with CloudBeaver!

**Comment by niklasweimann** [comment]
Thank you for informing me. I can confirm that the bug is fixed.
