### ISSUE TITLE
SQL Error [S1000]: arraycopy: last source index 128 out of bounds for byte[108]

### ISSUE THREAD

**Issue by kevinlin299** [dbeaver/cloudbeaver#2816]
**Describe the bug**

**To Reproduce**
1. Go to sql editor and wrtie the sql script then run then sql script,i want export the result data,it such so long time to export,
2.  run then sql script
3. export the result data,it such so long time to export

**Screenshots**

**Desktop (please complete the following information):**
 - OS:window
 - Browser chrome, safari
 - Version :Current: 24.0.4

**Additional context**
Add any other context about the problem here, e.g. error log.

SQL Error [S1000]: arraycopy: last source index 128 out of bounds for byte[108]
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [S1000]: arraycopy: last source index 128 out of bounds for byte[108]
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
        at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:134)
        at io.cloudbeaver.service.sql.WebSQLQueryDataContainer.readData(WebSQLQueryDataContainer.java:107)
        at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:270)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
        at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:187)
        at io.cloudbeaver.service.data.transfer.impl.WebServiceDataTransfer.exportData(WebServiceDataTransfer.java:332)
        at io.cloudbeaver.service.data.transfer.impl.WebServiceDataTransfer$1.run(WebServiceDataTransfer.java:186)
        at io.cloudbeaver.model.session.WebSession$1.run(WebSession.java:742)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: arraycopy: last source index 128 out of bounds for byte[108]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:767)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:652)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
        ... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 128 out of bounds for byte[108]
        at java.base/java.lang.System.arraycopy(Native Method)
        at com.mysql.cj.protocol.a.NativePacketPayload.readBytes(NativePacketPayload.java:576)
        at com.mysql.cj.protocol.a.NativePacketPayload.readBytes(NativePacketPayload.java:525)
        at com.mysql.cj.protocol.a.TextRowFactory.createFromMessage(TextRowFactory.java:65)
        at com.mysql.cj.protocol.a.TextRowFactory.createFromMessage(TextRowFactory.java:42)
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:87)
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1648)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:86)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1661)
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1713)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1063)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:658)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:727)
        ... 13 more

**Comment by LonwoLonwo** [comment]
Hello @linguibin 

It would be beneficial to include a video demonstrating your actions.
For now, I can't reproduce your issue.

**Comment by kevinlin299** [comment]
As the execution of the script takes a long time, I feedback by screenshot, the script is with syntax or select syntax but join lot of table , about 600 lines, the amount of data is about 200000, can be exported using other clients
![企业微信截图_17225072849666](https://github.com/user-attachments/assets/805cee73-221f-47f1-85f3-ce079ddc660e)
![企业微信截图_17225073121865](https://github.com/user-attachments/assets/828c1dbf-cd0d-4a40-9676-2fcffa3b7de3)
![企业微信截图_1722507325766](https://github.com/user-attachments/assets/324f6957-96a2-4bde-bacc-4f958f9cefb9)
![image](https://github.com/user-attachments/assets/7e4828da-9d5a-4cf4-8401-763900f775a1)

**Comment by DenisSinelnikov** [comment]
Hi, @kevinlin299 

I wasn't able to reproduce the issue on my end. It might be worth checking if your database data is corrupted, as that could potentially be causing the error.

If everything is okay with the database, could you please provide details on which database you are using, along with the driver and its version? What data format do you use in your columns? Additionally, if you try exporting the data in a different format, do you encounter the same issue?

**Comment by EvgeniaBzzz** [comment]
Hi @kevinlin299 
Any news here?

**Comment by EvgeniaBzzz** [comment]
It’s been a while since an update here. Please feel free to ask to reopen the ticket if it is still actual for you.
