### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jetbinliu** [dbeaver/cloudbeaver#29]
use command:java -jar /opt/src/dbeaver/product/appstore/target/products/org.jkiss.dbeaver.core.appstore/linux/gtk/x86_64/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar  -data ./workspace -web-config ./conf/cloudbeaver.conf -nl en -registryMultiLanguage -vmargs -Xmx2048M

but failed，thank you!!!

[root@ops-codis-node-2 deploy]# java -jar /opt/src/dbeaver/product/appstore/target/products/org.jkiss.dbeaver.core.appstore/linux/gtk/x86_64/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar  -data ./workspace -web-config ./conf/cloudbeaver.conf -nl en -registryMultiLanguage -vmargs -Xmx2048M
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.0.4.202004300704]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
2020-04-30 17:15:15.054 - Error parsing command line: Unrecognized option: -web-config
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.0.4.202004300704]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-04-30 17:15:15.214 - Initializing DBeaver 7.0.4
2020-04-30 17:15:15.214 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.0.4.202004300704
2020-04-30 17:15:15.215 - Initialize Core...
2020-04-30 17:15:15.216 - Can't find BC security provider. Use default JCE.
2020-04-30 17:15:15.216 - BouncyCastle not registered, using the default JCE provider

	Refreshing workspace.
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
Refreshing workspace contents
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
2020-04-30 17:15:15.360 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.32.202004300704]
2020-04-30 17:15:15.388 - Core initialized (173ms)
2020-04-30 17:15:15.389 - Create display
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1130)
	at org.eclipse.swt.widgets.Display.create(Display.java:1070)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:636)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:627)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:776)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:166)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:404)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:330)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:205)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Error updating splash shell
2020-04-30 17:15:15.416 - DBeaver 7.0.4.202004300704 is starting
2020-04-30 17:15:15.417 - OS: Linux 3.10.0-693.el7.x86_64 (amd64)
2020-04-30 17:15:15.417 - Java version: 14.0.1 by Oracle Corporation (64bit)
2020-04-30 17:15:15.417 - Install path: '/opt/src/dbeaver/product/appstore/target/products/org.jkiss.dbeaver.core.appstore/linux/gtk/x86_64'
2020-04-30 17:15:15.417 - Instance path: 'file:/opt/src/cloudbeaver/deploy/workspace/'
2020-04-30 17:15:15.417 - Memory available 506Mb/8004Mb
2020-04-30 17:15:15.426 - Starting RMI server at 50425
2020-04-30 17:15:15.602 - Run workbench
2020-04-30 17:15:15.602 - Create display
2020-04-30 17:15:15.602 - Internal error in workbench lifecycle
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1130)
	at org.eclipse.swt.widgets.Display.create(Display.java:1070)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:636)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:627)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:776)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:166)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:404)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:232)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-04-30 17:15:15.604 - DBeaver is stopping
2020-04-30 17:15:15.605 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.47.202004300704]
2020-04-30 17:15:15.687 - org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1130)
	at org.eclipse.swt.widgets.Display.create(Display.java:1070)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:636)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:627)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:2282)
	at org.jkiss.dbeaver.ui.UIUtils.getDisplay(UIUtils.java:1736)
	at org.jkiss.dbeaver.ui.UIUtils.asyncExec(UIUtils.java:1742)
	at org.jkiss.dbeaver.core.DBeaverUI.initialize(DBeaverUI.java:135)
	at org.jkiss.dbeaver.core.DBeaverUI.getInstance(DBeaverUI.java:95)
	at org.jkiss.dbeaver.core.DBeaverCoreAdapterFactory.getAdapter(DBeaverCoreAdapterFactory.java:54)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:339)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:366)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:726)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:705)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:720)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatformUI(DBWorkbench.java:66)
	at org.jkiss.dbeaver.utils.RuntimeUtils.runTask(RuntimeUtils.java:225)
	at org.jkiss.dbeaver.utils.RuntimeUtils.runTask(RuntimeUtils.java:190)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.shutdown(DBeaverApplication.java:512)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:258)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-04-30 17:15:15.688 - DBeaver shutdown completed
2020-04-30 17:15:15.712 - Shutdown Core...
2020-04-30 17:15:15.831 - Total database drivers: 81 (81)
2020-04-30 17:15:15.877 - Shutdown completed in 165ms
An error has occurred. See the log file
/opt/src/cloudbeaver/deploy/workspace/.metadata/.log.

**Comment by serge-rider** [comment]
You are trying to start desktop DBeaver. Please ask on dbeaver issue tracker - https://github.com/dbeaver/dbeaver/issues
