### ISSUE TITLE
Run error during first startup

### ISSUE THREAD

**Issue by stogdan** [dbeaver/cloudbeaver#30]
**Describe the bug**
First run attempt after first successful cloudbeaver build

**To Reproduce**
1. Go to 'directory containing artificats' in my case:
`/home/build/cloudbeaver/deploy/cloudbeaver`
2. Attempt to run CB server './run-server.sh'
3. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04 x86-64
 - Version 7.0.4
 - pwd: `/home/build/cloudbeaver/deploy/cloudbeaver`
 - $CLOUDBEAVER_HOME:
`/home/build/cloudbeaver/deploy/cloudbeaver/`

**Error message**
`
Starting Cloudbeaver Server
2020-05-02 11:17:03.400 - Using configuration conf/cloudbeaver.conf
2020-05-02 11:17:03.488 - Product configuration file not found (/home/build/cloudbeaver/deploy/cloudbeaver/conf/product.conf'
2020-05-02 11:17:03.531 - Cloudbeaver Web Server 7.0.4.202005021033 is starting
2020-05-02 11:17:03.532 -       OS: Linux 4.15.0-99-generic (amd64)
2020-05-02 11:17:03.533 -       Java version: 11.0.7 by Ubuntu (64bit)
2020-05-02 11:17:03.535 -       Install path: '/home/build/cloudbeaver/deploy/cloudbeaver/server'
2020-05-02 11:17:03.536 -       Global workspace: 'file:/home/build/cloudbeaver/deploy/cloudbeaver/workspace/'
2020-05-02 11:17:03.537 -       Memory available 30Mb/477Mb
2020-05-02 11:17:03.576 - Initializing product: Cloudbeaver Web Server 7.0.4
2020-05-02 11:17:03.577 - Host plugin: io.cloudbeaver.server 7.0.4.202005021033
2020-05-02 11:17:03.577 - Initialize web platform...
2020-05-02 11:17:03.838 - BounceCastle bundle found. Use JCE provider BC
2020-05-02 11:17:04.192 - Initialize base platform...
2020-05-02 11:17:04.516 - Total database drivers: 80 (80)
2020-05-02 11:17:04.548 - Driver 'derby_server' is missing library 'org.apache.derby:derbyclient:RELEASE'
2020-05-02 11:17:04.555 - Web platform initialized (978ms)
2020-05-02 11:17:04.555 -       Content root: /home/build/cloudbeaver/deploy/cloudbeaver/web
2020-05-02 11:17:04.556 -       Drivers storage: /home/build/cloudbeaver/deploy/cloudbeaver/drivers
2020-05-02 11:17:04.559 -       Product details: CloudBeaver Sample Server
2020-05-02 11:17:04.560 -       Base port: 8978
2020-05-02 11:17:04.561 -       Base URI: /dbeaver/
2020-05-02 11:17:04.568 -       Production mode
2020-05-02 11:17:04.577 - Initializing database connection
2020-05-02 11:17:05.196 - Connected to H2 1.4.196 (2017-06-10)
2020-05-02 11:17:05.209 - Create database schema
2020-05-02 11:17:05.210 - Error initializing database
org.jkiss.dbeaver.DBException: Can't find schema file db/cb-schema-create.sql
        at io.cloudbeaver.server.CBDatabase.createDatabaseSchema(CBDatabase.java:169)
        at io.cloudbeaver.server.CBDatabase.checkDatabaseStructure(CBDatabase.java:146)
        at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:126)
        at io.cloudbeaver.server.CBApplication.initializeDatabase(CBApplication.java:217)
        at io.cloudbeaver.server.CBApplication.start(CBApplication.java:187)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-05-02 11:17:05.231 - Shutdown Core...
2020-05-02 11:17:05.301 - Shutdown completed in 70ms
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
`

**Comments**

1. error: home/build/cloudbeaver/deploy/cloudbeaver/server/conf/product.conf 
2. error: Driver 'derby_server' is missing library 'org.apache.derby:derbyclient:RELEASE'
3. error: org.jkiss.dbeaver.DBException: Can't find schema file db/cb-schema-create.sql

I cannot see the file cb-schema-create.sql in the directory structure. However I see it is located here: /home/build/cloudbeaver/server/bundles/io.cloudbeaver.server/db/cb-schema-create.sql

A missing copy command in the build instructions? If so where should it be placed?

**Comment by serge-rider** [comment]
It is already fixed. Thanks for the bug report though.

`devel ` branch is unstable. Build may fail from time to time.
If you build fro msources then its better to use some release verison: https://github.com/dbeaver/cloudbeaver/releases
