### ISSUE TITLE
NumberFormatException parsing server configuration

### ISSUE THREAD

**Issue by lyonzy** [dbeaver/cloudbeaver#3050]
**Describe the bug**
Somewhere between 24.2.0 and 24.2.1 I've started getting this. I'm not sure what `10.43.112.130` represents but it doesn't seem to be the Pod IP.
```
org.jkiss.dbeaver.DBException: Error parsing server configuration
	at io.cloudbeaver.server.CBServerConfigurationController.loadConfiguration(CBServerConfigurationController.java:121)
	at io.cloudbeaver.server.CBServerConfigurationController.loadServerConfiguration(CBServerConfigurationController.java:91)
	at io.cloudbeaver.model.app.BaseWebApplication.loadServerConfiguration(BaseWebApplication.java:99)
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:203)
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:203)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1434)
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "tcp://10.43.112.130:8978"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:277)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:267)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
	at com.google.gson.Gson.fromJson(Gson.java:1361)
	at com.google.gson.Gson.fromJson(Gson.java:1262)
	at com.google.gson.Gson.fromJson(Gson.java:1171)
	at com.google.gson.Gson.fromJson(Gson.java:1107)
	at io.cloudbeaver.server.CBServerConfigurationController.parseConfiguration(CBServerConfigurationController.java:143)
	at io.cloudbeaver.server.CBServerConfigurationController.loadConfiguration(CBServerConfigurationController.java:119)
	... 17 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "tcp://10.43.112.130:8978"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:651)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1293)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:275)
	... 27 common frames omitted
```

**To Reproduce**
This is enough to reproduce on my end:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver-deployment
  namespace: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver-app
          image: dbeaver/cloudbeaver
          ports:
            - containerPort: 8978
              protocol: TCP
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS:     k3OS v0.24.17-k3s1-r1
 - Version 24.2.1 and later

Logs:

[cloudbeaver-deployment-78d8bfb49c-j8jdl-cloudbeaver-app.log](https://github.com/user-attachments/files/17640415/cloudbeaver-deployment-78d8bfb49c-j8jdl-cloudbeaver-app.log)

**Comment by LonwoLonwo** [comment]
Hello @lyonzy 

Thanks for the report! 
Working on a fix.

**Comment by EvgeniaBzzz** [comment]
As a workaround you can try to change `cloudbeaver` name to any other (like `cloudbeaver1`). Or use the version that worked for you.

**Comment by dariamarutkina** [comment]
Hello @lyonzy!
You can find a fix in v.24.2.5 💙
Thank you for being with CloudBeaver!

**Comment by lyonzy** [comment]
Thanks, 24.2.5 fixes it on my end!
