### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Invalid char ([) found at index (0) in sheet name '[select 1]'

### ISSUE THREAD

**Issue by gdyflxw** [dbeaver/cloudbeaver#3086]
When I export data from SQL Server using the .xlsx format, it raises an error (the error is described below). And I have tried SQL Server, pg (PostgreSQL), and MySQL; only SQL Server raises the error.

org.jkiss.dbeaver.model.exec.DBCException: Error while exporting table row
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:247)
	at io.cloudbeaver.service.data.transfer.impl.WebServiceDataTransfer$3.fetchRow(WebServiceDataTransfer.java:279)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:156)
	at io.cloudbeaver.service.sql.WebSQLQueryDataContainer.readData(WebSQLQueryDataContainer.java:107)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:271)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:188)
	at io.cloudbeaver.service.data.transfer.impl.WebServiceDataTransfer.exportData(WebServiceDataTransfer.java:332)
	at io.cloudbeaver.service.data.transfer.impl.WebServiceDataTransfer$1.run(WebServiceDataTransfer.java:186)
	at io.cloudbeaver.model.session.WebSession$1.run(WebSession.java:567)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Invalid char ([) found at index (0) in sheet name '[select 1]'
	at org.apache.poi.ss.util.WorkbookUtil.validateSheetName(WorkbookUtil.java:150)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:918)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:712)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.createSheet(DataExporterXLSX.java:401)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.getWsh(DataExporterXLSX.java:412)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.exportRow(DataExporterXLSX.java:427)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:242)
	... 11 more

**Comment by dariamarutkina** [comment]
@gdyflxw thank you for the report!
We've reproduced the bug. We will fix this in the future.
Thank you for your interest in CloudBeaver!

**Comment by arhayka** [comment]
Related ticket:  https://github.com/dbeaver/dbeaver/issues/36281

**Comment by LonwoLonwo** [comment]
Hello @gdyflxw 
You will find a fix in v.24.3.0 🤗 (release December 02)
Thank you for being with CloudBeaver!
