### ISSUE TITLE
Issue on testing Connection Redshift (Cloudbeaver EE - Trial)

### ISSUE THREAD

**Issue by dng19059** [dbeaver/cloudbeaver#3146]
hello

I use docker images (CloudBeaver **Enterprise Edition)** and and I have this issue when i try to connect to my Redshift
**(for information it's a trial licence)**
Telnet seems to be good when i try to connect to target port Redshift (5439)

org.postgresql.util.PSQLException: Connection attempt timed out.
at org.postgresql.Driver$ConnectThread.getResult(Driver.java:410)
 at org.postgresql.Driver.connect(Driver.java:305)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:214)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:133)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:552)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:124)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:235)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:122)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:269)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:165)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
 at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
 at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:105)
 at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
 at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1395)
 at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1266)
 at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
 at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
 at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
 at io.cloudbeaver.service.core.impl.WebServiceCore.testConnection(WebServiceCore.java:748)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:569)

**Comment by dng19059** [comment]
for information, my telnet to the destination work fine

**Comment by EvgeniaBzzz** [comment]
Hi @dng19059 
I just have successfully connected to Redshift with PostgreSQL driver in Community version.
If you're using right credentials and Redshift instance is running, then please check if the instance has public access.

**Comment by dng19059** [comment]
Many thanks @EvgeniaBzzz , are you specify Redshift (5439) port or Postgres natif port (5432) ?

**Comment by EvgeniaBzzz** [comment]
I specified 5439

**Comment by dng19059** [comment]
Thanks  @EvgeniaBzzz i'm going to try it and i tell You

**Comment by LonwoLonwo** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
