### ISSUE TITLE
Getting Directory Listing Page when Accessing Cloudbeaver

### ISSUE THREAD

**Issue by jkailasam** [dbeaver/cloudbeaver#481]
Hi, 

I followed the instructions  in https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy to compile and install Cloudbeaver.  The cloudbeaver is compiled successfully.  I start the service using "run-server.sh" script. When I access the cloudbeaver using my `ipaddress:8978`, I get a Webserver directly listing page instead of the actual Cloudbeaver.  Have any one experienced this behavior? Please see bellow the screen shot. 

<img width="467" alt="Screen Shot 2021-09-19 at 9 24 35 PM" src="https://user-images.githubusercontent.com/7970242/133957004-6f25c86a-4f08-4134-b149-3ad07e8d1df1.png">

The summary  of  build.sh output: 
```
[INFO] Reactor Summary:
[INFO]
[INFO] dbeaver 1.0.0-SNAPSHOT ............................. SUCCESS [ 16.330 s]
[INFO] bundles 1.0.0-SNAPSHOT ............................. SUCCESS [  0.006 s]
[INFO] org.jkiss.utils 2.1.148-SNAPSHOT ................... SUCCESS [ 13.559 s]
[INFO] org.jkiss.wmi 2.0.158-SNAPSHOT ..................... SUCCESS [  0.742 s]
[INFO] plugins 1.0.0-SNAPSHOT ............................. SUCCESS [  0.011 s]
[INFO] org.jkiss.dbeaver.model 1.0.154-SNAPSHOT ........... SUCCESS [  8.423 s]
[INFO] org.jkiss.dbeaver.model.sql 1.0.55-SNAPSHOT ........ SUCCESS [  1.447 s]
[INFO] org.jkiss.dbeaver.registry 1.0.59-SNAPSHOT ......... SUCCESS [  2.077 s]
[INFO] org.jkiss.dbeaver.cmp.simple 6.0.61-SNAPSHOT ....... SUCCESS [  0.526 s]
[INFO] org.jkiss.dbeaver.erd.model 1.0.25-SNAPSHOT ........ SUCCESS [  0.655 s]
[INFO] org.jkiss.dbeaver.ext.generic 2.3.151-SNAPSHOT ..... SUCCESS [  1.113 s]
[INFO] org.jkiss.dbeaver.ext.athena 1.0.71-SNAPSHOT ....... SUCCESS [  0.487 s]
[INFO] org.jkiss.dbeaver.ext.bigquery 1.0.71-SNAPSHOT ..... SUCCESS [  0.437 s]
[INFO] org.jkiss.dbeaver.ext.clickhouse 1.0.70-SNAPSHOT ... SUCCESS [  0.630 s]
[INFO] org.jkiss.dbeaver.ext.db2 2.1.150-SNAPSHOT ......... SUCCESS [  1.694 s]
[INFO] org.jkiss.dbeaver.ext.db2.zos 1.0.68-SNAPSHOT ...... SUCCESS [  0.500 s]
[INFO] org.jkiss.dbeaver.ext.db2.i 1.0.53-SNAPSHOT ........ SUCCESS [  0.541 s]
[INFO] org.jkiss.dbeaver.ext.derby 1.1.150-SNAPSHOT ....... SUCCESS [  0.472 s]
[INFO] org.jkiss.dbeaver.ext.elasticsearch 1.0.76-SNAPSHOT  SUCCESS [  0.424 s]
[INFO] org.jkiss.dbeaver.data.gis 1.0.89-SNAPSHOT ......... SUCCESS [  0.614 s]
[INFO] org.jkiss.dbeaver.ext.exasol 1.0.123-SNAPSHOT ...... SUCCESS [  1.129 s]
[INFO] org.jkiss.dbeaver.ext.opendistro 1.0.49-SNAPSHOT ... SUCCESS [  0.394 s]
[INFO] org.jkiss.dbeaver.ext.firebird 1.0.166-SNAPSHOT .... SUCCESS [  0.733 s]
[INFO] org.jkiss.dbeaver.tasks.native 1.0.43-SNAPSHOT ..... SUCCESS [  0.429 s]
[INFO] org.jkiss.dbeaver.ext.postgresql 2.1.138-SNAPSHOT .. SUCCESS [  2.066 s]
[INFO] org.jkiss.dbeaver.ext.greenplum 1.0.66-SNAPSHOT .... SUCCESS [  0.692 s]
[INFO] org.jkiss.dbeaver.ext.h2 1.0.120-SNAPSHOT .......... SUCCESS [  0.492 s]
[INFO] org.jkiss.dbeaver.ext.h2gis 1.0.48-SNAPSHOT ........ SUCCESS [  0.286 s]
[INFO] org.jkiss.dbeaver.ext.hana 1.2.43-SNAPSHOT ......... SUCCESS [  0.566 s]
[INFO] org.jkiss.dbeaver.ext.hive 1.0.71-SNAPSHOT ......... SUCCESS [  0.480 s]
[INFO] org.jkiss.dbeaver.ext.hsqldb 1.0.112-SNAPSHOT ...... SUCCESS [  0.426 s]
[INFO] org.jkiss.dbeaver.ext.informix 1.0.156-SNAPSHOT .... SUCCESS [  0.437 s]
[INFO] org.jkiss.dbeaver.ext.mssql 1.0.159-SNAPSHOT ....... SUCCESS [  1.477 s]
[INFO] org.jkiss.dbeaver.ext.mysql 2.1.150-SNAPSHOT ....... SUCCESS [  1.508 s]
[INFO] org.jkiss.dbeaver.ext.netezza 1.0.130-SNAPSHOT ..... SUCCESS [  0.371 s]
[INFO] org.jkiss.dbeaver.ext.oceanbase 1.0.3-SNAPSHOT ..... SUCCESS [  0.894 s]
[INFO] org.jkiss.dbeaver.ext.ocient 1.0.36-SNAPSHOT ....... SUCCESS [  0.409 s]
[INFO] org.jkiss.dbeaver.ext.oracle 2.1.150-SNAPSHOT ...... SUCCESS [  1.273 s]
[INFO] org.jkiss.dbeaver.ext.phoenix 1.0.134-SNAPSHOT ..... SUCCESS [  0.418 s]
[INFO] org.jkiss.dbeaver.ext.snowflake.core 1.0.85-SNAPSHOT SUCCESS [  0.570 s]
[INFO] org.jkiss.dbeaver.ext.spanner 1.0.52-SNAPSHOT ...... SUCCESS [  0.494 s]
[INFO] org.jkiss.dbeaver.ext.sqlite 1.0.114-SNAPSHOT ...... SUCCESS [  0.545 s]
[INFO] org.jkiss.dbeaver.ext.vertica 2.0.95-SNAPSHOT ...... SUCCESS [  0.754 s]
[INFO] org.jkiss.dbeaver.ext.teradata 1.0.133-SNAPSHOT .... SUCCESS [  0.398 s]
[INFO] org.jkiss.dbeaver.ext.kognitio 1.0.49-SNAPSHOT ..... SUCCESS [  0.355 s]
[INFO] org.jkiss.dbeaver.ext.datavirtuality 1.0.15-SNAPSHOT SUCCESS [  0.473 s]
[INFO] org.jkiss.dbeaver.ext.denodo 1.0.11-SNAPSHOT ....... SUCCESS [  0.420 s]
[INFO] org.jkiss.dbeaver.data.transfer 2.0.49-SNAPSHOT .... SUCCESS [  1.047 s]
[INFO] org.jkiss.dbeaver.data.office 1.1.103-SNAPSHOT ..... SUCCESS [  0.693 s]
[INFO] org.jkiss.dbeaver.net.ssh 1.0.86-SNAPSHOT .......... SUCCESS [  0.531 s]
[INFO] org.jkiss.dbeaver.net.ssh.jsch 1.1.75-SNAPSHOT ..... SUCCESS [  0.441 s]
[INFO] org.jkiss.dbeaver.net.ssh.sshj 1.0.86-SNAPSHOT ..... SUCCESS [  0.504 s]
[INFO] org.jkiss.dbeaver.slf4j 2.0.35-SNAPSHOT ............ SUCCESS [  0.455 s]
[INFO] org.jkiss.dbeaver.team.git 1.0.53-SNAPSHOT ......... SUCCESS [  0.104 s]
[INFO] org.jkiss.dbeaver.headless 1.0.5-SNAPSHOT .......... SUCCESS [  0.431 s]
[INFO] org.jkiss.dbeaver.runtime.feature 21.2.1-SNAPSHOT .. SUCCESS [  0.695 s]
[INFO] org.jkiss.dbeaver.db.feature 1.0.56-SNAPSHOT ....... SUCCESS [  1.047 s]
[INFO] org.jkiss.dbeaver.net.sshj.feature 1.0.86-SNAPSHOT . SUCCESS [  0.220 s]
[INFO] features 1.0.0-SNAPSHOT ............................ SUCCESS [  0.020 s]
[INFO] Cloudbeaver 1.0.0-SNAPSHOT ......................... SUCCESS [  0.010 s]
[INFO] bundles 1.0.0-SNAPSHOT ............................. SUCCESS [  0.014 s]
[INFO] io.cloudbeaver.server 21.1.4-SNAPSHOT .............. SUCCESS [  1.661 s]
[INFO] io.cloudbeaver.service.admin 1.0.32-SNAPSHOT ....... SUCCESS [  0.630 s]
[INFO] io.cloudbeaver.service.auth 1.0.32-SNAPSHOT ........ SUCCESS [  0.518 s]
[INFO] io.cloudbeaver.service.metadata 1.0.36-SNAPSHOT .... SUCCESS [  0.406 s]
[INFO] io.cloudbeaver.service.data.transfer 1.0.33-SNAPSHOT SUCCESS [  0.602 s]
[INFO] io.cloudbeaver.resources.drivers.base 1.0.33-SNAPSHOT SUCCESS [  0.141 s]
[INFO] io.cloudbeaver.connect.provider.sample 1.0.36-SNAPSHOT SUCCESS [  0.503 s]
[INFO] io.cloudbeaver.product.ce 21.1.4-SNAPSHOT .......... SUCCESS [  0.415 s]
[INFO] features 1.0.0-SNAPSHOT ............................ SUCCESS [  0.013 s]
[INFO] io.cloudbeaver.server.feature 21.1.4-SNAPSHOT ...... SUCCESS [  0.536 s]
[INFO] io.cloudbeaver.ce.drivers.feature 1.0.56-SNAPSHOT .. SUCCESS [  0.107 s]
[INFO] io.cloudbeaver.sample.feature 1.0.36-SNAPSHOT ...... SUCCESS [  0.133 s]
[INFO] io.cloudbeaver.product.ce.feature 21.1.4-SNAPSHOT .. SUCCESS [  0.357 s]
[INFO] drivers 1.0.0 ...................................... SUCCESS [ 17.715 s]
[INFO] drivers.clickhouse 1.0.0 ........................... SUCCESS [  7.739 s]
[INFO] drivers.db2 1.0.0 .................................. SUCCESS [  0.595 s]
[INFO] drivers.derby 1.0.0 ................................ SUCCESS [  1.123 s]
[INFO] drivers.h2 1.0.0 ................................... SUCCESS [  0.325 s]
[INFO] drivers.firebird 1.0.0 ............................. SUCCESS [  0.743 s]
[INFO] drivers.mysql 1.0.0 ................................ SUCCESS [  0.517 s]
[INFO] drivers.mariadb 1.0.0 .............................. SUCCESS [  0.269 s]
[INFO] drivers.oracle 1.0.0 ............................... SUCCESS [  1.605 s]
[INFO] drivers.postgresql 1.0.0 ........................... SUCCESS [  1.415 s]
[INFO] drivers.sqlite 1.0.0 ............................... SUCCESS [  0.447 s]
[INFO] drivers.sqlserver 1.0.0 ............................ SUCCESS [  0.296 s]
[INFO] drivers.trino 1.0.0 ................................ SUCCESS [  1.221 s]
[INFO] Cloudbeaver Server Product 21.1.4-SNAPSHOT ......... SUCCESS [  5.880 s]
[INFO] Cloudbeaver Provided Sample Product 21.1.4-SNAPSHOT  SUCCESS [  4.820 s]
[INFO] product 1.0.0-SNAPSHOT ............................. SUCCESS [  0.004 s]
[INFO] CloudBeaver CE Aggregate 1.0.0-SNAPSHOT ............ SUCCESS [  0.007 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:06 min
[INFO] Finished at: 2021-09-20T04:10:54Z
[INFO] ------------------------------------------------------------------------
```

The cloudbeaver startup script output:

```
# ./run-server.sh
Starting Cloudbeaver Server
2021-09-20 04:11:22.844 - Using configuration [conf/cloudbeaver.conf]
2021-09-20 04:11:22.935 - Load product configuration from '/root/cloudbeaver-dev/cloudbeaver/deploy/cloudbeaver/conf/product.conf'
2021-09-20 04:11:22.937 - Error reading product configuration
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 34 column 2 path $.
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.parseMap(JSONUtils.java:269)
	at io.cloudbeaver.server.CBApplication.parseConfiguration(CBApplication.java:506)
	at io.cloudbeaver.server.CBApplication.loadConfiguration(CBApplication.java:429)
	at io.cloudbeaver.server.CBApplication.start(CBApplication.java:180)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 34 column 2 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:506)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 18 more
2021-09-20 04:11:22.957 - CloudBeaver CE Server 21.1.4.202109200403 is starting
2021-09-20 04:11:22.958 - 	OS: Linux 5.4.0-1045-aws (amd64)
2021-09-20 04:11:22.958 - 	Java version: 11.0.11 by Ubuntu (64bit)
2021-09-20 04:11:22.959 - 	Install path: '/root/cloudbeaver-dev/cloudbeaver/deploy/cloudbeaver/server'
2021-09-20 04:11:22.960 - 	Global workspace: 'file:/root/cloudbeaver-dev/cloudbeaver/deploy/cloudbeaver/workspace/'
2021-09-20 04:11:22.960 - 	Memory available 159Mb/1972Mb
2021-09-20 04:11:23.002 - Initializing product: CloudBeaver CE Server 21.1.4
2021-09-20 04:11:23.002 - Host plugin: io.cloudbeaver.product.ce 21.1.4.202109200403
2021-09-20 04:11:23.003 - Initialize web platform...
2021-09-20 04:11:23.159 - BounceCastle bundle found. Use JCE provider BC

	Refreshing workspace.
Refreshing workspace contents
2021-09-20 04:11:23.399 - Initialize base platform...
2021-09-20 04:11:23.711 - Total database drivers: 90 (90)
2021-09-20 04:11:23.720 - Available drivers: ClickHouse,DB2 LUW,Firebird,H2 Embedded,Derby Server,Trino,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
2021-09-20 04:11:23.728 - Web platform initialized (725ms)
2021-09-20 04:11:23.729 - 	Content root: /root/cloudbeaver-dev/cloudbeaver/deploy/cloudbeaver/web
2021-09-20 04:11:23.729 - 	Drivers storage: /root/cloudbeaver-dev/cloudbeaver/deploy/cloudbeaver/drivers
2021-09-20 04:11:23.729 - 	Base port: 8978
2021-09-20 04:11:23.729 - 	Base URI: /api/
2021-09-20 04:11:23.730 - 	Production mode
2021-09-20 04:11:23.730 - 	Server is in configuration mode!
2021-09-20 04:11:23.736 - 	Local host addresses:
2021-09-20 04:11:23.742 - 		10.175.159.147 (spdpaa0909-usw2.aws.science.roche.com)
2021-09-20 04:11:23.743 - 		0:0:0:0:0:0:0:1%lo (ip6-localhost)
2021-09-20 04:11:23.822 - Initializing database connection
2021-09-20 04:11:24.311 - Connected to H2 1.4.199 (2019-03-13)
2021-09-20 04:11:24.324 - Create database schema
2021-09-20 04:11:24.528 - Auth provider 'local' registered
2021-09-20 04:11:24.532 - No auto configuration was found. Server must be configured manually
2021-09-20 04:11:24.539 - Starting Jetty server (8978)
2021-09-20 04:11:25.086 - Schema extensions loaded: WebServiceBindingCore,WebServiceBindingNavigator,WebServiceBindingSQL,WebServiceBindingAdmin,WebServiceBindingAuth,WebServiceBindingDataTransfer,WebServiceBindingMetadata
2021-09-20 04:11:25.651 - Active servlets:
2021-09-20 04:11:25.651 - 	static: [/*]
2021-09-20 04:11:25.652 - 	images: [/api/images/*]
2021-09-20 04:11:25.652 - 	graphql: [/api/gql/*]
2021-09-20 04:11:25.652 - 	sqlResultValueViewer: [/api/sql-result-value/*]
2021-09-20 04:11:25.652 - 	adminLogs: [/api/logs/*]
2021-09-20 04:11:25.653 - 	dataTransfer: [/api/data/*]
2021-09-20 04:11:25.655 - jetty-{}; built: {}; git: {}; jvm {}
2021-09-20 04:11:25.729 - Session workerName={}
2021-09-20 04:11:25.765 - Started {}
2021-09-20 04:11:25.777 - Started {}
2021-09-20 04:11:25.778 - Started Server@6bedd4e4{STARTING}[10.0.5,sto=0] @6577ms
```

Any help is greatly appriciated.

thanks,

**Comment by serge-rider** [comment]
Problem was caused by malformed product.conf file.
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
The fix will be available in 21.1.5 release.

**Comment by jkailasam** [comment]
This problem was I was using the wrong yarn version and the web components were not compiled.  I have to remove the old yarn using ` apt remove cmdtest` command in ubuntu and install yarn again.

After reinstalling yarn, the cloudbeaver is working as expected.

thanks,

**Comment by kseniiaguzeeva** [comment]
Could you please try the latest release https://github.com/dbeaver/cloudbeaver?
