### ISSUE TITLE
not nunning in eclipse

### ISSUE THREAD

**Issue by pangbin0502** [dbeaver/cloudbeaver#630]
branch：devel
java-version：11.0.10

**I run cloudbeaver in eclipse，have a error，cann't find drivers，but I run rn-server.sh success**

!SESSION 2022-01-24 11:55:17.223 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.10
java.vendor=Red Hat, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\workspace -dev file:D:/workspace3/dbeaver-ce/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.eclipse.m2e.core.ui 4 0 2022-01-24 11:55:22.802
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.core.ui [137]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.20211002-1029"; singleton:="true"
       org.eclipse.m2e.model.edit [142]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.400.v202107272335"; singleton:="true"
              org.eclipse.wst.xml.core [176]
                Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.1,3.0.0)"; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.m2e.model.edit 4 0 2022-01-24 11:55:22.810
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.model.edit [142]
  Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.400.v202107272335"; singleton:="true"
       org.eclipse.wst.xml.core [176]
         Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.1,3.0.0)"; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.wst.xml.core 4 0 2022-01-24 11:55:22.813
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wst.xml.core [176]
  Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.1,3.0.0)"; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
2022-01-24 10:22:37.183 - Using configuration [conf/cloudbeaver.conf]
2022-01-24 10:22:37.288 - Load product configuration from 'D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\conf\product.conf'
2022-01-24 10:22:37.352 - CloudBeaver CE Server 21.3.3.qualifier is starting
2022-01-24 10:22:37.352 - 	OS: Windows 10 10.0 (amd64)
2022-01-24 10:22:37.352 - 	Java version: 11.0.10 by Red Hat, Inc. (64bit)
2022-01-24 10:22:37.354 - 	Install path: 'D:\Users\pangbin\eclipse\jee-2021-12\eclipse'
2022-01-24 10:22:37.355 - 	Global workspace: 'file:/D:/workspace3/dbeaver-ce/cloudbeaver/deploy/cloudbeaver/workspace/'
2022-01-24 10:22:37.355 - 	Memory available 48Mb/512Mb
2022-01-24 10:22:37.376 - Initializing product: CloudBeaver CE Server 21.3.3
2022-01-24 10:22:55.220 - Host plugin: io.cloudbeaver.product.ce 21.3.3.qualifier
2022-01-24 10:22:55.220 - Initialize web platform...

!ENTRY org.jkiss.dbeaver.model 1 0 2022-01-24 10:22:55.220
!MESSAGE Initialize web platform...
2022-01-24 10:22:55.393 - BounceCastle bundle found. Use JCE provider BC
2022-01-24 10:22:57.582 - Initialize base platform...
2022-01-24 10:28:27.155 - Total database drivers: 0 (0)
2022-01-24 10:28:27.181 - Available drivers: 

!ENTRY org.jkiss.dbeaver.model 1 0 2022-01-24 10:28:27.182
!MESSAGE Available drivers: 
2022-01-24 10:28:27.198 - Web platform initialized (331978ms)

!ENTRY org.jkiss.dbeaver.model 1 0 2022-01-24 10:28:27.199
!MESSAGE Web platform initialized (331978ms)
2022-01-24 10:28:27.200 - 	Content root: D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\web
2022-01-24 10:28:27.200 - 	Drivers storage: D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\drivers
2022-01-24 10:28:27.200 - 	Base port: 8979
2022-01-24 10:28:27.200 - 	Base URI: /api/
2022-01-24 10:28:27.200 - 	Production mode
2022-01-24 10:28:27.200 - 	Server is in configuration mode!
2022-01-24 10:28:27.201 - 	Run in Docker container (host.docker.internal/10.72.139.141)?
2022-01-24 10:28:28.232 - 	Local host addresses:
2022-01-24 10:28:28.232 - 		10.72.139.141 (host.docker.internal)
2022-01-24 10:28:28.233 - 		127.0.0.1 (127.0.0.1)
2022-01-24 10:28:28.234 - 		10.202.52.168 (pangbin00.home.langchao.com)
2022-01-24 10:28:28.234 - 		2.0.0.1 (pangbin00.home.langchao.com)
2022-01-24 10:28:28.235 - 		172.29.176.1 (pangbin00.mshome.net)
2022-01-24 10:28:28.321 - Initiate management database
2022-01-24 10:36:25.688 - Error initializing database
org.jkiss.dbeaver.DBException: Driver 'h2_embedded' not found
	at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:127)
	at io.cloudbeaver.server.CBApplication.initializeDatabase(CBApplication.java:421)
	at io.cloudbeaver.server.CBApplication.start(CBApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-01-24 10:36:25.692
!MESSAGE Error initializing database
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-01-24 10:36:25.692
!MESSAGE Driver 'h2_embedded' not found
!STACK 0
org.jkiss.dbeaver.DBException: Driver 'h2_embedded' not found
	at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:127)
	at io.cloudbeaver.server.CBApplication.initializeDatabase(CBApplication.java:421)
	at io.cloudbeaver.server.CBApplication.start(CBApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
2022-01-24 10:36:25.704 - Shutdown Core...
2022-01-24 10:36:25.774 - Shutdown completed in 70ms

!ENTRY org.eclipse.core.jobs 2 2 Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
2022-01-24 10:36:26.877
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
[0x7FF86D1BE0A4] ANOMALY: use of REX.w is meaningless (default operand size is 64)

**Comment by pangbin0502** [comment]
**this is log of running rn-server.sh success:**

$ ./run-server.sh
Starting Cloudbeaver Server
2022-01-22 10:57:26.819 - Using configuration [conf/cloudbeaver.conf]
2022-01-22 10:57:26.989 - Load product configuration from 'D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\conf\product.conf'
2022-01-22 10:57:27.012 - CloudBeaver CE Server 21.3.3.202201211003 is starting
2022-01-22 10:57:27.012 -       OS: Windows 10 10.0 (amd64)
2022-01-22 10:57:27.012 -       Java version: 11.0.10 by Red Hat, Inc. (64bit)
2022-01-22 10:57:27.013 -       Install path: 'D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\server'
2022-01-22 10:57:27.013 -       Global workspace: 'file:/D:/workspace3/dbeaver-ce/cloudbeaver/deploy/cloudbeaver/workspace/'
2022-01-22 10:57:27.014 -       Memory available 254Mb/4064Mb
2022-01-22 10:57:27.025 - Initializing product: CloudBeaver CE Server 21.3.3
2022-01-22 10:57:27.025 - Host plugin: io.cloudbeaver.product.ce 21.3.3.202201211003
2022-01-22 10:57:27.025 - Initialize web platform...
2022-01-22 10:57:27.233 - BounceCastle bundle found. Use JCE provider BC
2022-01-22 10:57:27.506 - Initialize base platform...
2022-01-22 10:57:27.676 - Total database drivers: 93 (93)
2022-01-22 10:57:27.684 - Available drivers: ClickHouse,DB2 LUW,DB2 iSeries/AS 400,Firebird,H2 Embedded,Derby Server,Trino,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
2022-01-22 10:57:27.835 - Web platform initialized (810ms)
2022-01-22 10:57:27.836 -       Content root: D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\web
2022-01-22 10:57:27.836 -       Drivers storage: D:\workspace3\dbeaver-ce\cloudbeaver\deploy\cloudbeaver\drivers
2022-01-22 10:57:27.836 -       Base port: 8979
2022-01-22 10:57:27.836 -       Base URI: /api/
2022-01-22 10:57:27.836 -       Production mode
2022-01-22 10:57:27.836 -       Server is in configuration mode!
2022-01-22 10:57:27.837 -       Run in Docker container (host.docker.internal/10.72.139.141)?
2022-01-22 10:57:28.689 -       Local host addresses:
2022-01-22 10:57:28.689 -               10.72.139.141 (host.docker.internal)
2022-01-22 10:57:28.691 -               127.0.0.1 (127.0.0.1)
2022-01-22 10:57:28.691 -               192.168.31.197 (pangbin00.home.langchao.com)
2022-01-22 10:57:28.691 -               2.0.0.1 (pangbin00.home.langchao.com)
2022-01-22 10:57:28.691 -               172.29.176.1 (pangbin00.mshome.net)
2022-01-22 10:57:28.890 - Initiate management database
2022-01-22 10:57:29.005 -       Initiate connection pool with management database (H2 Embedded; jdbc:h2:D:/workspace3/dbeaver-ce/cloudbeaver/deploy/cloudbeaver/workspace/.data/cb.h2.dat)
2022-01-22 10:57:29.577 -       Connected to H2 1.4.199 (2019-03-13)
2022-01-22 10:57:31.350 -       Management database connection established
2022-01-22 10:57:31.356 - No auto configuration was found. Server must be configured manually
2022-01-22 10:57:31.357 - Starting Jetty server (8979)
2022-01-22 10:57:31.961 - Schema extensions loaded: WebServiceBindingCore,WebServiceBindingNavigator,WebServiceBindingSQL,WebServiceBindingAdmin,WebServiceBindingAuth,WebServiceBindingDataTransfer,WebServiceBindingMetadata
2022-01-22 10:57:32.216 - Active servlets:
2022-01-22 10:57:32.216 -       static: [/*]
2022-01-22 10:57:32.216 -       status: [/status]
2022-01-22 10:57:32.216 -       images: [/api/images/*]
2022-01-22 10:57:32.216 -       graphql: [/api/gql/*]
2022-01-22 10:57:32.216 -       sqlResultValueViewer: [/api/sql-result-value/*]
2022-01-22 10:57:32.216 -       adminLogs: [/api/logs/*]
2022-01-22 10:57:32.216 -       dataTransfer: [/api/data/*]
2022-01-22 10:57:32.218 - jetty-{}; built: {}; git: {}; jvm {}
2022-01-22 10:57:32.344 - Session workerName={}
2022-01-22 10:57:32.384 - Started {}
2022-01-22 10:57:32.418 - Started {}
2022-01-22 10:57:32.420 - Started Server@4bc6da03{STARTING}[10.0.6,sto=0] @8528ms






Total database drivers: 0 (0)

**Comment by alexander-skoblikov** [comment]
Hi, after building project with the [build.sh](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy#build-and-deploy) script,  you will have a `drivers` folder in `cloudbeaver/deploy/cloudbeaver`. Can you copy and paste it into the folder that you specified as "Working directory" in eclipse run configuration?

**Comment by kseniiaguzeeva** [comment]
Please feel free to contact me to reopen the ticket, if any questions still exist.
