### ISSUE TITLE
After importing the project in eclipse, debug reports an error

### ISSUE THREAD

**Issue by yunkuotianxian** [dbeaver/cloudbeaver#947]
Import the project according to the content in "develop in eclipse" and debug it. The errors are as follows（The detailed error reporting log is in log_info.txt file）:
![image](https://user-images.githubusercontent.com/18697373/176883274-acfe1f80-d341-43f5-8e0d-97542f2bb234.png)
![image](https://user-images.githubusercontent.com/18697373/176883887-4b8a37e6-eadd-4d0d-855f-e5ac5f0597cb.png)
![image](https://user-images.githubusercontent.com/18697373/176884050-925499a8-b617-4c64-b6b9-6809e70a96ea.png)
![image](https://user-images.githubusercontent.com/18697373/176884134-8f9d9157-9d4f-46bd-ac7a-ed9aa3b14060.png)

[log_info.txt](https://github.com/dbeaver/cloudbeaver/files/9028390/log_info.txt)

**Comment by yagudin10** [comment]
Hi @yunkuotianxian,

Try to deselect "org.jkiss.dbeaver.slf4j" plug-in from your configuration file.
![image](https://user-images.githubusercontent.com/59531286/178738923-94a20d81-d010-48e1-8e39-467b518bcaf4.png)

**Comment by yunkuotianxian** [comment]
@yagudin10 ，I cancel the selection and report an error without "unresolved requirement: import package: org.slf4j"

org.osgi.framework.BundleException: Could not resolve module: io.cloudbeaver.model [10]
  Unresolved requirement: Import-Package: org.slf4j

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
!ENTRY io.cloudbeaver.product.ce 4 0 2022-07-17 21:33:23.299
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.cloudbeaver.product.ce [11]
  Unresolved requirement: Require-Bundle: io.cloudbeaver.server
    -> Bundle-SymbolicName: io.cloudbeaver.server; bundle-version="22.1.1.qualifier"; singleton:="true"
       io.cloudbeaver.server [13]
         Unresolved requirement: Import-Package: org.slf4j

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by yagudin10** [comment]
@yunkuotianxian,
You should try to select "org.slf4j.api" plug-in to your configuration file.

**Comment by yunkuotianxian** [comment]
"Org.slf4j.api" has always been selected. If I try to uncheck it, I will also report an error. This package is really necessary.
It seems that the content of my initial question has nothing to do with this




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/cloudbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/cloudbeaver] After importing the project in eclipse, debug reports an error (Issue #947)





 
@yunkuotianxian,
 You should try to select "org.slf4j.api" plug-in to your configuration file.

**Comment by yagudin10** [comment]
Hi @yunkuotianxian ,
Have you tried to validate required plug-ins in your configuration file?

**Comment by yunkuotianxian** [comment]
Can you tell me how to do it in detail? This has bothered me for a long time




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/cloudbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/cloudbeaver] After importing the project in eclipse, debug reports an error (Issue #947)





 
Hi @yunkuotianxian ,
 Have you tried to validate required plug-ins in your configuration file?

**Comment by yagudin10** [comment]
@yunkuotianxian ,
You can find an information about plug-in validation in [this article](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse) (at the bottom)

**Comment by kseniaguzeeva** [comment]
I've noticed that there is no updates during for a long time. Feel free to contact me to reopen the ticket.
