### ISSUE TITLE
Server configuration use mysql database initializing database error

### ISSUE THREAD

**Issue by yxydde** [dbeaver/cloudbeaver#968]
**Server configuration**
        database: {
            url: "jdbc:mysql://x.x.x.x:3306/cloudbeaver",
            driver: "mysql",
            user: "cloudbeaver",
            password: "xxxxxxx",
            initialDataConfiguration: "conf/initial-data.conf",
            pool: {
                minIdleConnections: 4, 
                maxIdleConnections: 10,
                maxConnections: 100,
                validationQuery: "SELECT 1"
            }
        }

**Error info**
07:40:29.431 [main] DEBUG i.c.s.s.internal.db.CBDatabase -      Connected to MySQL 5.7.34
07:40:29.440 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
        at io.cloudbeaver.service.security.internal.db.CBDatabase.initialize(CBDatabase.java:193) ~[na:na]
        at io.cloudbeaver.service.security.SecurityPluginService.createSecurityService(SecurityPluginService.java:68) ~[na:na]
        at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:458) ~[na:na]
        at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:454) ~[na:na]
        at io.cloudbeaver.server.CBApplication.start(CBApplication.java:308) ~[na:na]
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[na:na]
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) ~[na:na]
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) ~[na:na]
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440) ~[org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar:na]
Caused by: org.jkiss.dbeaver.DBException: Can't instantiate class 'org.jkiss.dbeaver.ext.mysql.model.MySQLDialect'
        at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:197) ~[na:na]
        at org.jkiss.dbeaver.model.sql.registry.SQLDialectDescriptor.createInstance(SQLDialectDescriptor.java:161) ~[na:na]
        at io.cloudbeaver.service.security.internal.db.CBDatabase.initialize(CBDatabase.java:185) ~[na:na]
        ... 17 common frames omitted
Caused by: java.lang.IllegalAccessException: class org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType cannot access a member of class org.jkiss.dbeaver.ext.mysql.model.MySQLDialect with modifiers "public"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
        at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:195) ~[na:na]
        ... 19 common frames omitted

**Comment by kseniiaguzeeva** [comment]
It's a bug. Thank you for the report. We are going to fix it.

**Comment by kseniaguzeeva** [comment]
The bug is fixed and available in the latest 22.2.0 release.
