### ISSUE TITLE
Error in all packages in following folders to deploy cloudbeaver in eclipse java

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#988]
Make all the configuration to implement cloudbeaver in eclipse, in the last step it shows me errors in all the packages in the folders
![image](https://user-images.githubusercontent.com/52106718/181395076-6b7e359b-1165-4e14-8d65-356c4df80ec5.png)

i'm using the version release 21.3.3

I base myself on the following guide for the installation https://cloudbeaver.io/docs/Build-and-deploy/ 
since the guide they mention https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse 
it is useless since it only contemplates desktop application for dbeaver
 
Please support me to solve this problem.

Please implement an eclipse cloudbeaver installation guide and don't keep mentioning that it's on the eclipce dbeaver wiki

**Comment by yagudin10** [comment]
Hi @miltonchirinos44,
Try to update all projects (select all projects in project explorer and press Alt+F5) and restart Eclipse IDE.

**Comment by miltonchirinos44** [comment]
guys i still have the same error
![image](https://user-images.githubusercontent.com/52106718/182467307-e3b58e47-78d7-46a8-8b25-82fc8d8e756a.png)

I need your help
I am installing cloud dbeaver in eclipse I am raising the code with the following configurations:
- openjdk 11
- maven 3.6.3
- nodejs v14.19.3
- npm 8.15.0
- yarn 1.22.19
all in windows 10
I followed the next steps described in the following link https://cloudbeaver.io/docs/Build-and-deploy/

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
Is your CB project in path `C:\devel\my`?

**Comment by miltonchirinos44** [comment]
I am working with the version
![error cloudbeaver -2](https://user-images.githubusercontent.com/52106718/182610358-78e2d7a3-c7bf-479d-8fb6-2cbfb0163590.png)

and clone the following project on my pc
![dbeavercloud-archivos](https://user-images.githubusercontent.com/52106718/182611048-3a345855-0ee6-49b7-b862-c7d21c2d5a59.png)

or what steps do I have to follow to raise the project in eclipse I was following the following link https://cloudbeaver.io/docs/Build-and-deploy/

Is it possible that you can help me

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
you should set the path of your cb project+`/deploy/cloudbeaver/` to that place
![image](https://user-images.githubusercontent.com/59531286/182612893-77b715af-0a0e-4d32-ae5a-687d75a25f96.png)

**Comment by miltonchirinos44** [comment]
I already corrected the route that leads to` deploy\cloudbeaver\`and bugs fixed
![dbeavercloud-error run](https://user-images.githubusercontent.com/52106718/182619795-ea1ce67d-bd93-46aa-8e62-3d579a153955.png)

when I run RUN I get the following error
![error run cloudbeaver](https://user-images.githubusercontent.com/52106718/182622030-ff58c03d-30a3-4442-9860-8dcb53a47eaa.png)

the log that it generates is the following
[error del log.txt](https://github.com/dbeaver/cloudbeaver/files/9251789/error.del.log.txt)

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
Have you added DBeaver project to Eclipse?

**Comment by miltonchirinos44** [comment]
@yagudin10 
if I have added the cloud dbeaver
![cloud contenido en eclipse](https://user-images.githubusercontent.com/52106718/182625385-bfe00884-2d86-4467-a3e0-33e52df8b0a8.png)

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
You need to add [DBeaver project to Eclipse IDE](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse)

**Comment by miltonchirinos44** [comment]
@yagudin10 
I tell you that I already installed dbeaver but I still get the same error when I run RUN CONFIGURATION
![ERROR2](https://user-images.githubusercontent.com/52106718/182677300-64fa767b-ed8f-4cdc-8554-f6edc18f2ea6.png)

![ERROR3](https://user-images.githubusercontent.com/52106718/182677816-7ddfa64a-8291-404c-a613-d44232c72e57.png)

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
try to add required plug-ins to CB run configuration file (as shown [here](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse#include-plugins-in-the-debug-info))

**Comment by miltonchirinos44** [comment]
@yagudin10 
I tell you that I already made the configuration of the plugins
![error cloud](https://user-images.githubusercontent.com/52106718/183088877-b1318e78-d431-4f44-9130-78d4fb628417.png)

I have configured dbeaver and cloud dbeaver, and I get the following error
![segundo error](https://user-images.githubusercontent.com/52106718/183089269-24e97f48-7cc2-40f1-8e97-bb88bc6f85e0.png)

**Comment by miltonchirinos44** [comment]
@yagudin10
or what is the correct way to compile cloud dbeaver?

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
did you build and run cloudbeaver by run-server script?

**Comment by yagudin10** [comment]
If yout want to debug in Eclipse IDE, you need to:
- [Build and deploy CB](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy#build-and-deploy)
- [Add DBeaver project to Eclipse IDE](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse)
- [Add CB project to Eclipse IDE](https://github.com/dbeaver/cloudbeaver/wiki/Develop-in-Eclipse)
- If there are some errors in packages - update them and add required plug-ins
- [Set the working directory to the configuration](https://github.com/dbeaver/cloudbeaver/issues/988#issuecomment-1203913065)
- Run the configuration

**Comment by miltonchirinos44** [comment]
@yagudin10 
I followed all the steps you mentioned but I still get the same error
![ultimos pasos](https://user-images.githubusercontent.com/52106718/183149692-88252a49-ca4a-4040-b4de-590570a8c18d.png)

**Comment by miltonchirinos44** [comment]
@yagudin10
dbeaver is the only project that raises well
![dbeaver bien](https://user-images.githubusercontent.com/52106718/183150428-945cc8e7-ada8-40a6-b521-db52c2a3f166.png)
n

**Comment by miltonchirinos44** [comment]
the strangest thing is that when I execute the `dbeaver cloud` server by console the command  .`/run-server.sh` run correctly

![ejecucion cloud](https://user-images.githubusercontent.com/52106718/183152836-fa253243-f221-4ea7-8a72-b995fce52c1d.png)

and view the dbeaver cloud system in the browser `http://localhost:8978`
![http dbeaver](https://user-images.githubusercontent.com/52106718/183153573-8517c0ae-678a-458c-b3f1-c9eb0744b227.png)

but in the code I keep getting errors
![ultimos pasos](https://user-images.githubusercontent.com/52106718/183153852-5da4ac17-a026-4fb7-8c68-b2e9fc8b8ec0.png)

**Comment by miltonchirinos44** [comment]
@yagudin10
I tell you to do all the steps you told me but I keep having problems with these files, it's as if code is missing in these java classes
![Error Proyecto cloud](https://user-images.githubusercontent.com/52106718/183671287-d527c394-3058-4992-afbc-9fae7dd26c5b.png)

can you help me with this error
when I run RUN I get the following error
![Error Proyecto cloud1](https://user-images.githubusercontent.com/52106718/183672715-6f37a92f-fc0c-4f84-8083-2c189ec9ab38.png)

![Error Proyecto cloud2](https://user-images.githubusercontent.com/52106718/183673168-93fe60ec-1fc9-4d85-8182-fdfc8c8bc29d.png)

I get the following error
![Error Proyecto cloud3](https://user-images.githubusercontent.com/52106718/183674039-0df1e647-cc1c-4542-b1cb-4140b3014fe6.png)

I have the following log
[log.txt](https://github.com/dbeaver/cloudbeaver/files/9291610/log.txt)

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
try to update io.cloudbeaver.service.auth bundle via Alt + F5

**Comment by miltonchirinos44** [comment]
@yagudin10 
Update the io.cloudbeaver.service.auth package via Alt + F5, but still the same problem

**Comment by miltonchirinos44** [comment]
@yagudin10 
run package update io.cloudbeaver.service.auth bundlevia Alt + F5 and the same error persists
![image](https://user-images.githubusercontent.com/52106718/184698056-1faed2a3-b6bd-495b-b5e6-5d3964c9dd9d.png)

**Comment by miltonchirinos44** [comment]
@yagudin10
I tell you that I have managed to solve the errors of the tab `Problems ` but now i get the following error
![image](https://user-images.githubusercontent.com/52106718/184981159-03fce477-24e7-4db1-a4f6-f8ef06a3444c.png)
What other configuration do I have to make?

**Comment by yagudin10** [comment]
@miltonchirinos44 ,
Could you show the whole log? It seems like CB can't find H2 driver in the working directory

**Comment by miltonchirinos44** [comment]
@yagudin10 
To date I still get the same error
![error hasta la fecha](https://user-images.githubusercontent.com/52106718/185966891-fbc90a29-ff1d-4ec7-9439-d5f02b5305a2.png)

The log is in the following document
[1661183950560.log](https://github.com/dbeaver/cloudbeaver/files/9395885/1661183950560.log)

**Comment by miltonchirinos44** [comment]
@yagudin10
In the console I have the following error
```
!SESSION 2022-08-23 15:42:45.267 -----------------------------------------------
eclipse.buildId=unknown
java.version=11
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_BO
Framework arguments:  -product io.cloudbeaver.product.ce.product -web-config conf/cloudbeaver.conf
Command-line arguments:  -product io.cloudbeaver.product.ce.product -data C:\Users\SIN\eclipse-workspace8/../runtime-DBeaverWebServer.product -dev file:C:/Users/SIN/eclipse-workspace8/.metadata/.plugins/org.eclipse.pde.core/CloudbeaverServer.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -web-config conf/cloudbeaver.conf

!ENTRY org.eclipse.m2e.core.ui 4 0 2022-08-23 15:42:51.239
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.core.ui [153]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.20211002-1029"; singleton:="true"
       org.eclipse.m2e.model.edit [158]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.500.v202201311924"; singleton:="true"
              org.eclipse.wst.xml.core [193]
                Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.2,3.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.apache.xerces; bundle-version="2.12.2.v20220131-0835"
                     org.apache.xerces [49]
                       Unresolved requirement: Import-Package: sun.io; resolution:="optional"
                       Unresolved requirement: Import-Package: org.apache.xml.resolver

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.m2e.model.edit 4 0 2022-08-23 15:42:51.250
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.model.edit [158]
  Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.500.v202201311924"; singleton:="true"
       org.eclipse.wst.xml.core [193]
         Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.2,3.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.apache.xerces; bundle-version="2.12.2.v20220131-0835"
              org.apache.xerces [49]
                Unresolved requirement: Import-Package: sun.io; resolution:="optional"
                Unresolved requirement: Import-Package: org.apache.xml.resolver

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.wst.xml.core 4 0 2022-08-23 15:42:51.257
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wst.xml.core [193]
  Unresolved requirement: Require-Bundle: org.apache.xerces; bundle-version="[2.12.2,3.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.apache.xerces; bundle-version="2.12.2.v20220131-0835"
       org.apache.xerces [49]
         Unresolved requirement: Import-Package: sun.io; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.resolver

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://247.fwk1307417026:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://247.fwk1307417026:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
15:42:52.213 [main] DEBUG i.c.model.app.BaseWebApplication - Loading configuration from C:\devel\my\cloud8\cloudbeaver\deploy\cloudbeaver\conf\cloudbeaver.conf
15:42:52.216 [main] DEBUG io.cloudbeaver.server.CBApplication - Using configuration [conf/cloudbeaver.conf]
15:42:52.216 [main] DEBUG io.cloudbeaver.server.CBApplication - Read configuration [C:\devel\my\cloud8\cloudbeaver\deploy\cloudbeaver\conf\cloudbeaver.conf]
15:42:52.681 [main] DEBUG io.cloudbeaver.server.CBApplication - Load product configuration from 'C:\devel\my\cloud8\cloudbeaver\deploy\cloudbeaver\conf\product.conf'
15:42:52.834 [main] DEBUG io.cloudbeaver.server.CBApplication - CloudBeaver CE Server 22.1.5.qualifier is starting
15:42:52.834 [main] DEBUG io.cloudbeaver.server.CBApplication - 	OS: Windows 10 10.0 (amd64)
15:42:52.834 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Java version: 11 by Oracle Corporation (64bit)
15:42:52.835 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Install path: 'C:\Users\SIN\eclipse\rcp-2022-03\eclipse'
15:42:52.835 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Global workspace: 'file:/C:/Users/SIN/runtime-DBeaverWebServer.product/'
15:42:52.835 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Memory available 99Mb/512Mb
15:42:52.872 [main] DEBUG io.cloudbeaver.server.CBPlatform - Initializing product: CloudBeaver CE Server 22.1.5
15:42:52.873 [main] DEBUG io.cloudbeaver.server.CBPlatform - Host plugin: io.cloudbeaver.product.ce 22.1.5.qualifier
15:42:52.873 [main] INFO  io.cloudbeaver.server.CBPlatform - Initialize web platform...
15:42:53.518 [main] DEBUG o.j.d.runtime.SecurityProviderUtils - BounceCastle bundle found. Use JCE provider BC
15:42:55.618 [main] DEBUG o.j.d.registry.BasePlatformImpl - Initialize base platform...
15:42:56.943 [main] DEBUG o.j.d.r.DataSourceProviderRegistry - Total database drivers: 95 (95)
15:42:57.034 [main] INFO  io.cloudbeaver.server.CBPlatform - Available drivers: ClickHouse (Legacy),ClickHouse,DB2 LUW,DB2 iSeries/AS 400,Firebird,Derby Server,Trino,H2 Embedded,MS SQL Server / SQL Server,MySQL,MariaDB,Oracle,PostgreSQL,SQLite
15:42:57.055 [main] INFO  io.cloudbeaver.server.CBPlatform - Web platform initialized (4182ms)
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Content root: C:\devel\my\cloud8\cloudbeaver\deploy\cloudbeaver\web
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Drivers storage: C:\devel\my\cloud8\cloudbeaver\deploy\cloudbeaver\drivers
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Listen port: 8978 on all interfaces
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Base URI: /api/
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Production mode
15:42:57.055 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Server is in configuration mode!
15:42:57.500 [main] DEBUG io.cloudbeaver.server.CBApplication - 	Local host addresses:
15:42:57.501 [main] DEBUG io.cloudbeaver.server.CBApplication - 		127.0.0.1 (127.0.0.1)
15:42:57.501 [main] DEBUG io.cloudbeaver.server.CBApplication - 		172.26.65.99 (S-NAL-GTIC-686.sin.gobierno.bo)
15:42:57.502 [main] DEBUG io.cloudbeaver.server.CBApplication - 		192.168.56.1 (S-NAL-GTIC-686.sin.gobierno.bo)
15:42:57.502 [main] DEBUG io.cloudbeaver.server.CBApplication - 		172.27.64.1 (S-NAL-GTIC-686.mshome.net)
15:42:57.933 [main] DEBUG i.c.service.security.db.CBDatabase - Initiate management database
15:42:58.511 [main] DEBUG i.c.service.security.db.CBDatabase - 	Initiate connection pool with management database (H2 Embedded; jdbc:h2:C:\Users\SIN\runtime-DBeaverWebServer.product/.data/cb.h2.dat)
15:42:59.900 [main] ERROR io.cloudbeaver.server.CBApplication - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:193)
	at io.cloudbeaver.service.security.EmbeddedSecurityControllerFactory.createSecurityService(EmbeddedSecurityControllerFactory.java:57)
	at io.cloudbeaver.server.CBApplication.createGlobalSecurityController(CBApplication.java:464)
	at io.cloudbeaver.server.CBApplication.initializeSecurityController(CBApplication.java:460)
	at io.cloudbeaver.server.CBApplication.startServer(CBApplication.java:320)
	at io.cloudbeaver.model.app.BaseWebApplication.start(BaseWebApplication.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.validateUserAndPassword(Engine.java:366)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:186)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at io.cloudbeaver.service.security.db.CBDatabase.initialize(CBDatabase.java:173)
	... 18 common frames omitted
15:42:59.914 [Framework stop - Equinox Container: 128c6931-6804-43a4-a8e4-c157fcd581c3] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown Core...
15:43:00.072 [Framework stop - Equinox Container: 128c6931-6804-43a4-a8e4-c157fcd581c3] DEBUG io.cloudbeaver.server.CBPlatform - Shutdown completed in 158ms

!ENTRY org.eclipse.core.jobs 2 2 2022-08-23 15:43:01.396
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob
```

**Comment by miltonchirinos44** [comment]
@yagudin10  
Thanks for the help, I fixed the error.

**Comment by kseniaguzeeva** [comment]
I'm glad to hear it. Feel free to create new tickets if you have some questions or suggestions.

**Comment by Amor7527** [comment]
Hello, how do you solve this problem?
